### ISSUE TITLE
Site claims "successful login" on console output but doesn't login session

### ISSUE THREAD

**Issue by tigwyk** [moloch--/RootTheBox#101]
I'm attempting to login as either of my two users (admin and a player user). When I put in the username and password and click login, the console output says: 
[I 150820 17:14:42 PublicHandlers:91] Successful login: admin from (my ip)
[I 150820 17:14:42 web:1908] 302 POST /login (my ip) 775.96ms
[I 150820 17:14:42 web:1908] 302 GET /user (my ip) 2.51ms
[I 150820 17:14:42 web:1908] 200 GET /login (my ip) 11.80ms

But it just refreshes the login page and doesn't log me into a session at all. The menu at the top remains the same (login, registration, etc) and I'm unable to do any administration.

As the player account, the same behaviour occurs.

I think I set everything up correctly, but obviously I can't be sure. If I turn on verbose logging then it just prints more info but still seems to think it's logging me in correctly. Any ideas?

Running on Debian 8.1 x64.

**Comment by moloch--** [comment]
Make sure `memcached` is running.

**Comment by tigwyk** [comment]
Excellent, I'll check. It probably is related to that since I noticed some other dependencies I had to manually fix. For some reason the mysql stuff failed to install via the dependencies script but I got all that fixed up eventually. Thanks for the quick feedback!
