### ISSUE TITLE
Add flag attachments

### ISSUE THREAD

**Issue by tinmartinet** [moloch--/RootTheBox#104]
Hi!

In the administrator panel, I saw the possibility for flags to have attachements. But I can't find where to add an attachement ... Neither in the creating flag form, nor in the update form.

Thanks for RootTheBox :+1:

**Comment by moloch--** [comment]
Yes, this is on the agenda for the future! However, at present the best I can recommend is to post a link in the description to any additional materials.

**Comment by tinmartinet** [comment]
Oh nice ! I will do so. Thanks.

**Comment by jeffg2k** [comment]
An administrative section for adding game materials was added in https://github.com/moloch--/RootTheBox/commit/ce239c609ecf1cff65c7333ca7fd1e03b1067c18  Using that with a reference from the flag description should solve this issue.
