### ISSUE TITLE
Successful login but no access to user page

### ISSUE THREAD

**Issue by remi1411** [moloch--/RootTheBox#106]
Hi !

First, many thanks for your tool !
i would like to support Rootthebox on my mac, nevertheless i have a bug when i would to connect with my admin user ( no problem with linux distrib ).. i have a login successful in the log of the server but just after the success i have a refresh of the page.. 
[I 150917 21:00:30 web:1908] 302 POST /login (127.0.0.1) 556.24ms
[I 150917 21:00:30 web:1908] 302 GET /user (127.0.0.1) 0.98ms
[I 150917 21:00:30 web:1908] 200 GET /login (127.0.0.1) 1.63ms
Furthermore, the login counter is incremented in mysql database.

Do you have an idea of the problem ?

Thanks in advance for your help,

**Comment by moloch--** [comment]
Is `memcached` running?

**Comment by remi1411** [comment]
Thanks ! In fact, memcached daemon is not running by default...
