### ISSUE TITLE
Score board and History

### ISSUE THREAD

**Issue by sfulol** [moloch--/RootTheBox#107]
Is the score board and history supposed to update in real time? As in you can see the chart grows when teams score points? If it is, then mine certainly don't.

My config for web socket is ws://127.0.0.1:8888 and I host it locally on a LAN. Any ideas?

**Comment by moloch--** [comment]
Make sure you have the [origin](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#origin) set correctly, if it's set to `127.0.0.1` you'll only be able to connect from the machine running the engine itself! Unfortunately there's no great way to automatically detect this setting, but the Bootstrap 3 re-write of the front-end should remove the need to manually set this most of the time.

**Comment by jeffg2k** [comment]
This issue appears to be answered and covered in the Wiki.  @moloch-- did you want to leave it as an open question or are we good to close it?
