### ISSUE TITLE
Windows bot message

### ISSUE THREAD

**Issue by kumux** [moloch--/RootTheBox#109]
Using the compiled Windows bot I'm having an issue where it doesn't respond to the challenge sent by the server.  I get the message below, that appears to not be outputting the 'message'.  Not sure what it is if I'm doing something wrong.

[*] 10:36:28 Status : Successfully connected to command & control ...
recv: '\x81D{"xid": "69c003fdfa9c24d46dcffe47a2c08820", "opcode": "interrogate"}'
'message'

**Comment by moloch--** [comment]
We just made some changes to this code, and it's still a little buggy, looking into it.

**Comment by AnarKyx01** [comment]
moloch, see last comment....
https://github.com/moloch--/RootTheBox/pull/97#issuecomment-108040248

**Comment by kumux** [comment]
Thanks compiled from source and works great!

**Comment by jeffg2k** [comment]
This appears to be resolved based on this discussion - closing.  Reopen if needed.
