### ISSUE TITLE
Cannot delete hints

### ISSUE THREAD

**Issue by nbven** [moloch--/RootTheBox#115]
Cannot delete hints with the following message:
"ERROR: Hint does not exist in database."

**Comment by Joeviocoe** [comment]
It would be great if there were a workaround to at least manually delete/edit hints.  Right now, I cannot do anything to hints once created.

**Comment by moloch--** [comment]
You can possibly manually DROP the row from the database, but I'm not sure if that will cause integrity errors or not.

**Comment by F13** [comment]
Fixed! ...finally :)
