### ISSUE TITLE
./rootthebox.py --save basestring not defined.

### ISSUE THREAD

**Issue by nmbarker** [moloch--/RootTheBox#120]
Info:
I'm working from pyvenv
Heres the log:
(Poliastro) bash-3.2$ ls
LICENSE     files       models      setup       tests
README.md   handlers    modules     static
bot     libs        rootthebox.py   templates
(Poliastro) bash-3.2$ ./rootthebox.py --save
Traceback (most recent call last):
  File "./rootthebox.py", line 289, in <module>
    type=basestring)
NameError: name 'basestring' is not defined
(Poliastro) bash-3.2$

Edit: I fixed it somehow, but now things such as define statements are being called invalid syntax.

**Comment by moloch--** [comment]
Looks like you may be running under Python 3 which isn't yet supported.

**Comment by noraj1337** [comment]
I made a PR https://github.com/moloch--/RootTheBox/pull/131

**Comment by noraj1337** [comment]
See https://github.com/moloch--/RootTheBox/issues/35

**Comment by jeffg2k** [comment]
Closing this issue as it's covered more generally in #35 and this particular issue was resolved in #131
