### ISSUE TITLE
No admin pannel shown

### ISSUE THREAD

**Issue by ezracyber** [moloch--/RootTheBox#121]
![screenshot from 2016-03-14 13-40-53](https://cloud.githubusercontent.com/assets/17825332/13742031/6dff118e-e9d1-11e5-9661-4e174c399eb2.png)

**Comment by BitSledge** [comment]
To access the admin panel, I believe you have to connect with a whitelisted IP address (add the IP in the config file).

**Comment by moloch--** [comment]
Ensure `memcached` is running/configured properly.

**Comment by ezracyber** [comment]
thanks i configure the memcached and running it with memcached &
Much thanks ...
