### ISSUE TITLE
Admin panel noob alert

### ISSUE THREAD

**Issue by oolivero45** [moloch--/RootTheBox#122]
Whenever I navigate to the admin panel, I get shown the noob alert page. Logging in doesn't help - it seems like it's not actually signing me in.

**Comment by moloch--** [comment]
Ensure memcached is running and configured properly, please note that to access the admin planel you log in normally as the admin user, `/admin` doesn't exist.

**Comment by oolivero45** [comment]
Thank you, that fixed it :)

**Comment by noraj1337** [comment]
`sudo systemctl start memcached` solved the issue
