### ISSUE TITLE
db connection driver problem

### ISSUE THREAD

**Issue by CingulateCortex** [moloch--/RootTheBox#123]
hi 

giving a try on debian, mysql. 

configured cfg file regarding mysql user, pass etc. mysql server is up and running. Installed dependencies with the sh script. However getting below error. 

root@csr-ctf:/home/ctf/RootTheBox# ./rootthebox.py --setup=prod
[*] 18:35:43 : Creating the database ...
[C 160502 18:35:43 DatabaseConnection:84] Cannot connect to database with any available driver

Thanks

**Comment by moloch--** [comment]
Re-run `pip install mysql-python --upgrade` and see if you get an error, iirc Debian doesn't install one of the MySQL client files via the same package as Ubuntu so you need to manually `apt-get` it.

**Comment by ottodeng** [comment]
@CingulateCortex Have you solve it? I am same to your situation.

**Comment by crystof5** [comment]
hi, i have the same problem. I try all solution and that no work... Can you help me? 
thank 's a lot

**Comment by moloch--** [comment]
This is generally due to a missing `libmysqlclient-dev` at the time you install the Python packages, try manually installing this package for your respective distro (on Debian it should be `apt-get install libmysqlclient-dev` and then re-running the Python dependency script.

**Comment by jeffg2k** [comment]
Trying to install RootTheBox and running into this issue.  I installed it in two different Ubuntu 16.04 VMs with the same issue.  apt-get install libmysqlclient-dev reports "libmysqlclient-dev is already the newest version".  So that did not solve the problem for me.  I also installed the various pip suggestions in #147 but that also didn't help.

I installed everything via the instructions in the Wiki.

**Comment by jeffg2k** [comment]
I think we got this all worked out in the install scripts - closing.

**Comment by nmiodice** [comment]
Just ran into this issue and found the issue to be that my DB enforced SSL connections, but there is no way for me to specify these options when running the dockerized variant of the application.

A fix was to disable enforcement of SSL, but this is far from ideal. @moloch-- , is there something we can do about the application code to fix this?

**Comment by oreodejobi** [comment]
> Problem was that my "save" of the rootthebox.cfg did not take and thus had the incorrect password. Working now :)

i'm having the same issue, so what did you do to resolve yours?
