### ISSUE TITLE
depends.sh - Ubuntu 14.04 x32

### ISSUE THREAD

**Issue by benichmt1** [moloch--/RootTheBox#124]
For some reason when I went to run the install script, I kept getting the below error and the packages would not install on a fresh ubuntu 14.04 box.

<code>
terminate called after throwing an instance of 'std::out_of_range' 
what():  basic_string::compare
./depends.sh: line 80:  6730 Aborted 
</code>

I was able to fix this manually by just doing
<code>
sudo apt-get install python-pip python-dev build-essential 
</code>
to install pip myself.

**Comment by moloch--** [comment]
Good to know, I'll update the script accordingly.
