### ISSUE TITLE
Distribution of premade games. 

### ISSUE THREAD

**Issue by kdb424** [moloch--/RootTheBox#125]
Are there currently any pre made games that anyone has found or has made that can be shared? I am setting up a local competition and don't want to have to be excluded as I would know too much if I were to set it up myself, not that I am at all incapable. Was hoping there was a way of sharing. If none exists, I'd like to set up a database of pre made games if that would be acceptable to make this more fun and playable more times over. Looking forward to a reply, great work, and thanks for everything.

**Comment by moloch--** [comment]
This is something I've wanted to set up for a long time, but as of yet has not come to fruition. I am working on a v2 of Root the Box that will have point-n-click deployments of existing challenges but this is a ways off as I've not had much time to work on it so far. In short no, but in the future, maybe, depending on my work schedule :-)
