### ISSUE TITLE
Linux Bot

### ISSUE THREAD

**Issue by BitSledge** [moloch--/RootTheBox#127]
What is the proper way to configure the linux bot? Specifically what is the garbage file that it is asking for?

**Comment by moloch--** [comment]
The garbage file generated by the administrator in scoring engine, when you create a box you should be able to download a copy and upload it to the target server(s). This file basically contains some random data which is part of a zero-knowledge proof that confirms the bot has access to the target machines and not running on a box outside the scope of the game.

**Comment by moloch--** [comment]
https://github.com/moloch--/RootTheBox/blob/master/handlers/BotnetHandlers.py#L41

**Comment by jeffg2k** [comment]
I added this information to the [Game Setup Wiki](https://github.com/moloch--/RootTheBox/wiki/Game-Setup-Tutorial).  Closing Issue
