### ISSUE TITLE
Enhancement Request - Option to add more specific URL 

### ISSUE THREAD

**Issue by theHackPot** [moloch--/RootTheBox#129]
Hi,
Enhancement Request - On the Target Management page would it be possible to have an option to specify a URL in the format [IP]:[Port]:[File.extension] e.g. 192.168.1.5:80/file.txt.
I can only see an option to add IP Address.

It would be useful for file based challenges and if the challenge was on a different port {80,443}.

**Comment by jeffg2k** [comment]
Feature added in latest merge
