### ISSUE TITLE
Setting guidelines for repository contributors

### ISSUE THREAD

**Issue by noraj** [moloch--/RootTheBox#134]
> To help your project contributors do good work, you can add a file with contribution guidelines to the root of your project's repository.

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

This may, for example, allow us to know in which branch do PR, coding conventions, etc...

**Comment by noraj1337** [comment]
Update: There is a wiki page https://github.com/moloch--/RootTheBox/wiki/Contributing, but a CONTRIBUTING file in `.github` will allow to show an alert box when users create an issue or a PR.

**Comment by jeffg2k** [comment]
Created the CONTRIBUTING.md file and redirected the Wiki home page link to that file.  Deleted the old contributing Wiki page so we don't have the content in two places.
