### ISSUE TITLE
depends.sh broken

### ISSUE THREAD

**Issue by olibleu** [moloch--/RootTheBox#136]
During setup depends.sh calls python-depends.sh (l.76), but this script doesn't exist anymore as it has been replaced by python2-depends.sh and python3-depends.sh.

**Comment by datnt2308** [comment]
Hi olibleu,
You can run "sh  setup/python2-depends.sh"
My email: datnt2308@gmail.com.
Contact me if you have any question :)

**Comment by jeffg2k** [comment]
The setup could probably check the python version and run the proper file.
