### ISSUE TITLE
404 When adding port with flag IP address

### ISSUE THREAD

**Issue by BitSledge** [moloch--/RootTheBox#139]
when adding an IP address to a box, it only accepts ipaddress not ipaddress:port. It gives a 404 when specifying ports.

**Comment by moloch--** [comment]
Likely an exception on the backend (errors are replaced with 404s on the frontend). Do you have the logs?

**Comment by jeffg2k** [comment]
Related request https://github.com/moloch--/RootTheBox/issues/129

**Comment by jeffg2k** [comment]
Feature added in latest merge
