### ISSUE TITLE
403 - Forbidden

### ISSUE THREAD

**Issue by adamsistron** [moloch--/RootTheBox#141]
How can I fix the following error? Already polled by changing permissions to RootTheBox directory
`

> [W 170830 16:31:21 SecurityDecorators:66] Attempted unauthorized access from 10.x.x.x to /admin/ban/config

`

![imagen](https://user-images.githubusercontent.com/7489516/29896108-56833524-8da1-11e7-8db0-b28c841e468c.png)

**Comment by moloch--** [comment]
Add yourself to the IP whitelist for the admin interface (see wiki for details)

**Comment by adamsistron** [comment]
como debo hacer para agregar un segmento de red?

**Comment by F13** [comment]
I don't believe network ranges are currently supported.
