### ISSUE TITLE
Database Driver

### ISSUE THREAD

**Issue by whitewid0w** [moloch--/RootTheBox#147]
Hi there,

I found this CTF whilst looking for something easy to set up in my school's computer lab. I have followed all of the instructions, but upon execution of the "--setup=prod" command, I am met with an error in regards to connecting to the database with an available driver. I know there's a thread open for this, but it looks kind of abandoned.

All of my config settings have been modified and are correct. Please advise !

**Comment by F13** [comment]
If you're using Debian, the earlier thread recommended attempting `apt-get
install libmysqlclient-dev`. Try that and report back. If you're not on
Debian, what OS are you using?

**Comment by whitewid0w** [comment]
Running into this on the newest Ubuntu build. Tried that command , just in case.

**Comment by F13** [comment]
If your database creds are incorrect, you would see this error. Please verify that you've run the following instructions and have saved the username and password you chose. You'll also need to have correctly set those in the config settings.

* Login to mysql `mysql -u root -p`
* Create a local user `create user '<user>'@'localhost' identified by '<password>'`; Remember your `<user>` and `<password>`, we'll need these later.
* Create the database `create database rootthebox`;
* Setup database permissions `grant all on rootthebox.* to '<user>'@'localhost'`;
* Exit MySQL `exit`
* Clear your MySQL `history echo "" > ~/.mysql_history`

**Comment by whitewid0w** [comment]
Hi there,

I have followed the above steps. I tested on 2 different VM's as well. Created user, created the DB, granted permissions to said user, and exited+cleared mysql history.

To ensure that I wasn't typing something in wrong in the config, I left the "password" field blank in the config file; so that it would prompt me upon running the setup=prod command. It accepts the pass and then hits me with the driver error.

I am using the same credentials to login to mysql (mysql -u root -p (pass) ) that I have designated within the config.

:(

**Comment by F13** [comment]
The error indicates the connection was unsuccessful for some reason or another. This could be an error due to special characters? Try using the default user/pass for the database (just for testing) of rtb/rtb and see if that corrects the error.

If you like, you can modify the RootTheBox/libs/DatabaseConnection.py to give you a little more information, as here:

```python
def _test_connection(self, connection_string):
        [...]
        except Exception as e:
            if options.debug:
                logging.exception("Database connection failed")
            raise e
```
This will allow you to see the text of the exception raised by sqlalchemy and help point to the root cause of the connection failure.

**Comment by whitewid0w** [comment]
Hi there,

Thanks by the way, for taking the time to help me out.

Fresh VM, followed all instructions, using rtb/rtb as defaults.

Used the snippet you gave me , here is what I got back:

Traceback (most recent call last):
  File "./rootthebox.py", line 465, in <module>
    setup()
  File "./rootthebox.py", line 65, in setup
    from setup.create_database import create_tables, engine, metadata
  File "/home/CTF/RootTheBox/setup/create_database.py", line 21, in <module>
    from models import engine
  File "/home/CTF/RootTheBox/models/__init__.py", line 30, in <module>
    from libs.DatabaseConnection import DatabaseConnection
  File "/home/CTF/RootTheBox/libs/DatabaseConnection.py", line 95
    return True

**Comment by whitewid0w** [comment]
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'rootthebox'")

Unknown DB? I just set it up though ) :

**Comment by whitewid0w** [comment]
Final post. I was able to get this working by re-creating the DB.

Some modules that I had to pip install manually:

nose
tornado
sqlalchemy
pbkdf2
netaddr

Hopefully you can add these to the python setup script.

Thank you for your help!

**Comment by F13** [comment]
Thanks for reporting back.

Just clarifying - the current depends script calls `python-depends.sh` but that was split out into `python2-depends.sh` and `python3-depends.sh`. The script definitely needs to be updated to call the correct file, but in the mean time, you need to manually run the appropriate python dependency installer (in your case that would likely be `python2-depends.sh`).
