### ISSUE TITLE
Cannor connect to database

### ISSUE THREAD

**Issue by joerobinson7** [moloch--/RootTheBox#149]
When I get to the ./rootthebox.py --setup=prod command I receive this error. I read the other open ticket on this issue, but it didn't fix it for me.

**Comment by F13** [comment]
Please confirm you manually ran the appropriate `python-depends` scripts after installation - that was part of the issue before. If that's not the issue, patch the DatabaseConnection.py as referenced [here](https://github.com/moloch--/RootTheBox/issues/147#issuecomment-352874017) in #147. That will help you identify the specific error sqlalchemy is returning.
