### ISSUE TITLE
io_loop Error on ./rootthebox.py --start

### ISSUE THREAD

**Issue by redhataugust** [moloch--/RootTheBox#152]
Kindly, could someone help me past this?

![io_loop-issue](https://user-images.githubusercontent.com/39546710/40405030-a8ec2c50-5e0f-11e8-84df-3400796073f9.PNG)

I tried this on Ubuntu 16-04 server and desktop. The screenshot is on desktop. I did some Googling and it indicated it was possibly an issue with Tornado? I don't know how to get past this roadblock. When I try to access the URL, it doesn't find anything.

As an aside, the setup/python-depends.sh doesn't work, so I'd suggest adding the extra direction to go to that directory and running the appropriate one for which python version the person has installed. In my case, I ran the python2-depend.sh script.

**Comment by moloch--** [comment]
Install a version of Tornado prior to v5:

```
pip install tornado==4.5.3
```

**Comment by redhataugust** [comment]
Thank you! This did it! :-D
