### ISSUE TITLE
Start Issue - unexpected keyword argument 'io_loop'

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#153]
I've gotten everything to work up until the --start.  I get this error.
```
jeff@ubuntu:/usr/local/RootTheBox$ sudo ./rootthebox.py --start
[I 180528 09:37:21 GameHistory:53] Loading game history from database ...
[I 180528 09:37:21 GameHistory:67] History load complete.
Traceback (most recent call last):
  File "./rootthebox.py", line 467, in <module>
    start()
  File "./rootthebox.py", line 43, in start
    from handlers import start_server
  File "/usr/local/RootTheBox/handlers/__init__.py", line 231, in <module>
    io_loop=io_loop
TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by jeffg2k** [comment]
Looks like the issue is Tornado.  I downgraded the version to tornado==4.4.3 and it's now running fine.  I found some threads where versions >= 4.5 may have this issue.

**Comment by moloch--** [comment]
This is generally from breaking changes in Tornado v5, so anything prior to that should work.

**Comment by jeffg2k** [comment]
Cool - I tried 4.5.3 and it does appear to work fine.  I've specified it in the requirements of my fork if you want me to issue a pull request until you get around to looking at the changes in v5.  Also added a check for Python2 or Python3 so the correct depends script runs.  https://github.com/jeffg2k/RootTheBox

I'm still comparing RootTheBox to other CTF software, but I really like it.  So far, I think I like RTB and CTFd the most.  On RTB, there are a few things I'd like to work on if I do use it.  Right now it is very Offensive focused, where my use is Defensive (Digital Forensics / Incident Response / Malware Analysis).  So not sure if I care for the whole, $ / bank setup.  I'd rather just have something that said points / score.  I'd also like an option that doesn't focus on teams, just individual players.  I wish the hints were tied to the flags and not the box.  Would also like to see penalties for missed questions.

**Comment by moloch--** [comment]
Yea, RTB is less maintained than it used to be just because my day job consumes all my time these days :)  --I used to work with ColdHeat (developer of CTFd) and that's a great piece of software too and from your description I think it fits your use case a bit better. I'd love to keep adding features and configuration options but I simply don't have the time these days.

**Comment by moloch--** [comment]
@jeffg2k  Happy to take a look at any pull requests, the best way would be to integrate or write a few wrapper scripts around [Alembic](http://alembic.zzzcomputing.com/en/latest/), which is designed for migrating SQL Alchemy schemas

**Comment by jeffg2k** [comment]
Might make sense for me to create a new branch since I'm making a lot of additions - 0.7.0 beta or something.  Just not sure how a pull request works on a branch - haven't done that before.
