### ISSUE TITLE
Delete a Team

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#156]
I'm not seeing it, but is there a handler for deleting a team?  If you delete the players under a team, the team remains and I don't see a way to delete it via the interface.  Attempting to delete a team from the database results in failure due to all the foreign keys.  Hope to look into it at some point, but my sql foo is not super strong.

**Comment by moloch--** [comment]
This is to avoid cascading issues with the "Scoreboard History" feature, if you delete a team from the database it messes with the foreign keys in the history table, it was simpler to just not allow deleting them but we certainly could add the feature.

**Comment by jeffg2k** [comment]
The reason I ask is that in the version I'm working on, I created an option to "disable teams", so it's just a player competition.  Due to the design of RtB, it was easiest to do this by just making a team of 1 and changing the nomenclatures, for example - team -> player.  So for me, it's not so much about deleting a team, but deleting a player.  When I delete the user, the team remains.  When the game is configured in this way, I'd like to auto-delete the team when the user is deleted.

**Comment by jeffg2k** [comment]
One option is just to add a "_deleted" column to the team.  Then we could just exclude team queries where _deleted = not null.

**Comment by jeffg2k** [comment]
Or perhaps even simpler, if in Player Mode, if team has 0 users, don't list it.
