### ISSUE TITLE
Session Age

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#157]
The session age is way too quick for me.  I see there is a configuration option for session_age and session_regeneration_interval.  However, they seem to do nothing.  Searching the code, I don't see that they're actually being used anywhere other than being defined.  Looking at the Sessions.py, I see a DURATION=30 variable that seems to be what I might expect for the session age.  The refresh() seems to also use the duration variable. Could you take a quick look at this.  Should session_age be set to DURATION?

**Comment by moloch--** [comment]
Yea I think the options are old old code that got re-written at some point, ideally we should use what the user specifies in `options.foo`

**Comment by jeffg2k** [comment]
Cool - thanks
Addressed in https://github.com/jeffg2k/RootTheBox/commit/3d36284fdc24ab86872c7d4fc1c759cd0287fe9e
