### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#158]
I'm looking at expanding the default avatar options or by providing team avatars for the users to select from if they don't want to upload their own.  Similarly it would be nice to include some additional box images.  The only one currently in there is the SW Force Unleashed.  Would you be adverse to accepting more if they're not under open licensing?  For example, here is a pack I've put together for an upcoming game I'm planning.  Could include it zipped or not, even pw protected and could remove it if they ever ask...
[marvell-pack.zip](https://github.com/moloch--/RootTheBox/files/2087276/marvell-pack.zip)

**Comment by moloch--** [comment]
Yea we should probably avoid including protected content, the inclusion of the Force Unleashed was mot of a place holder I always meant to replace, it'd be better to switch to free/public domain stock photos of "hackers" or something like that.

**Comment by jeffg2k** [comment]
I'll see what I can find that doesn't overly promote some group, such as Anonymous.  You won't find me uploading any Guy Fawkes masks - not a fan.  And I hesitate to use some hoodie wearing stereotype.  Maybe just some generic computer security images or matrix style code.. idk. haha

**Comment by moloch--** [comment]
Sounds good.

**Comment by jeffg2k** [comment]
If I make new directories for box, team, user where the admin can place new avatars, do you suggest I create them in files/avatars or would you prefer static/images or static/avatars?

**Comment by moloch--** [comment]
yea just make sure the user files are put into a separate directory from the built-in ones, the exact structure isn't super important (and throw away any user provided file names too --pretty sure the current code does this already).

**Comment by jeffg2k** [comment]
Would you be adverse to adding a link in the readme or wiki to avatar packs hosted elsewhere that were designed for RTB?  I fully understand not wanting them included in the code repo and by that extent, I can also see not wanting them linked, but figured since I created on, would be useful for others.  No worries if not.  Just figured I'd ask.  

I'm finishing up the main coding that I had planned (hope to be done tomorrow) and plan to start beta testing with users this week and next.

Still need to go through the issue list here to see if there are things I can fix or add.  It looks like there are issues still open that appear to be fixed, but I'll try to review what is left.

Also, I seem to notice that I'm always having "Start the Game"... I haven't looked, but is there some time period where it stops?  Maybe it's just because I'm in debug and live coding can cause it to stop.  I've almost thought about a config option that recalls the last known state and auto-starts if not in a stopped state.

**Comment by moloch--** [comment]
I open to linking to packs of images, I don't think there's anything wrong with that. As far as "Start Game," iirc if you restart the server it will pause the game, and if you're running in debug mode it will automatically restart the server when you save/modify a Python file.
