### ISSUE TITLE
Change password errors

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#164]
Hey,
First of all, fantastic tool and appreciate the support so far.

After registering a user, I'm unable to change their password after logging in as them. If I configure a min length of 6 as admin for example, I can register a user with a 6-char pw, but after logging in and trying to change it, I receive "ERROR: Password must be at least 6 characters". Increasing the password to 8, 10 or anything else results in an identical error.

I found in /handlers/AdminHandlers/AdminGameHandlers.py there was a line:

`self.config.min_user_password_length = self.get_int('min_user_password_length', '16')`

which I tried setting to lower numbers, but nothing changed and I don't think I'm in the right area anyway.

**Comment by jeffg2k** [comment]
Thanks for the report and complement! I've pushed an update that should fix this.
