### ISSUE TITLE
Global Notification Toggle

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#166]
The more I explore this platform the more I think there's little out there that competes with it, in particularly aesthetically :)

Are there any plans to allow the disabling of _global_ notifications through admin config? i.e. Players get to see their own notifications but it's private to them so other players can't see them?

I tried manually editing the MissionHandler code to do it, but alas, I'm not very good in Python!

**Comment by jeffg2k** [comment]
Might need @moloch-- to take a look at this.  I'm not sure how to let the EventManager know which user / team created the event.  If he can tell me how to do that, then I think we can offer a filter option to limit the notification to the team.

**Comment by jeffg2k** [comment]
I think I figured this out. 👍 Give it try when you get a chance.

**Comment by moloch--** [comment]
Yea RtB was the first app I ever wrote that used WebSockets and used real-time communication, as such the EventManager isn't quite as polished/doesn't have a clean design. It works but it may need to get refactored to cleanly support more features like this.

**Comment by stealthsploit** [comment]
Works well, thanks very much.
