### ISSUE TITLE
Flag file upload

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#168]
It would be awesome if when creating a flag for a box that files could be uploaded for it, for example, a box might have a flag which is 'Download this password hash and crack it'.

**Comment by jeffg2k** [comment]
I'd suggest using the Game Materials for this.  Place the directory / file in the Game Materials, then in your flag question reference the file in Game Materials (which is a tab under tools).

**Comment by stealthsploit** [comment]
Ah yea my bad, missed this, thanks.
