### ISSUE TITLE
Optional OS setting

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#169]
For certain challenges, e.g. OSINT related ones and others, it would be useful to be able to create a box without having a mandatory OS option, so that if not selected, it's removed from the box description including any linked avatar.

**Comment by jeffg2k** [comment]
This should already exist.  There should be a "None" option that does what you describe.

**Comment by jeffg2k** [comment]
Looks like we don't have the OS options in the Edit Box, so I'll add those.

**Comment by stealthsploit** [comment]
Thanks.
