### ISSUE TITLE
Optional Avatar

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#170]
Could avatars be optional when creating a box, meaning if not selected the box's description box uses full width on the screen?

P.S. Truly sorry for the barrage of recent comments/requests on here and am very grateful for all the help!

**Comment by jeffg2k** [comment]
I added an option that you could set the box avatar to none.  This will hide the image from all pages and extends the description area on the box mission page.

**Comment by stealthsploit** [comment]
Cheers!
