### ISSUE TITLE
Registration pause

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#172]
Hello there,

I have a case that is "Pause the registration while the ctf is running" what should i do ?

Suggestion:
add a new feature to disable registration page while the game is running

Thanks

**Comment by jeffg2k** [comment]
If you need something immediate, then I'd suggest maybe modifying the __init__.py line 76

Change this
`(r'/registration', RegistrationHandler),`
To this
`(r'/registration', HomePageHandler),`

That should redirect anyone clicking on Registration back to the home page.

I'll work on this as I work on the Freeze Scoreboard feature, as I think they'll both live on the Admin Home page.

**Comment by jeffg2k** [comment]
Or you could remove Registration menu from the templates/menu/public.html

**Comment by jeffg2k** [comment]
Code pushed - added Pause Registration button to Admin Home.
