### ISSUE TITLE
All levels accessible

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#183]
Hey, is there a way to make all levels (and boxes/flags therein) to be accessible from the start? I've created multiple levels all 'unlocked', however they aren't viewable from the home screen until a player completes all boxes in the first level.

I was looking to have Linux, Windows and Mac levels, each with multiple boxes etc, but all could be attempted in any order the player wishes.

**Comment by jeffg2k** [comment]
Thanks for the report - should be fixed. https://github.com/moloch--/RootTheBox/commit/4cd6bdde2e3818163be45ce426731c6d9832e602
