### ISSUE TITLE
Limit Flag Attempts

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#185]
Is there a way an admin can limit flag attempts for users (irrespective of whether hints are added or not)?

**Comment by jeffg2k** [comment]
I don't think we have a max attempts yet, but you could set the penalty to 100% after X attempts, making further attempts pointless as far as scoring.

**Comment by jeffg2k** [comment]
Here is what I'm thinking will happen when the player reaches max attempts:

- submit disabled (no points & no further penalties if enabled)
- unclaimed hints disabled
- color change (instead of the green w/ check - maybe yellow, red, blue, or gray with a disabled icon)
