### ISSUE TITLE
DB Upgrade Check

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#189]
I hesitate when we get new requests that change the database schema as it breaks the platform for users that sync with git, until they run the proper SQL.  It would be nice if we could do a db sanity check as the application starts and either fix the issue (maybe rerun /setup/create_database.py) or inform the user that we need a db update and to check /setup/dbupdate.sql for version changes.

This might be of help: [Check database schema matches SQLAlchemy models on application startup
](https://stackoverflow.com/questions/30428639/check-database-schema-matches-sqlalchemy-models-on-application-startup)

Maybe it could also check that we have all the needed packages in case we add a new requirement.

**Comment by moloch--** [comment]
https://alembic.zzzcomputing.com/en/latest/ - may also be a good option
