### ISSUE TITLE
Flag reordering

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#190]
It might be useful to have the ability to reorder flags within a box. There have been times where for example I've got a box with 10 flags and I want to move flags 8, 9 and 10 into positions 1, 2 and 3, and have had to delete all the flags and re-write.

**Comment by jeffg2k** [comment]
Since this will likely require a DB change to add an "order" column, it would be best to wait until #189 is completed.  I'm working on it now, but not sure how long it will take.

**Comment by jeffg2k** [comment]
You can now order the flags via dragging.
