### ISSUE TITLE
Time based points rewards 

### ISSUE THREAD

**Issue by garanews** [moloch--/RootTheBox#193]
It will be useful to have this kind of feature.
I'm thinking to an user that to go ahead through the game (story mode) is using the hints and these hints will reduce the points. For the next box maybe the user will have few points and not possible to use hints and go ahead.
Maybe a feature that will permit to earn some point to use hint and go ahead through the game would be useful.
What do you think?
Thanks

**Comment by garanews** [comment]
Yes, something like that (I would use points instead $, but concept is the same).
And another thing: something like the starting points, because if an user is not able to achieve the first flag, cannot ask for hint. So the workaround for this was create a box for training with some question like "write: hello world" in order to earn some points and go through the real questions with the possibility to ask for hints.

**Comment by jeffg2k** [comment]
There is also the option to reduce the cost of the hints.  Maybe make the first hint free or hints on the first level free.  I'm following the SANS Netwars model in my game, where hints are free but the scoreboard shows you took a hint and they're weighed in the scoring.  I also employ the penalties where the first guess is free, but subsequent guesses take a 20% deduction of the flag value to a max of 60% (3 wrong attempts).

When using money, we do allow a starting value as part of the story, but I set that value to 0 when the game switches to using points.  So we could rethink how we do that.  Alternatively, we could add an option in #184 to grant a reward to all teams.

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/49386183-f82f7100-f716-11e8-8ac6-a98c029c5283.png)
![image](https://user-images.githubusercontent.com/16938405/49386208-03829c80-f717-11e8-94be-f742050c6a1c.png)
![image](https://user-images.githubusercontent.com/16938405/49386229-0c736e00-f717-11e8-8faa-7be6c8dc6fe6.png)


it works for both add and subtract points to all teams

**Comment by jeffg2k** [comment]
Since we now have the option to easily add points to all teams or to a select team / player, I'm going to close this one.  I'm not sure it makes sense to build an administrative page for managing timed bonus points when the admin could just set a timer on their phone or add points whenever they feel like it.
