### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#215]
hello did the backup and restore work also "game object" button?

**Comment by jeffg2k** [comment]
@mohammadHmedat I'm not sure I understand this question.  We did have a bug #217 in the backup, so maybe this issue has been resolved.

**Comment by jeffg2k** [comment]
Fixed another bug with importing https://github.com/moloch--/RootTheBox/commit/d1114e48d2dba39fe04772161f7b368c50271ab7

**Comment by mohammadHmedat** [comment]
Hello all and thanks for the tag;
Could you test to submit an empty flag?
Is still redirect to 404?

**Comment by jeffg2k** [comment]
Fixed the empty flag - thanks
