### ISSUE TITLE
Timing attack

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#216]
Might be possible to do a timing attack on the PublicHandler.py LoginHandler() as it doesn't do a PBKDF2 hash on a failed username.  Something to look at...

**Comment by moloch--** [comment]
Usernames are public, I don't think there's much risk

**Comment by jeffg2k** [comment]
Probably should have checked that..  I had to temporarily nuke my dev vm for disk space.  If that's the case, we should probably add an option to make the scoreboard visible only to authenticated users.
