### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by Xlaits** [moloch--/RootTheBox#218]
Using localhost/127.0.0.1, memcached running, I cannot login as admin at all.

**Comment by jeffg2k** [comment]
What does it say when you try to log in?  Keep in mind this is not the sql password - it's the username and password you set during setup.  Might want to set Debug to True to see if there is anything else going on.

**Comment by Xlaits** [comment]
It says incorrect username/password. I am using the correct user/pass combo
for the admin setup.

**Comment by jeffg2k** [comment]
I'm not aware of any code issues with authentication.  I'd suggest a database query.
```
mysql -u mysqluser -p
show databases;
use rootthebox; --use rtb_dbname
select _name, password from user where id=1;
```
Verify the username is what you expect.

If the username is what you expect, then you can set the password to "password123456".

```
UPDATE `rootthebox`.`user` SET `password`='$p5k2$2bad$4bp39m81$Cg/lKc6hFnrX33b/4v2MgCuAr34fjhXo' WHERE `id`='1';
```

**Comment by Xlaits** [comment]
Just installed it on a VirtualMachine. _name shows up as NULL, as it does
on the other server in question. The name entered was 'admin'.

**Comment by jeffg2k** [comment]
Interesting... wonder if it's a difference between PyMySQL and mysql-python.  I'll work through this tomorrow and get it strait.  Thanks

**Comment by jeffg2k** [comment]
Sorry, the correct field is _handle, not _name.  _name should be null.

Just so I can follow you process, did you do --setup=dev or --setup=prod

**Comment by jeffg2k** [comment]
I spent the morning going through this setup several times and could not reproduce this issue.  I added a little more error handling, but didn't see anything that would cause your issue.
Try to run this select and make sure the _handle is the name you expect.  If so, then try to replace the password with the above password.

`select _handle, password from user where id=1;`

This should help us identify if it was a problem with the username, problem with the password, or a problem comparing the username or password.  

The Python code that does the username / password check is in "handlers/PublicHandlers.py" under the class LoginHandler.  So you may be able to put in some manual print statements to see where things are going wrong.

**Comment by Xlaits** [comment]
I was able to log into the admin account in my virtual environment, however my original server was bricked and I had to do a reinstall. Since my setup is incomplete, I cannot test it there. I'm preemptively saying I succeeded, but I am leaving this open in case there are the same issues with the new install.

**Comment by jeffg2k** [comment]
One way to start over would be to delete the rootthebox database from mysql and start the install again at this point: https://github.com/moloch--/RootTheBox/wiki/Installation#database-setup

**Comment by jeffg2k** [comment]
Alternatively, create a new database "rootthebox2" and update your rootthebox.cfg to point to it.

**Comment by Xlaits** [comment]
Alright, after a full reinstall, I can now log in.

**Comment by jeffg2k** [comment]
I know this is an old post, but for anyone searching, there is a recovery console that makes this easier.

The recovery console is run via `./rootthebox.py --recovery=True`  To list the accounts, run `ls` and then run `chpass admin_handle`.
