### ISSUE TITLE
Unable to Register, due to email issues.

### ISSUE THREAD

**Issue by Xlaits** [moloch--/RootTheBox#219]
![image](https://user-images.githubusercontent.com/32484365/53135703-42700380-354a-11e9-9de5-3828e0603506.png)

Is there any way to make emails optional?

**Comment by jeffg2k** [comment]
Option Added 👍 https://github.com/moloch--/RootTheBox/commit/8a9c2b9d716a8dd0f75c3a8b4db55ba477d886ac
Update from the repo and add this to the rootthebox.cfg
require_email = False
