### ISSUE TITLE
Scoreboard/stats for admin only?

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#222]
Enhancement request - it would be great if after disabling the scoreboard globally for players, that it could still be visible for the admin only.

**Comment by jeffg2k** [comment]
Yeah, can do.  I could see where you may want to hide the scoreboard from the players so it's not a competitive game (training situation), but still allow the instructor to see how well they're doing and what the statistics are on the game.

I think we'll put this in the GUI as well - make it a drop down where you have the scoreboard visibility options for: Public, Players, Admins.

**Comment by jeffg2k** [comment]
Added the options for the Scoreboard Visibility, which is in the GUI Configuration.  Note that this change removes prior configuration options with regard to hide_scoreboard & public_scoreboard as these two configurations were replaced with the single scoreboard_visibility.  It defaults to Public.
