### ISSUE TITLE
Seperate SQL and Logs each to different file

### ISSUE THREAD

**Issue by barakat-abweh** [moloch--/RootTheBox#224]
When trying to run the logging service we used the commands in your description

Debugging

If you run into problems and need to debug here are some useful commands to help, be warned running the application in debug mode will disable certain security features

    Start the application in debug mode: rootthebox.py --start --debug
    Increase the verbosity of the logs: rootthebox.py --start --logging=debug
    All of the above: rootthebox.py --start --debug --logging=debug
    All of the above and log SQL queries:

rootthebox.py --start --debug --logging=debug --log_sql

    Write the logs to a file:

rootthebox.py --start --logging=debug --log_file_prefix=./files/rtb.log

is it possible to put each type of logs in a seperate file?

**Comment by jeffg2k** [comment]
Python’s standard logging module is used to implement informational and debug log output with SQLAlchemy, but it looks like you can define a file handler.  I'm not sure if that will direct all logging or just the sql alchemy, but you can give it a try.

The logging for sql is defined in models/__init__.py
If you're in the master branch, then at line 35 of that file, you should be able to add this before the 
```
handler = logging.FileHandler('sql.log')
logging.getLogger('sqlalchemy').addHandler(handler)
```

**Comment by mohammadHmedat** [comment]
Thank you @jeffg2k  @barakat-abweh 

We try the edit its worked fine but with the following order:

handler = logging.FileHandler('./files/sql.log')
**handler**.setLevel(logging.INFO)
sql_logger = logging.getLogger('sqlalchemy').addHandler(handler)
