### ISSUE TITLE
Game.py   __main__.py  403 

### ISSUE THREAD

**Issue by Arwaalkatheeri** [moloch--/RootTheBox#226]
I have 2 issues : 
1- cannot find these files 
- `__main__.py` directory : RootTheBox
- `game.py` in the directory : RootTheBox/files
Can someone tell me why ??
And is it related to the second issue ?? 

2- if i try to access admin features, to create anything in the admin interface ill get 403 forbidden error...it tried  to add my IP to the whitelisted IP but didn’t work !? 

Any solution

**Comment by moloch--** [comment]
Please refer to the wiki for setup instructions: https://github.com/moloch--/RootTheBox/wiki

**Comment by jeffg2k** [comment]
1.  RTB doesn't have a `game.py` or `main.py` file, so you shouldn't see them in RootTheBox or RootTheBox/files.  
1.  Should only require two things: a) Admin account  b) IP in `admin_ips =` `RootTheBox/files/rootthebox.cfg` or use `admin_ips = []` to allow all IPs.

**Comment by Arwaalkatheeri** [comment]
I was going to do that but after seeing a video in youtube i got confused.
 
amazing thank u 👍🏻

**Comment by jeffg2k** [comment]
@Arwaalkatheeri I'm going to close this.  Let us know if you have any additional issues.
