### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#228]
Hi I followed the wiki to install Root the box now It stops at this point raising exception 
```shell
dev@dev-VirtualBox:~/Desktop/RootTheBox$ ./rootthebox.py --save
Traceback (most recent call last):
  File "./rootthebox.py", line 32, in <module>
    from tornado.options import define, options
  File "/home/dev/.local/lib/python2.7/site-packages/tornado/options.py", line 127
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax
dev@dev-VirtualBox:~/Desktop/RootTheBox$ ./rootthebox.py --version
Traceback (most recent call last):
  File "./rootthebox.py", line 32, in <module>
    from tornado.options import define, options
  File "/home/dev/.local/lib/python2.7/site-packages/tornado/options.py", line 127
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax
```

**Comment by jeffg2k** [comment]
Thank you for the report.  Tornado web server released version 6 this month and dropped compatibility with Python 2.7.x.  We'll update the requirements file for Python2.  To fix it, you have two options:

Downgrade your Tornado from 6.0.2 to 5.1.1
`pip2 install tornado==5.1.1`

Change to the RTB Python3 branch (beta - supports Python2 & 3)
`git checkout Python3`

Or, you could do both and if you have any issues with the Python3 branch, let us know.  But you can always drop back to the Python2 branch by running 'git checkout master'.  We keep the branches in-sync functionality wise so you shouldn't lose or gain any features.  We'd like to switch the master to the Python3 branch, but it just requires more testers to work out any remaining kinks.  So, it may depend on how close you are to game time.  If you have time to build the CTF and play with it before big day, then I'd try to use the Python3 branch as it helps us find anything wrong, but if you're wanting something that shouldn't give you any surprises when flags are flying, then I'd use the master branch.

**Comment by jeffg2k** [comment]
As an additional FYI, I forgot to backport utfmb8 MySql connection to Python2 this week when I updated the Wiki during the Python3 changes.  I just pushed an update if you defined your character set as utfmb8.  `git pull`

**Comment by mxamusic** [comment]
Thank you so much for such quick response <3 

Now I have something else i managed to run the application. created the admin but i cant login as admin 
it says bad username / password 

![image](https://user-images.githubusercontent.com/16447622/55680266-90896c80-5928-11e9-93f2-8848059a355f.png)

```
# [ Server ]
origin = "ws://localhost:8888"
admin_ips = ['127.0.0.1', '::1']
certfile = ""
listen_port = 8888
x_headers = False
ssl = False
session_age = 3600
listen_interface = "0.0.0.0"
keyfile = ""
```
or the admin interface has different port ?

**Comment by mxamusic** [comment]
also is there a way to reset admin password ?

**Comment by mxamusic** [comment]
i tried to play with recovery.py 
```
dev@dev-VirtualBox:~/Desktop/RootTheBox$ ./setup/recovery.py 
Traceback (most recent call last):
  File "./setup/recovery.py", line 30, in <module>
    from libs.ConsoleColors import *
ImportError: No module named libs.ConsoleColors
```

**Comment by jeffg2k** [comment]
The recovery console is run via `./rootthebox.py --recovery=True`  That would be the easiest way to reset the password.  I'll add that info to the wiki and also add an option to list the users, but you could verify the admin username via the database.

```
mysql -u mysqluser -p
show databases;
use rootthebox; --use rtb_dbname
select _handle, password from user where id=1;
```

Alternatively, you could update the database more directly to "password123456".

```
UPDATE `rootthebox`.`user` SET `password`='$p5k2$2bad$4bp39m81$Cg/lKc6hFnrX33b/4v2MgCuAr34fjhXo' WHERE `id`='1';
```

**Comment by mxamusic** [comment]
hey @jeffg2k 
Is there a way I can attach files to the box like hints or even extended to become Jeopardy style ctf with attack and defense

**Comment by jeffg2k** [comment]
If the option "use_box_materials_dir" is set to true, a Game Materials folder named identical to a box will auto-link in the description.  Also, the description fields for Boxes, Flags, and Hints support Markdown, so you could link a file or picture using that.  You could place your files somewhere under static (obscurity) and reveal them in the flag or hint description, as flags can unlock other flags.  Could also use Story Mode to describe the location of the file after a flag is complete (working on adding stories for when a Box is complete).

**Comment by mxamusic** [comment]
i cant find this in the config tab or i have to edit something in the config files

**Comment by jeffg2k** [comment]
Yeah, that one is not in the GUI.  You'll have to edit the `rootthebox.cfg`  More info on configuration options are described in the Wiki [Configuration File Details](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details).

**Comment by mxamusic** [comment]
hi @jeffg2k 

can you help me with this error. I have created fresh Debain Box to host RTB and I have had this error 
![image](https://user-images.githubusercontent.com/16447622/55874491-92ab2f80-5ba3-11e9-95a7-8d66a3aa5f9f.png)

**Comment by jeffg2k** [comment]
Take a look at the prerequisites on this page for python-dev.  I think that may be the issue.  https://pypi.org/project/mysqlclient/1.4.2/

**Comment by jeffg2k** [comment]
@mxamusic just wanted to follow up and see if that link helped resolve your issue.  I was on mobile at the time so couldn't give a more detailed response.  If you're up and running, then I'll go ahead and close the issue.

**Comment by mxamusic** [comment]
I haven't had time to check it out honestly but i moved it to Ubuntu Container for a quick fix. you can close this ticket @jeffg2k 

Thanks a lot buddy :D

**Comment by jeffg2k** [comment]
Looks like in 2018, Debian/Ubuntu moved from libmysqlclient-dev to default-libmysqlclient-dev.  Maybe Ubuntu still maintains the older one or redirects.  I expect that we need to change to default-libmysqlclient-dev in the build package.
