### ISSUE TITLE
Feature Requests: Self service - Password reset

### ISSUE THREAD

**Issue by lgpaulsen** [moloch--/RootTheBox#232]
People lose passwords all the time, and special in a ctf scenarios, they often use some random password when the registered. If they have used their correct email, a password reset feature would be great. The manual way of editing the user as admin works, but self service would be better.

**Comment by jeffg2k** [comment]
Would be funny to deduct points / money for a password reset. :)

**Comment by mohammadHmedat** [comment]
Looks nice

**Comment by alahammad** [comment]
Maybe this could help : 
 using fastmail, or other free service for example :

https://alexwlchan.net/2016/05/python-smtplib-and-fastmail/

**Comment by jeffg2k** [comment]
I've added this feature to RootTheBox, so please give it a try and let me know if you have any issues.
