### ISSUE TITLE
User Registration Fails

### ISSUE THREAD

**Issue by nishils** [moloch--/RootTheBox#234]
I think this commit 6ac8dd61eec22de3158a3eaf97ec34f364d9ddff causes an issue when users are trying to register for a game especially given the error code thrown, "Invalid team code". You'll notice that the commit changes the logic directly around this error.

I was working with head of master and ran into the issue but reverted before this commit and ran into no issues.

**Comment by jeffg2k** [comment]
Yup, I fkd that one up. haha  Thanks, pushed a fix.
