### ISSUE TITLE
Link Game Material to box

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#236]
Hey 

I have created the setup as per the wiki with ```use_box_materials_dir = True```
now I have folder structure one per corp and inside the file called "Rotate" just like the box name with no extensions but for some reasons, it's not linking or does the file name has to be like "Corp Name - File Name" or is there naming convention

**Comment by mxamusic** [comment]
![image](https://user-images.githubusercontent.com/16447622/56838730-337e3800-6890-11e9-9218-769d21933501.png)
![image](https://user-images.githubusercontent.com/16447622/56838733-38db8280-6890-11e9-9466-15a8cdd8480f.png)
Screen shots attached for helping :D

**Comment by jeffg2k** [comment]
I'll double check, but I think it's looking for a folder name Rotate, not a file.  So if you had a folder named Rotate and then a file inside of it, I think it would link.

**Comment by mxamusic** [comment]
so it checks the root folder has to be with the box name so in my case folder name has to be "Rotate" but when I do it "Secure Tech"/Rotate it's not linking anymore. that's fine for me for now but is there a way we can do it per corp name to separate scenarios and multiple levels

**Comment by jeffg2k** [comment]
Pushed an update to allow corp/box linking.  As a note, if a folder with the box name exists at the root, it will link that first before corp/box.  The order is to first check for the box name, then the corp/box. 
 `git pull` should update you if you've cloned the branch.
