### ISSUE TITLE
New Version of Cyberchef

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#237]
Hey bro :D 

I keep coming back with stuff but there is a new release of Cyberchef version 8.31.1 since the built-in one is 5 months old how can I fetch the new version?
if I can do it manually I can script service to make sure that the current version is the one up to date but I am not sure where do I change it in RTB or if it's plug and play

**Comment by jeffg2k** [comment]
Not sure about auto-updating, but I can try to keep it more up to date.  I haven't done so recently as they changed the way they build it so it's not a single file any longer, which was one cool feature of it.  I need to rewrite the handler to allow access to the various subdirectories and assets, but I can easily update it to the latest that still had the single file, which was 8.30.  I'll see what can be done for updating though as I work on #235, maybe a submodule.
