### ISSUE TITLE
Question - open next level

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#242]
when I configure the level to open based on game progress (50%) of the previous level, on what it depends (score of overall or number of flags) ?

**Comment by jeffg2k** [comment]
It's based on the number of flags.
`len(user.team.level_flags(level.number)) /  float(len(level.flags))`

**Comment by mohammadHmedat** [comment]
sometimes the level not open, I submit 16 flags from 20 for level 1 and the configuration is "next level open based on game progress (50%)" but level 2 didn't open ?!

**Comment by jeffg2k** [comment]
So, here is the code for the level check.  Maybe we can figure out where it's going wrong in your case.
```
level_progress = len(user.team.level_flags(level.number)) /  float(len(level.flags))
next_level = GameLevel.by_id(level.next_level_id)
if next_level and next_level._type == "progress" and 
    level_progress * 100 >= next_level.buyout and 
    next_level not in user.team.game_levels: 
        #unlock
```

**Comment by jeffg2k** [comment]
I've tested this and haven't seen where the code is having an issue.  Perhaps you can modify your code slightly to report back what is occuring.

Place this code in your MissionHandler.py at line 61, below the user definition.  When you go to a Box page, it should print the various factors for the level unlock in your terminal.  
```
            level = GameLevel.by_id(box.game_level_id)
            level_progress = len(user.team.level_flags(level.number)) /  float(len(level.flags))
            next_level = GameLevel.by_id(level.next_level_id)
            print("Level Available: %s" % (next_level not in user.team.game_levels))
            print("Level Type: %s" % next_level._type)
            print("Level Progress: %d" % (level_progress * 100))
            print("Level Requirement: %d" % next_level.buyout)
            print("%d >= %d: %s" % ((level_progress * 100),next_level.buyout, level_progress * 100 >= next_level.buyout))
            if next_level and next_level._type == "progress" and level_progress * 100 >= next_level.buyout and next_level not in user.team.game_levels:
                print("%s (%s) unlocked %s" % (
                        user.handle, user.team.name, next_level.name
                    ))
```

The actual code for the level unlock is in the MissionHandler.py under the success_capture() function - the check begins at line 200.  If all indications look good with the testing code above, perhaps something is failing right above line 200.

**Comment by jeffg2k** [comment]
@mohammadHmedat I think I might have found the problem.. are you in story mode and have a capture message for your flags?  Appears this will currently bypass the success_capture() function which does the unlock.

**Comment by mohammadHmedat** [comment]
Yes I'm using story mode, that's make sense

**Comment by mohammadHmedat** [comment]
Excuse me but I didn't get the solution?

**Comment by jeffg2k** [comment]
I just pushed up a fix and it auto-closed the issue.  Note that the check happens when a flag is captured, so this won't unlock the level until you capture another flag.
