### ISSUE TITLE
Nginx Configuration

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#249]
Can you guys help me with setting the platform sitting behind Nginx. if there is some sock to be configured or server configuration sample to make it work. 

Cheers :D

**Comment by jeffg2k** [comment]
If you haven't looked at this yet, it can be helpful.
https://github.com/moloch--/RootTheBox/blob/master/setup/nginx.conf

I haven't done it myself, but have some familiarity with nginx forwarding.  Think you have to setup an unstream server, upstream, location, and http server.

**Comment by jeffg2k** [comment]
Would be great if you were able to write up some additional instructions.  We have this Wiki stub that could use some updates. https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx

**Comment by loi219** [comment]
I don't know if this issue is stil up but I've write up some additional instructions on how to reverse proxying the RTB Server: https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx/_edit

**Comment by mxamusic** [comment]
I have created dedicated lxc for each CTF by that time it was not stable to use Nginx so I guess its closed :D 
thanks a lot for help
