### ISSUE TITLE
Error on ./rootthebox.py --setup=prod

### ISSUE THREAD

**Issue by torrycrass** [moloch--/RootTheBox#250]
I wanted to log this here in case I don't get to troubleshoot this before someone else does.

**VPS:** Running OpenVZ
**System:** Ubuntu 16.04
**Kernel:** Linux rtb 2.6.32-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux
**Python Version:** Python 2.7.12

Previous installation (several months prior, sorry I don't have a more specific date) worked fine.

This is a 100% clean install with no customization at the OS level, just git followed by dependencies, database, and then the setup script.

**Error Message:**
```
#@rtb:~/RootTheBox$ ./rootthebox.py --setup=prod
[*] 09:03:55 : Creating the database ...
Traceback (most recent call last):
  File "./rootthebox.py", line 789, in <module>
    setup()
  File "./rootthebox.py", line 81, in setup
    from setup.create_database import create_tables, engine, metadata
  File "/home/pyrate/RootTheBox/setup/create_database.py", line 21, in <module>
    from models import engine
  File "/home/pyrate/RootTheBox/models/__init__.py", line 116, in <module>
    from models.Theme import Theme, ThemeFile
  File "/home/pyrate/RootTheBox/models/Theme.py", line 128
    return "cyborg.min.css"
SyntaxError: 'return' with argument inside generator
```

**Comment by jeffg2k** [comment]
Looks like this is caused by my last commit.  https://github.com/moloch--/RootTheBox/commit/4f2f3c3b55db53b0a12dac97434d17d5bb109ede To try and fix #248.  I think this is what might be causing the css issue.

**Comment by jeffg2k** [comment]
Might need to be a yield instead of return.

**Comment by torrycrass** [comment]
This resolved the problem as suspected. Latest code appears good. Closing issue.

Thank you! =)
