### ISSUE TITLE
Feature Request: Add translation for foreign language

### ISSUE THREAD

**Issue by gmorchio** [moloch--/RootTheBox#251]
I loved your platform, but I would like to have the option to translate it without losing everytime is updated. I can offer the spanish translation if this moves one.

Thanks!

**Comment by jeffg2k** [comment]
Great request - I'll see how best to do that.

**Comment by jeffg2k** [comment]
I've started playing with translation and have a working test on my dev box registration page.  It uses [tornado.locale](https://www.tornadoweb.org/en/stable/locale.html) using the load_translations with files of the form `LOCALE.csv`, e.g. `es_LA.csv`.  By default, it would use the browser's locale and offer the closest matching locale.

So a question... would you want an option to define the locale for the players, such that you could add locale_force="es_LA" for example to the rootthebox.cfg and have it override the player's browser setting?  Or do your users already have the browser locale defined and RTB just needs to try to use it?

**Comment by gmorchio** [comment]
Nice to read that! We are planning to do local CTF, so we know exactly were we are. So, it is better to force the language, and the browser will have to use that. 

Thanks!

**Comment by jeffg2k** [comment]
Not sure what you're timeline is for the CTF, but I pushed up a branch that has my current  changes for the Multi-language support if you wanted to test it.  I still have some admin pages to do, but all the user pages should be done.  I did a quick Google Translate for Spanish as a test.

**Comment by gmorchio** [comment]
Our timeline is at the end of August '19. So I have some time!. I'll push it today and test it.
Thanks!

**Comment by jeffg2k** [comment]
Pushed additional translation updates to the branch.  Use the option "force_locale" in the configuration file to specify a locale file under the locale directory.
