### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#252]
This is a placeholder for screenshots.  Issue will be immediately closed and is just used for wiki / readme linking.

<img width="1156" alt="Screen Shot 2019-06-29 at 10 14 41 AM" src="https://user-images.githubusercontent.com/161904/60768715-4fbf0200-a095-11e9-9989-b71993adca4b.png">
<img width="1151" alt="Screen Shot 2019-06-29 at 10 14 01 AM" src="https://user-images.githubusercontent.com/161904/60768716-551c4c80-a095-11e9-95ad-556bec8b3e98.png">

![57324170-5a7d0b00-70d5-11e9-9511-ab57d1521fc5](https://user-images.githubusercontent.com/161904/60768721-7a10bf80-a095-11e9-8f20-b835cc9fd066.png)

**Comment by mohammadHmedat** [comment]
is the features in screenshots available?

**Comment by jeffg2k** [comment]
All the features are available. The images for the infinity stones are not included in RTB (you can find them on Google and crop/size them 500x250) nor are the flag questions, but the rest is.
