### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#253]
[E 190711 15:11:17 rootthebox:52] Error: (MySQLdb._exceptions.OperationalError) (1091, "Can't DROP 'snapshot_to_snapshot_ibfk_1'; check that column/key exists")
    [SQL: ALTER TABLE snapshot_to_snapshot_team DROP FOREIGN KEY snapshot_to_snapshot_ibfk_1]
    (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by jeffg2k** [comment]
Fixed - thanks for the report.  I really need to figure out the auto-creation of Alembic.  During the db fail, it should have reverted the changes (non-commit), so you should be good to update and run again.

**Comment by mohammadHmedat** [comment]
Is this another issue?

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1412, 'Table definition has changed, please retry transaction')
[SQL: SELECT flag.id AS flag_id, flag.created AS flag_created, flag.uuid AS flag_uuid, flag.box_id AS flag_box_id, flag.lock_id AS flag_lock_id, flag._name AS flag__name, flag._token AS flag__token, flag._description AS flag__description, flag._capture_message AS flag__capture_message, flag._case_sensitive AS flag__case_sensitive, flag._value AS flag__value, flag._original_value AS flag__original_value, flag._order AS flag__order, flag._type AS flag__type
FROM flag, team_to_flag
WHERE %s = team_to_flag.team_id AND flag.id = team_to_flag.flag_id]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by jeffg2k** [comment]
Not sure what is causing that one.  When does it happen?  I'd guess that maybe the last attempt from your original error never rolled back and is pending a commit.  Maybe a db restart?

**Comment by mohammadHmedat** [comment]
Worked, Thanks
