### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#254]
The markdown editor has a couple qwirks in it that need to be fussed out.  When you highlight something, set it to code for example, then select something else and set it to code.  It tries to undo the first selection instead of applying it to the second section.  So the cursor placement is not being verified properly - an undo vs do again.

**Comment by moloch--** [comment]
Be sure to check for bugs with [fuzz.md](https://gist.github.com/moloch--/fc9f3a7b2c924c1ef348f59c219850dc)
