### ISSUE TITLE
python3 setup env error

### ISSUE THREAD

**Issue by torrycrass** [moloch--/RootTheBox#258]
This issue applies to installations with Python3 installed and no installation of Python2.x. Specifically a clean Ubuntu 18.04 LTS installation with Python 3.6.8 installed.

Error:
```
./rootthebox.py --save
/usr/bin/env: ‘python’: No such file or directory
```

This appears to be caused by the environment not knowing how to access Python3.  

The Ubuntu wiki points out that (per: https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3)  

> For both Ubuntu and Debian, we have ongoing project goals to make Python 3 the default, preferred Python version in the distros.
> 
> What this does not mean:
> 
> /usr/bin/python will point to Python 3. No, this is not going to happen (unless PEP 394 advocates otherwise, which is doubtful for the foreseeable future). /usr/bin/python and /usr/bin/python2 will point to Python 2.7 and /usr/bin/python3 will point to the latest supported Python 3 version.  

**Workaround:** Create an symlink for /usr/bin/python3 to point to /usr/bin/python. 
**Likely Long Term Resolution:** Code update that if python3 is installed, the environment variables are set to use it.

**Comment by jeffg2k** [comment]
Hmmm, I'm not sure the best way to handle this.. another failure of Py2 / Py3.  We have 5 scripts that use the shebang for running without calling python first: 

- Bot.py
- BotMonitor.py
- build_bot.py
- rootthebox.py
- recovery.py

If we change it to `#!/usr/bin/env python3` as recommended for a Python3 app, it would have a similar effect for breaking those Python2 users with no Python3 install.  I'm not sure there is a good way to do Python2/3, which seems to be the python way of breaking things to fix them.  Let me know if you have any ideas. :)

We could try to put something in the depends.sh.  It does a check of `$python_version` in there and could offer to symlink if `/usr/bin/python` doesn't exist.

**Comment by torrycrass** [comment]
Yeah that's kind of what I was running into when I briefly poked at it.  

For now, the work-around of symlinking does solve the problem but not a great _solution_  

I'll poke at this some (perhaps this weekend) and see if I can come up with a good fix.

Thinking maybe:

1. Detect version of python
1. If version == 3, sed/awk/regex/etc. (whichever/combination works best) replace the env variables in the files

**Comment by jeffg2k** [comment]
A concern with dynamic modification of the user's RTB files is that it would cause a conflict for git pull, making it difficult for them to sync updates.
