### ISSUE TITLE
Backup is not working 

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#261]
Hi I hope that you are doing well :D 

I launched the ctf platform finally to public but i tried to take a backup it go the following error 

![image](https://user-images.githubusercontent.com/16447622/63230201-85b9df00-c21a-11e9-8f16-a3e1bccbf53b.png)
Knowing that I keep updating the Platform

**Comment by jeffg2k** [comment]
Thanks for the report - had a Python 2 issue when it tried to convert the images to base64.  Should be resolved with the latest update.
