### ISSUE TITLE
Enable Multi Language

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#265]
Hello :D 

I have just seen the new update with multi-language update is there a way to enable it or it relay on the browser to pick the language I checked the wiki but still nothing there yet

**Comment by jeffg2k** [comment]
By default, the application should use the browser's locale if a language file exists for that local in the `./locale` folder.  It makes a best effort.  If you want to force the application to use a certain language, you can use the configuration option `force_locale`.  The default language defined in RTB is "en_US" if the browser's locale is not defined or a language csv file doesn't match.

This setting, for example, would force the language to Spanish.

> force_locale="es_LA"

Thanks for the reminder about the Wiki.  I updated the [Configuration File Details](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details).
