### ISSUE TITLE
Enhacement: Enable / Disable boxes at will 

### ISSUE THREAD

**Issue by gmorchio** [moloch--/RootTheBox#266]
We have run our first CTF with latin american spanish language, it was a success!
During the event we realize thath we couldn't disable some boxes while we need to make updates or fixes. So, can this be a enhacement? For example the behaviour should be when the box is created, it is enabled by default, but if you need to disabled it, with the enable / disable button should work without any issues.

Thanks!

**Comment by jeffg2k** [comment]
Feature Added https://github.com/moloch--/RootTheBox/commit/f78dd565fa362a99fc1f52183d77a2e903ab521c

**Comment by gmorchio** [comment]
Nice! When it will commit to the master branch?
Regards

**Comment by jeffg2k** [comment]
It's already in the master branch.  Just haven't pushed a new release yet as I have a couple other things left for the milestone.
