### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#274]
Is there an ability to notify players that there is a new challenge has been added for example using Chrome Notifications even when they didn't open the platform and/or by email

**Comment by jeffg2k** [comment]
If you have the RocketChat server setup, global notifications will be sent to the CTF's channel.  So if they had a notification on the chat system, then it could alert them outside the game.  Of course, global notifications will also be sent via the in-game system.  It does not currently support Chrome Notifications or Email.

**Comment by jeffg2k** [comment]
Did you want to turn this into an enhancement request or should I close it?
