### ISSUE TITLE
Sorting Challenges

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#276]
Can we have a way to sort challenges by date added or difficulty, or category inside the company 

so it should look like this 
Company A 
 -> Challenge 1 Easy
-> Challenge 2 Medium
-> Challenge 3 Hard 

or 
Company A 
-> Web 
--> Challenge 1 , 2 ,3 
-> PWN 
--> Challenge 1 ,2 ,3

**Comment by jeffg2k** [comment]
I don't use Company myself.  I leave it empty so it is excluded.  You might be able to do what you want with just Boxes and Levels, removing the Company component from the structure and just using the description or images to indicate any additional factors.  

I'll have to recreate the company layout structure on my test system to see how it presents and how we might be able to better organize it.

**Comment by jeffg2k** [comment]
As a side thought, I've wondered if it would be better if we renamed Corporations -> Groups, and Boxes -> Sections.  As the software broadend from offensive use, more generic terms might be better, but didn't want to mess with Moloch's original styling.

**Comment by jeffg2k** [comment]
Feature Added https://github.com/moloch--/RootTheBox/commit/173b9c1d2f72560e0bf24807387a76b638fd733f - enabled in the rootthebox.cfg via Game option:
`group_by_corp = True`
