### ISSUE TITLE
Startup issues, str/int issue on options.listen_port

### ISSUE THREAD

**Issue by lgpaulsen** [moloch--/RootTheBox#281]
A clean install, with latest version. and running --setup=prod, and --start (with defaults).
The application fails with 
Traceback (most recent call last):
  File "./rootthebox.py", line 813, in <module>
    start()
  File "./rootthebox.py", line 65, in start
    listenport = "port " + options.listen_port
TypeError: can only concatenate str (not "int") to str

A quck fix would be to just force options.listen_port to a string. 
Rootthebox.py: Line 65
        listenport = "port " + str(options.listen_port)

But uncertain if this brake something else, somewhere else.

**Comment by jeffg2k** [comment]
Thanks for the report and sorry for introducing the bug.  Fixed
