### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#287]
Hello, 

I was running a CTF today and I wanted to share the log file with some problems is there a way we can get in contact? Its a big log file with some info that I would rather not share publicly.

**Comment by jeffg2k** [comment]
You could hit me up on Discord ElJeffe#1601 or I did create this [forum on Gitter](https://gitter.im/RootTheBox/community).

**Comment by jeffg2k** [comment]
You could also create a private repo - upload your log, and then invite me to your repo.

**Comment by CovertError** [comment]
Apparently the log life is like 10M I will go through it and post the issues to save you guys the time of going through it.
