### ISSUE TITLE
Delete Corp 

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#295]
Hey :D 

I was trying to delete a Corp after CTF is over and it crashed the platform completely 
![image](https://user-images.githubusercontent.com/16447622/67206034-ef748600-f421-11e9-9fcc-5ea64b7debed.png)

and if there is a way to disable some boxes other than deleting them

**Comment by mxamusic** [comment]
on top of that even deleting a box caused the same error 
```shell
root@hwsrv-545543:~# systemctl status rtb.service
● rtb.service - Root The Box Platform
   Loaded: loaded (/etc/systemd/system/rtb.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2019-10-21 12:48:38 UTC; 6s ago
  Process: 8404 ExecStart=/usr/bin/python /root/RootTheBox/rootthebox.py --start (code=killed, signal=KILL)
 Main PID: 8404 (code=killed, signal=KILL)

Oct 21 12:47:43 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:43 web:2162] 302 POST /login (94.200.228.50) 1203.65ms
Oct 21 12:47:43 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:43 web:2162] 200 GET /user (94.200.228.50) 100.28ms
Oct 21 12:47:44 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:44 web:2162] 304 GET /scoreboard/ajax/timer (94.200.228.50) 1.07ms
Oct 21 12:47:45 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:45 web:2162] 304 GET /admin/gitstatus (94.200.228.50) 856.30ms
Oct 21 12:47:45 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:45 web:2162] 101 GET /connect/notifications/updates (94.200.228.50) 1.80ms
Oct 21 12:47:55 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:55 web:2162] 200 GET /admin/view/game_objects (94.200.228.50) 222.45ms
Oct 21 12:47:56 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:47:56 web:2162] 101 GET /connect/notifications/updates (94.200.228.50) 1.20ms
Oct 21 12:48:06 hwsrv-545543.hostwindsdns.com python[8404]: [I 191021 12:48:06 AdminGameObjectHandlers:888] Delete box: Getting Started
Oct 21 12:48:38 hwsrv-545543.hostwindsdns.com systemd[1]: rtb.service: Main process exited, code=killed, status=9/KILL
Oct 21 12:48:38 hwsrv-545543.hostwindsdns.com systemd[1]: rtb.service: Failed with result 'signal'.
```

**Comment by jeffg2k** [comment]
I'm not able to reproduce this.  Looks like it had a problem deleting one of the boxes under the corp.

**Comment by jeffg2k** [comment]
You could transfer boxes you want to keep to another corp.  Often I'll create a corp with no name and place my boxes there.  If the corp has no name, it will not display the corp to players.

**Comment by mxamusic** [comment]
So My Environment has 
2 Corp  each has different boxes so I tried to delete entire corp it failed and delete a box inside a corp still failed so is there any logs I can extract and share with you

**Comment by jeffg2k** [comment]
Can't recall where the logging goes if it's set (maybe /var/log), but a quick way would be to stop the service and run rootthebox.py directly with the --debug option.  It should spit out on the console what the error is about, even if it's a sql problem.

**Comment by jeffg2k** [comment]
I tried this again with another data set using both python 2 and python 3 and wasn't able to see the error.

**Comment by jeffg2k** [comment]
I found some issues when deleting a box that had "source code" attached https://github.com/moloch--/RootTheBox/commit/99ce3350c259d36135299e2abf0fe528c462f127.  Also tweaked a couple other tables to cascade on delete.  Not sure if this fixes your issue, but worth testing with the latest codebase.

**Comment by mxamusic** [comment]
Sure I will test it out and keep you posted

Cheers
Mina

________________________________
