### ISSUE TITLE
Game reset

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#297]
when trying to reset a game I keep getting ERROR Failed to Reset Game

**Comment by CovertError** [comment]
this is the only thing I see in the log 
Oct 26 23:45:55 rtb-Droplet python3.6[11473]: [I 191026 23:45:55 web:2246] 200 GET /admin/reset (83.110.104.92) 20.58ms
Oct 26 23:45:56 rtb-Droplet python3.6[11473]: [I 191026 23:45:56 web:2246] 101 GET /connect/notifications/updates (83.110.104.92) 0.87ms
Oct 26 23:45:57 rtb-Droplet python3.6[11473]: [E 191026 23:45:57 AdminGameHandlers:629] unhashable type: 'MarketItem'
Oct 26 23:45:57 rtb-Droplet python3.6[11473]: [I 191026 23:45:57 web:2246] 200 POST /admin/reset (83.110.104.92) 102.47ms
Oct 26 23:45:58 rtb-Droplet python3.6[11473]: [I 191026 23:45:58 web:2246] 101 GET /connect/notifications/updates (83.110.104.92) 1.40ms

**Comment by jeffg2k** [comment]
You could probably get a stack trace by removing the try / except in the AdminGameHandler.py AdminResetHandler class.  The only line that I think deals with the MarketItem is `team.items = []`.  Not sure why that would cause an unhashable type error though - hmm.

Can you try this - Add it to the bottom of the models/MarketItem.py

```
    def __hash__(self):
        return hash(self.name)
```
