### ISSUE TITLE
docker-compose: /opt/rtb/setup/depends.sh: not found

### ISSUE THREAD

**Issue by bkimminich** [moloch--/RootTheBox#303]
```
$ docker-compose -f docker-compose.yml up
Pulling memcache (memcached:latest)...
latest: Pulling from library/memcached
Digest: sha256:3e59b871aaf8017c5643eccfbada3a0633fc6c600617918385c8749126a900d9
Status: Downloaded newer image for memcached:latest
Building rtb
Step 1/6 : FROM python:3.6
3.6: Pulling from library/python
Digest: sha256:869b4f8db6c46eadf5e25ccefc53690978e822c27a5f5aed777549e8f8b8f11f
Status: Downloaded newer image for python:3.6
 ---> 601c1195acd5
Step 2/6 : RUN mkdir /opt/rtb
 ---> Running in b875eb4f01ba
Removing intermediate container b875eb4f01ba
 ---> 6ea74a9b9d1d
Step 3/6 : ADD . /opt/rtb
 ---> 68925ddc75e1
Step 4/6 : RUN /opt/rtb/setup/depends.sh -y
 ---> Running in 5bcd9566885e
/bin/sh: 1: /opt/rtb/setup/depends.sh: not found
Service 'rtb' failed to build: The command '/bin/sh -c /opt/rtb/setup/depends.sh -y' returned a non-zero code: 127
```

Happened on Windows 10 with latest native Docker Desktop installed.

**Comment by jeffg2k** [comment]
Thanks for the report.  I added the docker recently and apparently, untested on Windows. 😳
Moloch [mentioned](https://github.com/moloch--/RootTheBox/issues/263) moving the contents of depends.sh into docker itself.  Will make that happen, particularly with GitHub's new Packages option.

**Comment by bkimminich** [comment]
I've forked your repo and played with the `Dockerfile` a bit. As building on Windows is not fun, I created https://hub.docker.com/repository/docker/bkimminich/rtb as an auto-build image from my fork at https://github.com/bkimminich/RootTheBox. If I get it working, I'll send a PR just without the `docker-compose.yml` change to retrieve my auto-built image. But that's actually quite convenient, as it speeds up things for the users who just want to run the latest version of your software, so maybe you want to introduce your own auto-build.

I'll delete my DockerHub image after I'm done testing (or gave up) so there'll be no confusion for users.

**Comment by jeffg2k** [comment]
Pushed up some changes - hopefully that will fix it.  It was successful on my Windows tests.

As a side note, I'll be pushing JuiceShop changes into the [v3.3 branch](https://github.com/moloch--/RootTheBox/tree/v3.3) until i'm ready to merge that release.

**Comment by bkimminich** [comment]
Ok, cool! My fork is set up to work on my machine, I'll drop it when I played with RTB a bit and tested your juice-shop-ctf generator.

**Comment by jeffg2k** [comment]
@moloch-- while resolving memcache 127.0.0.1 issues on the docker instance.  I noticed that we're not using the setting for memcached_port from what I can tell.  The setting is also defaulted to a non-standard port (11011) for memcache - should be 11211.  Since we're not using the config option, I expect it is using 11211.  Wasn't sure if there was a plan to change the port?  I figured we could remove the option, but thought I'd ask.  

On a positive note, I think I have the docker instance working well on all platforms based on my quick tests.

**Comment by bkimminich** [comment]
`docker-compose` now works like a charm on my Windows 10 machine except for the launch step, where it fails to create the volume:

```
Successfully built 5cbaef9ec5bd
Successfully tagged rootthebox_rtb:latest
Image for service rtb was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating rootthebox_memcache_1 ... done
Creating rootthebox_rtb_1      ... error

ERROR: for rootthebox_rtb_1  Cannot create container for service rtb: b'Drive has not been shared'

ERROR: for rtb  Cannot create container for service rtb: b'Drive has not been shared'
Encountered errors while bringing up the project.
```

I can change the volume to a static folder on my machine, though and it will work:
```
  volumes:
    - D:/temp/rtb:/opt/rtb/files:rw
```

Not sure if there might be a way to keep it compatible on both Win and Linux when using volumes...

**Comment by jeffg2k** [comment]
You have to go into Docker desktop app settings and share your drive with Docker.  Not sure if there is a way to get docker to prompt or something.

**Comment by jeffg2k** [comment]
Also, be sure to use the 3.3 branch for compatibility with JuiceShop export.

**Comment by bkimminich** [comment]
Done, works fine! 👍
