### ISSUE TITLE
支持CTFd-Whale 插件

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#309]
能不能添加支持docker instance例子
1.可允许用户创建属于自己的独立靶机。（解题时不像共享靶机一样受其他用户对题目操作的影响，体验更好）
2.可快速部署题目（题目镜像在 dockerhub 上有即可，可快速使用他人打包好的题目）
3.可在一台低配置机器上部署成百上千的题目（只要硬盘够大，因为题目是按需启动，不是同时运行的）

**Comment by jeffg2k** [comment]
Duplicate of #310
