### ISSUE TITLE
FR: need additional field for users

### ISSUE THREAD

**Issue by garanews** [moloch--/RootTheBox#315]
It would be nice to have an additional field under user setting that only admin can see.
We're thinking to implement it, what do you think?

**Comment by jeffg2k** [comment]
Guess I would need more information.. what type of information you looking to store?  I mean, what's the use case?

**Comment by garanews** [comment]
In my specific case I would add a sort of unique serial number (varchar) taken from an electronic device  distributed to all partecipants, so in this way I will be able to match and show on the small display of single partecipant user, team and a simplified dashboard :)

**Comment by dadokkio** [comment]
It could be useful, for example, to add information relative to each team that we need to provide during the game like different url (thinking about aws, or download link) or passwords.

**Comment by jeffg2k** [comment]
Just to clarify this request, should the field apply to the Team or the Player.  Keep in mind that when in Player Mode, the player is a Team of 1.  But if you're playing in Team mode and applied the field to the team, then it would be one note area for multiple users.

**Comment by jeffg2k** [comment]
Feature Added - Admin Notes added for both User and Team. https://github.com/moloch--/RootTheBox/commit/173b9c1d2f72560e0bf24807387a76b638fd733f
