### ISSUE TITLE
 docker-compose up fails

### ISSUE THREAD

**Issue by jeremytourville** [moloch--/RootTheBox#317]
[root@localhost RootTheBox]# docker-compose up
Starting rootthebox_memcache_1 ... done
Starting rootthebox_rtb_1      ... done
Attaching to rootthebox_memcache_1, rootthebox_rtb_1
rtb_1       | [*] Switching CWD to '/opt/rtb'
rtb_1       | [I 191204 22:31:52 rootthebox:825] Running Docker Setup
rtb_1       | [I 191204 22:31:52 ConfigHelpers:15] Saving current config to: files/rootthebox.cfg
rtb_1       | Traceback (most recent call last):
rtb_1       |   File "/opt/rtb/rootthebox.py", line 828, in <module>
rtb_1       |     save_config()
rtb_1       |   File "/opt/rtb/libs/ConfigHelpers.py", line 16, in save_config
rtb_1       |     with open(options.config, "w") as fp:
rtb_1       | PermissionError: [Errno 13] Permission denied: 'files/rootthebox.cfg'
rootthebox_rtb_1 exited with code 1

**Comment by jeffg2k** [comment]
Odd.. You have SELinux enabled? Try to modify the `docker-compose.yml` volume with the `:z` or `:Z` ending. `./files:/opt/rtb/files:z` or `./files:/opt/rtb/files:Z` The z and Z volume flags are options for modifying selinux labels.   https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container---volumes-from

**Comment by jeremytourville** [comment]
Ah, I should have thought of that.  Yes, it is a SELinux issue.  I set it to permissive to see if it would run, and it does.  I'll work on your suggestions and SELinux context later but at least the quick test worked correctly.
