### ISSUE TITLE
Admin Username/PW when using Docker Container

### ISSUE THREAD

**Issue by jeremytourville** [moloch--/RootTheBox#318]
I built the scoreboard in the past using a full vm with Ubuntu.  According to my notes you can set the UN/PW when you setup the database and run  `./rootthebox.py`` --setup=prod`

This time I chose to try the Docker container.  If I run the same command I get the following:
`[root@docker RootTheBox]# ./rootthebox.py --setup=prod`
`Traceback (most recent call last):`
 ` File "./rootthebox.py", line 29, in <module>`
   ` import nose`
`ModuleNotFoundError: No module named 'nose'`

If I run `pip install nose`  the install completes sucessfully so shouldn't the module be found?

Is the procedure different for a Docker install or is something wrong?

**Comment by jeffg2k** [comment]
They are slightly different as the Docker uses the Dockerfile for setup, where the direct install uses the depends.sh, however, they both install python requirements via the requirements.txt, which has nose listed in it.

The Dockerfile has `RUN pip install --no-cache-dir -r requirements.txt --upgrade`

How RootTheBox runs the --setup after those pre-setup requirements are met though is different.  The three options for --setup are (`prod|devel|docker`), but that's more of an initial setup.  The docker setup does set a default un/pw.  Running prod should work afterward, but I haven't tested this scenario.  I've always used the web interface after the setup.

One way from the command line to change the password, create new accounts, etc would be to use the `--recovery` option.

**Comment by jeremytourville** [comment]
What is the default UN/PW for the Docker version?  That was my question, not the mechanics behind it.  (Sorry, I guess I wasn't clear enough :)  ) 

BTW, the error is still the same if I try `--recovery`

**Comment by jeremytourville** [comment]
Disregard, I found the default UN/PW in the rootthebox.py file

**Comment by jeffg2k** [comment]
For anyone else searching, the docker default uses:
Login: `admin` Password: `rootthebox`

It's listed in the [Docker Setup](https://github.com/moloch--/RootTheBox/wiki/Docker-Deployment)
