### ISSUE TITLE
waf firewall

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#321]
waf Firewall reverse proxy, scoreboard could not be refreshed, guessing it was a websocket problem

**Comment by jeffg2k** [comment]
Make sure to set `x_headers = True`

**Comment by cohux** [comment]
`# [ Server ]
origin = "ws://0.0.0.0:8090"
listen_port = 80
listen_interface = "0.0.0.0"
session_age = 3600
x_headers = True
ssl = False
certfile = ""
keyfile = ""
admin_ips = []
`

**Comment by cohux** [comment]
With the above configuration, the scoreboard still cannot get data

**Comment by jeffg2k** [comment]
Most likely your origin.  Try using the Proxy IP or FQDN.  There's a rather strict check that occurs to prevent cross-origin websocket requests.  If the server's origin isn't configured properly the websockets may fail to connect.

**Comment by jeffg2k** [comment]
@cohux, if you're still having issues, @loi219 recently made some corrections and instructions for proxy (nginx) setup.  https://github.com/moloch--/RootTheBox/issues/325 

https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx
