### ISSUE TITLE
Error 400 on /connect/notifications/updates

### ISSUE THREAD

**Issue by loi219** [moloch--/RootTheBox#325]
I've got an error about Websocket with the URL /connect/notifications/updates  with Chrome and Firefox:
`
WebSocket connection to 'wss://rtb.test/connect/notifications/updates' failed: Error during WebSocket handshake: Unexpected response code: 400`

On the server the only error is `Jan 06 18:06:58 ctfs rootthebox.py[83656]: [W 200106 18:06:58 web:2246] 400 GET /connect/notifications/updates (127.0.0.1) 1.39ms`

Versions:

- Root the Box v3.3.4
-  SQL Alchemy v1.3.11
-  Torando v6.0.3

**Comment by jeffg2k** [comment]
Are you using a proxy, waf, forwarder or anything?  Might be the Server origin specified in the config.

**Comment by loi219** [comment]
Thanks for your quick answer.
I'm using the reverse proxy with nginx and I specified the `origin` in the configuration file of rootthebox with the DNS Name of the server but it's still not working

**Comment by jeffg2k** [comment]
I expect that's the problem, unfortunately, my experience with setting up the nginx reverse proxy is limited.  `x_headers = True` is required and there is an example in setup.   A tutorial was started but never finished.  https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx

If you get it figured out, please update the wiki if you can.

**Comment by jeffg2k** [comment]
The DNS name should be for the proxy I think, not the server, as the proxy is the "front end".

**Comment by loi219** [comment]
I think it's because I'm using a self-signed certificate.
I'm going to get a valid one and test it

**Comment by loi219** [comment]
The problem was coming from the nginx configuration I was using from the files directory of RTB.

The location was `location ^~ /notifications/wsocket` but the URL for the notification update is `location ^~ /connect/notifications`

I've juste add this lines:
```
# WebSocket: notification connections
location ^~ /connect/notifications {
   proxy_pass http://rtb_server;
   proxy_http_version 1.1;
   proxy_set_header Host $host;
   proxy_pass_header X-XSRF-TOKEN;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection $connection_upgrade;
}
```
