### ISSUE TITLE
Under certian conditions, I get a 404 error when I try to export the XML

### ISSUE THREAD

**Issue by mharrod** [moloch--/RootTheBox#326]
I am using the docker container

Under certain conditions, I get a 404 error when I try to export the XML.  This seems to only happen when I have a box added.  If i just have levels, corporations etc., then I can export and import just fine.  However, once I add the box, the export does not work.

Any ideas on how I might fix this.  I have attached a dump of the console that shows the error when I try to export.

[error.txt](https://github.com/moloch--/RootTheBox/files/4027211/error.txt)

**Comment by jeffg2k** [comment]
Pushed a fix to the git - not sure why this didn't work in Docker, but seemed to be a Python 2.x / 3.x issue regarding bytes vs str.  I was able to reproduce your issue and the pushed change that worked in my tests.
