### ISSUE TITLE
local varaible 'sockets' referenced before assignment. 

### ISSUE THREAD

**Issue by lgpaulsen** [moloch--/RootTheBox#327]
Doing maintenance upgrade, and after update, I tried running RTB. 
It fails with:
> Traceback (most recent call last):
>   File "/home/xxx/RootTheBox/rootthebox.py", line 851, in <module>
>     start()
>   File "/home/xxx/RootTheBox/rootthebox.py", line 70, in start
>     result = start_server()
>   File "/home/xxx/RootTheBox/handlers/__init__.py", line 304, in start_server
>     server.add_sockets(sockets)
> UnboundLocalError: local variable 'sockets' referenced before assignment

After tracking down, the issue, the problem is that the server fails silent when the socket can not bind. We know of error 13, if none-root user tries to bind socket. But every other error will fail silent. 

For known issues, error code  and possible fixes can be added to the logging.error().
But a catch-all might be usefull at then end. 

elif errno == xx for known issues 

> try:
>         sockets = netutil.bind_sockets(options.listen_port, options.listen_interface)
>     except (OSError, IOError) as err:
>         if err.errno == 13:
>             pypath = sys.executable
>             if os_path.islink(pypath):
>                 pypath = os_path.realpath(pypath)
>             logging.error("Problem binding to port %s", str(options.listen_port))
>             logging.error(
>                 "Possible Fix: sudo setcap CAP_NET_BIND_SERVICE=+eip %s", pypath
>             )
>             sys.exit()
>         elif err.errno == 98:
>             logging.error("Can't bind socket port. RTB running?")
>             sys.exit()
>         else:
>             logging.error(err)
>

**Comment by jeffg2k** [comment]
Thanks!
