### ISSUE TITLE
[Question] Scoreboard Sync time

### ISSUE THREAD

**Issue by noraj** [moloch--/RootTheBox#330]
What is the database sync time ?

Because 5 minutes after a player flag a box, if going in the admin panel it say the suer has 400 points, if going to player page it says 1 flag captured but if going to the scoreboard it says 0 flag 0 point.

![image](https://user-images.githubusercontent.com/16578570/72525380-4f819980-3864-11ea-968a-1b6e7d4aff6b.png)

Waiting some more minutes and the scoreboard displays the real score.

![image](https://user-images.githubusercontent.com/16578570/72525446-7a6bed80-3864-11ea-91ee-2cfdcc9061f5.png)

Refreshing the scoreboard and cleaning the cache with <kbd>CTRL</kbd> + <kbd>F5</kbd> won't help so it must be server-side.

Also this maybe another issue or just related to the sync time: after a flag point has been changed in admin panel let's say from 200 to 100, the points change is not reflected on the user score of people who flagged it. So either it's an issue or it's the sync time and we need to wait several minutes before it's reflected on the user score.

**Comment by jeffg2k** [comment]
It should be instant as it gets pushed to all clients when a flag is captured. I'll check if the admin panel issues a update.

**Comment by noraj** [comment]
I also see that removed players are still displayed on the scoreboard. It seems its only on the scoreboard because everywhere else their profile page is removed, etc.

**Comment by jeffg2k** [comment]
You seeing anything in debug?  Docker is weird.. I've seen odd issues on that that I don't see when installed directly.

**Comment by jeffg2k** [comment]
I've made a bunch of updates to get things in sync better, hopefully.  Just need to do some testing and I'll push the code.
