### ISSUE TITLE
Export XML 404 Error

### ISSUE THREAD

**Issue by jeremytourville** [moloch--/RootTheBox#333]
I am running a Docker container and performed a git clone on 1/22/2020.  No corporation is created yet, just a single test box and a flag.

404 - Glitch in the Matrix
It looks like you typed a URL incorrectly, or were attempting to find something you ought not have access to.
The only other possibility is that I messed up some of the code, and that doesn't seem very likely.

**Comment by jeffg2k** [comment]
@jeremytourville I've tried this multiple times rebuilding the docker from scratch each time and I'm not able to reproduce your error.  I did find a small issue, but not sure it would cause what you're seeing.  If you could, add `"--debug"` as an ENTRYPOINT array option in the `Dockerfile`.  This should allow you to see a stack trace in the console and hopefully give me an idea of what is causing it on your system.

**Comment by jeremytourville** [comment]
I did the `docker-compose build` and tested it without even trying the `--debug` parameter.  That fixed the issue.  Don't know why but, hey I'll take the win just the same.  Export works now!  :-)
