### ISSUE TITLE
rootthebox.cfg not found

### ISSUE THREAD

**Issue by dd121** [moloch--/RootTheBox#337]
With docker-compose up I get the following error:
[Errno 2] No such file or directory: 'files/rootthebox.cfg'

**Comment by dd121** [comment]
full error:

Attaching to rootthebox_memcache_1, rootthebox_rtb_1
rtb_1       | [*] Switching CWD to '/opt/rtb'
rtb_1       | Traceback (most recent call last):
rtb_1       |   File "/opt/rtb/rootthebox.py", line 831, in <module>
rtb_1       |     options.parse_config_file(options.config)
rtb_1       |   File "/usr/local/lib/python3.8/site-packages/tornado/options.py", line 398, in parse_config_file
rtb_1       |     with open(path, "rb") as f:
rtb_1       | FileNotFoundError: [Errno 2] No such file or directory: 'files/rootthebox.cfg'
rootthebox_rtb_1 exited with code 1

**Comment by dd121** [comment]
Oh... fixed it by manually creating an empty file with that name....

**Comment by dd121** [comment]
Now problems with logging in:

Information
Succesfull credentials, but administration is restriceted via IP. See 'admin_ips' in configuration.

**Comment by jeffg2k** [comment]
You shouldn't need to manually create that file, so that suggests some problem with your setup - perhaps permissions.  Windows has a shared volume thing and SELinux has certain issues as well.  By default, docker has an empty `admin_ips = []`, so no such restriction should be in place.  Again, this points to your setup / permissions - perhaps it was unable to write to the rootthebox.cfg.

**Comment by jeffg2k** [comment]
See this issue report - sounds like the same issue. https://github.com/moloch--/RootTheBox/issues/317

**Comment by jeffg2k** [comment]
If adding :Z to `/files:/opt/rtb/files:Z` fixes it, let me know.  I don't know that it would cause problems for non-SELinux systems, so it might be good to just add it to the `docker-compose.yml`

**Comment by dd121** [comment]
No it did not fix it. 
Yesterday I had no problem, after your commit with the last issue I did a new clean docker employment and now I have this problem...

**Comment by dd121** [comment]
after a docker-compose build my issue was fixed.

**Comment by jeffg2k** [comment]
I'll accept the magic.  I'm not sure what caused your issue, but yeah, nothing in the last commit would explain that.  I'm not able to reproduce such an issue, so I'm going to call it a container permissions fluke (docker's fault - lol).

**Comment by jeffg2k** [comment]
Let me ask - are you running SELinux and was the `docker-compose build` done after changing rw to Z in the `docker-compose.yml`?  Or was this just a strait build on the source and it just work this time?

**Comment by dd121** [comment]
I did not change the rw in Z, or at least I changed it back before the build. And I am running it on mac osx so no SELinux.
