### ISSUE TITLE
Issue Deploy Latest RTB

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#339]
Hi Team 

I pulled the latest RTB for a CTF but I came across this error 
**NOTE** I followed the wiki installation guide 
```shell
root@RootTheBox:~/RootTheBox# ./rootthebox.py --setup=prod
Traceback (most recent call last):
  File "./rootthebox.py", line 851, in <module>
    options.parse_config_file(options.config)
  File "/usr/local/lib/python3.6/dist-packages/tornado/options.py", line 415, in parse_config_file
    option.set(config[name])
  File "/usr/local/lib/python3.6/dist-packages/tornado/options.py", line 590, in set
    % (self.name, self.type.__name__, type(value))
tornado.options.Error: Option 'privacy_policy_link' is required to be a str (<class 'bool'> given)
```

**Comment by jeffg2k** [comment]
Thanks for the report - fixed. I haven't quite figured out how to test and edit pull requests properly and push them back up without creating a new branch and things got weird during the merge.  Should be all fixed now.

**Comment by jeffg2k** [comment]
As a note, if your rootthebox.cfg was saved and it now contains a value of False for `privacy_policy_link`, you may need to updated it to `""`.
