### ISSUE TITLE
Demo Box

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#341]
I want to complement the developers for making the game engine, In order to understand better , is there a fully loaded demo of RootTheBox hosted anywhere ?

**Comment by jeffg2k** [comment]
Haven't set one up but could probably do so fairly quickly.  Maybe on Heroku or something.  Just have to figure out how to have it reset regularly and perhaps self update.  I'll try to work on it this week.

**Comment by nishant2019** [comment]
Thanks for reply. I would be nice if you can set one and populate with some challenges and data , ot would really help

**Comment by jeffg2k** [comment]
I've run into an issue with memcached on Heroku (and maybe other platforms).  They use a binary protocol (allows for SASL authentication and is faster) for memcached add-ons, which the api module we're using `python-memcached` doesn't support.  It looks like `python-memcached` is no longer maintained.

It might be time to update our memcached client and make environment support more flexible.  Looks like the options would be [python-binary-memcached](https://github.com/jaysonsantos/python-binary-memcached) or [pylibmc](https://github.com/lericson/pylibmc) as they support the binary protocol.  I think `pylibmc` is a drop in replacement for `python-memcached`.

**Comment by jeffg2k** [comment]
@moloch-- is there a reason `x_headers` defaults to False?  Is there a negative to honoring the `X-FORWARDED-FOR` and `X-REAL-IP` http headers? Spoofing for session hijack?

**Comment by jeffg2k** [comment]
@nishant2019 I set up a quick demo box here https://rootthebox.herokuapp.com/
It's still a in-work as I need to have it reset itself periodically, but you can take a look.
Admin username is `admin` and the password is `rootthebox`.
Player username is `player` and the password is `rootthebox`.
You're welcome to register new users and do whatever you want in there.  Just be aware I can wipe it out at any moment as I'm still trying to develop the updated memcache and settings needed to deploy rootthebox into the cloud.
