### ISSUE TITLE
Red Team vs Blue Team

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#343]
How can I design challenges for Red vs Blue team ? what would the flags blue team will be submitting when defending against Red Team ?

**Comment by jeffg2k** [comment]
I've never competed in a Red / Blue exercise that used a CTF scoring engine, so not sure.  Maybe @moloch-- has some thoughts, but not sure a jeopardy style platform is the best way to go for something like that.  You could easily have an Admin grant points to each team manually based on events.

You could have the Admin award members with a key, which could be used in the engine to gain points.  Just set the Box to Single mode and the submit box will be valid for any flag in the box.
