### ISSUE TITLE
kubernetes issues

### ISSUE THREAD

**Issue by sabatmonk** [moloch--/RootTheBox#344]
Hi, 

i'm trying to run this in kubernetes (for reasons, i need to) and i have issues. i've converted the docker-compose with kompose and adapted it to match my kubernetes template, but for some reasons it looks like the memcached isn't accessible in the same pod (so 127.0.0.1 resolve properly).

Is there a way to run without memcache or did anyone try this and got it to work?

Regards

**Comment by jeffg2k** [comment]
Take a look at the memcached branch, which I'm trying to get to better support cloud environments. https://github.com/moloch--/RootTheBox/tree/memcached
It uses a memcache api that supports the binary format that allows for SASL authentication, which is what I'm seeing used by cloud providers.  Also, I just started working on this [Cloud Deployment](https://github.com/moloch--/RootTheBox/wiki/Cloud-Deployment) wiki which describes how to set up the memcache (at least on Heroku).  .  Would be great to get more information about your deployment as you progress we can improve this branch and get it ready to pull into master.

**Comment by jeffg2k** [comment]
You'll need to define the memcache settings in your environment vars.  It currently supports these:
```
MEMCACHIER_SERVERS
MEMCACHIER_USERNAME
MEMCACHIER_PASSWORD

MEMCACHEDCLOUD_SERVERS
MEMCACHEDCLOUD_USERNAME
MEMCACHEDCLOUD_PASSWORD

MEMCACHED_SERVERS
MEMCACHED_USER
MEMCACHED_PASSWORD
```

**Comment by jeffg2k** [comment]
@sabatmonk did you ever get things running on kubernetes?  Would love it if you might be able to add a section to the Wiki on [Cloud Deployment](https://github.com/moloch--/RootTheBox/wiki/Cloud-Deployment)

**Comment by Jaa9** [comment]
We are trying to deploy RTB on an Azure Kubernetes Service (AKS) platform. We have successfully changed storage persistency to match functionality in AKS and are able to publish the service. But we have an issue with correct access to the service after a valid authentication. Users (including admin) are redirected back to the login page. We find that there has been an earlier issue #99 refering to memcached as the session storage used by RTB. We haven't done anything in regards to memcached and we are wondering if memcached is still a requirement for session persistency and a root cause of our problem?

**Comment by jeffg2k** [comment]
Yes, memcached is still required.  You'll want to look into Memcached Cloud or MemCachier I expect.

**Comment by Jaa9** [comment]
Solved the issue and this is now working. Thanks for you feedback. RTB up and running in AKS.

1. Deployed memcached container from bitnami/memcached:latest
2. Created a K8s service with a Cluster-IP exposing memcahed in the cluster
3. Added ENV variable MEMCACHED_SERVERS  to RTB container

**Comment by jeffg2k** [comment]
Awesome!  If you have a chance to write up the steps in the [Cloud-Deployment](https://github.com/moloch--/RootTheBox/wiki/Cloud-Deployment) wiki, it would be great for helping others trying to do the same.

**Comment by Jaa9** [comment]
Happy to help. I have uploaded a whole section in the Cloud Wiki explaining my tested setup.
