### ISSUE TITLE
 Function enhancement

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#345]
Want to add administrators to check the completion progress of each user, and answer categories，Now each user can only check their answer status after logging in。

**Comment by jeffg2k** [comment]
Added a user progress page that is accessible to administrators.  I added a "Statistics" button for each user to the Users Management page.  That will open a page that looks similar to the user homepage.

**Comment by cohux** [comment]
Has this feature been tested? 
Thanks developers

**Comment by jeffg2k** [comment]
It worked when I put it together last night, but you're probably the first user, so let me know if you run into any bugs.
