### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#346]
log:
File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1516, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)

Then unable to access。

**Comment by jeffg2k** [comment]
What page or form were you trying to submit?  This check is done on every POST.

**Comment by jeffg2k** [comment]
I looked at all the html forms within RTB and didn't see any cases where it was missing the xsrf, so I'm going to close this for now.  If you're able to identify the form / page that caused the issue you're seeing, please reopen and I can try to reproduce it.
