### ISSUE TITLE
Enhancement: Sample Game for testing purposes

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#349]
It would be nice to have in the repo a sample game (in XML) to play and test the full system.

Does anyone can share one good sample ?
Thanks

**Comment by jeffg2k** [comment]
There is a [demo box](https://rootthebox.herokuapp.com/) with a full system.  You could log in as admin and export it.  Alternatively, you could run [Juice Shop CTF](https://github.com/bkimminich/juice-shop-ctf).

**Comment by nunoguerreiro** [comment]
> There is a [demo box](https://rootthebox.herokuapp.com/) with a full system. You could log in as admin and export it. Alternatively, you could run [Juice Shop CTF](https://github.com/bkimminich/juice-shop-ctf).

Thanks @jeffg2k found that also.

**Comment by nunoguerreiro** [comment]
Closed - we can see the demo box and export the configs.
