### ISSUE TITLE
Enhancement: Possibility to add external tools

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#357]
It would be nice to add a possibility to add (via the admin site) additional external or internal tools (additional http websites).

Also could be useful to add the window/output in the same RTB context (without the need to open an external website).

I was wondering if we can add an external wiki for example to provide additional guidelines to support each challenge/flag...

Like the CyberChef, but additional other ones...

**Comment by sep3** [comment]
I used [Zim](https://www.zim-wiki.org/) for a long time, but I don't recommend it here, because it looks like the "Team PasteBin" feature.

But I recommend [Jupiter](https://jupyter.org/) which is a Notebook, ideal for examples with code.

**Comment by jeffg2k** [comment]
Added this feature and made CyberChef the first entry.  You'll have to edit the rootthebox.cfg to add additional entries to the `tool_links` option as it's not in the GUI configuration.  To add it to your existing RTB instance, you'll want to click the update button in the GUI to write the default value to the configuration, then edit the rootthebox.cfg or add it manually under the Application section.

### tool_links
> List of Dict

Adds links to the `Tools and Upgrades` menu.  This should be structured as a List of Dictionaries.  "name" and "url" are required items in the dictionary, target is optional and will default to "_blank".  Default: `[{"name": "CyberChef", "url": "/cyberchef/", "target": "_blank"}]`  

**Multilink Example:** 
`tool_links = [{"name": "Cheat Sheets", "url": "https://pen-testing.sans.org/resources/downloads"}, {"name": "Best Video", "url": "https://www.youtube.com/watch?v=oHg5SJYRHA0", "target": "_self"}]`

**Comment by nunoguerreiro** [comment]
Hi @jeffg2k  thanks for this.

Think that there is a small bug since I tried to use to sample in your post above and it gives an error after saving the configuration (in the admin pages)...

Seems that you try to check if there is a default value and does not work after.

Can you try to check ?

Traceback (most recent call last):
  File "./rootthebox.py", line 910, in <module>
    options.parse_config_file(options.config)
  File "/home/nmag/.local/lib/python3.6/site-packages/tornado/options.py", line 415, in parse_config_file
    option.set(config[name])
  File "/home/nmag/.local/lib/python3.6/site-packages/tornado/options.py", line 584, in set
    % (self.name, self.type.__name__)
tornado.options.Error: Option 'tool_links' is required to be a list of str

**Comment by jeffg2k** [comment]
Thanks, I've reverted it.  Limitation of tornado options parsing, which works fine as a default value, just not reading from the cfg file itself.  I'll see how best to work around it.

**Comment by jeffg2k** [comment]
Pushed a fix - had to define the type.

**Comment by nunoguerreiro** [comment]
working now. Thanks.
