### ISSUE TITLE
memcached

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#358]
Since last update the config values for memcached are different from the documentation:

Now when go to the admin page, after saving I will have in the config file:
# [ Cache ]
memcached = "127.0.0.1"
memcached_user = ""
memcached_password = ""

memcached_port is deleted
memcached_server is renamed to memcached

**Comment by jeffg2k** [comment]
Our documentation was wrong - it's always been just "memcached" in the code.  I'll update that.  I would rather it be memcached_servers, but for backward compatibility, I left it as just memcached.  If it's an environmental variable, it will accept either "memcached" or "memcached_servers".    "memcached_port" wasn't actually used at all in the code and had an incorrect port defined as the default.  So I just removed it.  If you want to define a port, you can do so as part of the hostname:port format.
