### ISSUE TITLE
Random Flags per team

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#360]
Is possible to have random & different flags for each team/player ?

Was thinking to have like a bank of flags and then randomly the system will distribute a specific fixed number of questions for each team ...

Thanks,

**Comment by jeffg2k** [comment]
Within the current framework, you could assign each team their own level and unlock that level only for that team.  You'd have to assign the flags manually to box within that level though.

As for a built-in feature that does this, it's not something I've seen in a CTF (I expect to keep the playing field level).

**Comment by nunoguerreiro** [comment]
> Within the current framework, you could assign each team their own level and unlock that level only for that team. You'd have to assign the flags manually to box within that level though.
> 
> As for a built-in feature that does this, it's not something I've seen in a CTF (I expect to keep the playing field level).

That would solve the need. Thanks will try
