### ISSUE TITLE
Error: 'NoneType' object has no attribute 'key' on start RTB

### ISSUE THREAD

**Issue by agenteph** [moloch--/RootTheBox#361]
OK folks ? My rtb suddenly stopped, I went to analyze the rtb service and noticed the following error:

Error: 'NoneType' object has no attribute 'key'

Does anyone know what it is? I already checked the table, files and I can't fix it.

**Comment by jeffg2k** [comment]
That looks like it might be a snapshot problem as I think it's the only thing that uses `.key`.  I pushed an update that checks to make sure the snapshot is not None before trying the key attribute.  Let me know if this fixes your issue.

**Comment by agenteph** [comment]
I did the update and restarted the service and now it's in the log...

mar 22 13:59:01 nameserver rootthebox.py[14822]: [I 200322 13:59:01 GameHistory:55] Loading game history from database ...
mar 22 13:59:02 nameserver rootthebox.py[14822]: [I 200322 13:59:02 GameHistory:69] Cached snapshot (23414 of 23420)
mar 22 13:59:02 nameserver rootthebox.py[14822]: [E 200322 13:59:02 rootthebox:54] Error: (MySQLdb._exceptions.OperationalError) (1054, "Unknown column 'game_level._description' in 'field list'")
mar 22 13:59:02 nameserver rootthebox.py[14822]:     [SQL: SELECT game_level.id AS game_level_id, game_level.created AS game_level_created, game_level.uuid AS game_level_uuid, game_level.next_level_id AS game_level_next_level_id, game_level._number AS game_level__number, game_level._buyout AS game_level__buyout, game_level._type AS game_level__type, game_level._reward AS game_level__reward, game_level._name AS game_level__name, game_level._description AS game_level__description
mar 22 13:59:02 nameserver rootthebox.py[14822]:     FROM game_level, snapshot_team_to_game_level
mar 22 13:59:02 nameserver rootthebox.py[14822]:     WHERE %s = snapshot_team_to_game_level.snapshot_team_id AND game_level.id = snapshot_team_to_game_level.gam_level_id]
mar 22 13:59:02 nameserver rootthebox.py[14822]:     [parameters: (1165512,)]
mar 22 13:59:02 nameserver rootthebox.py[14822]:     (Background on this error at: http://sqlalche.me/e/e3q8)
mar 22 13:59:02 nameserver systemd[1]: rtb.service: Main process exited, code=exited, status=1/FAILURE
mar 22 13:59:02 nameserver systemd[1]: rtb.service: Failed with result 'exit-code'.

**Comment by jeffg2k** [comment]
I think your database failed to update with the Alembic script.  Perhaps it got interrupted or something as it appears you don't have the `_description` column in your `game_levels` table.  These columns should have been added to your database as part of `bc091b7be912_add_descriptive_columns`.
```
    op.add_column("user", sa.Column("_notes", sa.VARCHAR(512)))
    op.add_column("team", sa.Column("_notes", sa.VARCHAR(512)))
    op.add_column("game_level", sa.Column("_description", sa.VARCHAR(512)))
    op.add_column("corporation", sa.Column("_description", sa.VARCHAR(512)))
```
Also after that, you should also have the update `9443ded40161_add_box_lock` which does:
```
    op.add_column("box", sa.Column("_locked", sa.BOOLEAN, nullable=False))
```

**Comment by jeffg2k** [comment]
I can reproduce this.. I think there is an issue where GameHistory is loading before the Update DB is run.  Investigating...

**Comment by jeffg2k** [comment]
Ok, I pushed an update that puts the database updates before loading game history.  Hopefully that will update those tables and resolve the issue.  Let me know :)

**Comment by agenteph** [comment]
Thanks @jeffg2k, now works great! Full online.
