### ISSUE TITLE
Descripton more than 1024 character

### ISSUE THREAD

**Issue by BNYBLN030** [moloch--/RootTheBox#362]
Hello i need in the desciption more than 1024 characters ...... what should i change in the code?

**Comment by moloch--** [comment]
https://github.com/moloch--/RootTheBox/blob/master/models/Flag.py#L75

**Comment by jeffg2k** [comment]
Also, we trim the description in the setter and our forms have a maxlength.
https://github.com/moloch--/RootTheBox/blob/master/models/Flag.py#L291
https://github.com/moloch--/RootTheBox/blob/master/templates/admin/create/flag-static.html#L73
https://github.com/moloch--/RootTheBox/blob/master/templates/admin/create/flag-regex.html#L73
etc..

If it's just for a single flag or something, it might be easier to just directly edit the description in the database.

**Comment by BNYBLN030** [comment]
thanks, now it works !!^^
