### ISSUE TITLE
Creating custom storyline

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#363]
How can I create multiple and custom story line and missions

**Comment by jeffg2k** [comment]
The game allows for an intro story line upon first login, a completion message for each flag, and a completion message for each box.  So you can craft your story line around those events.  For me the flag completion can be too much, depending on the difficulty of the flag, so I focus on the first login and box stories.  However, you could have each box as it's own storyline with the flag completion stepping through it, particularly if you set flag dependency.

**Comment by nishant2019** [comment]
> 
> 
> The game allows for an intro story line upon first login, a completion message for each flag, and a completion message for each box. So you can craft your story line around those events. For me the flag completion can be too much, depending on the difficulty of the flag, so I focus on the first login and box stories. However, you could have each box as its own storyline with the flag completion stepping through it, particularly if you set flag dependency.

Can you link to fully populated engine ?

**Comment by jeffg2k** [comment]
I don't, but you're welcome to connect to the demo https://rootthebox.herokuapp.com/ as admin (pw: rootthebox).   Go into configuration and turn on Story Mode.  Set a `Capture Message` on one of the flags.  Then go register a new user and log in - you'll see the default first login story.  Then go capture the flag and you'll see the capture message (storyline) for that flag.  Box Capture Messages work the same as the flag but trigger on completion of the box.

**Comment by nishant2019** [comment]
> 
> 
> I don't, but you're welcome to connect to the demo https://rootthebox.herokuapp.com/ as admin (pw: rootthebox). Go into configuration and turn on Story Mode. Set a `Capture Message` on one of the flags. Then go register a new user and log in - you'll see the default first login story. Then go capture the flag and you'll see the capture message (storyline) for that flag. Box Capture Messages work the same as the flag but trigger on completion of the box.

Thanks for input. How can I host RTB on Heroku ?? I am getting all errors

**Comment by jeffg2k** [comment]
Here are the instructions for [Cloud Deployment](https://github.com/moloch--/RootTheBox/wiki/Cloud-Deployment) that I was working on, however, there is one major issue with Heroku which works to our favor with the demo instance.  Heroku has an ephemeral filesystem which is reset every 24 hours.  So your `files` directory would need to be static when you upload and your database would need to be remote (using environment vars). There may be ways to set the files directory to an AWS filesystem, but I haven't worked through that.

It might work out better on something like Digital Ocean, but I haven't had a chance to spend more time on it.
