### ISSUE TITLE
404 - Glitch in the Matrix

### ISSUE THREAD

**Issue by BNYBLN030** [moloch--/RootTheBox#365]
i want to create web challanges ... for this i installed apache on the same server as rootthebox is running!
if i want to open the link to challange, i always get the following error message:

![Unbenannt](https://user-images.githubusercontent.com/29738526/77888762-08a11e80-726d-11ea-96a4-db357946afc6.PNG)

**Comment by jeffg2k** [comment]
I don't think I have enough information to help you, if you could explain the issue more.  RootTheBox runs its own web server, so make sure it runs on a different port than apache.  If you could enable [debugging](https://github.com/moloch--/RootTheBox/wiki/Installation#Debugging) and watch the console for errors, maybe that would narrow down your issue.

**Comment by BNYBLN030** [comment]
Root the Box runs on port 443 and Apache on port 80 for web-challanges!
The URL to RTB is https://ctf.xxx.de/ and the web-challanges are here: https://ctf.xxx.de/ctf/ on apache!
If i open the url to the web-challanges i get the message that you see above

**Comment by jeffg2k** [comment]
If you're using port 80, I expect your web challenges should be http, not https, correct?  What you're seeing is that RootTheBox is receiving the request for https://ctf.xxx.de/ctf/, not Apache.  You may want to turn RootTheBox off and make sure everything on Apache is working as expected.

**Comment by jeffg2k** [comment]
I'm going to assume this was resolved - if you still think it's an issue with RTB, reopen and add more comments.
