### ISSUE TITLE
proxy with nginx

### ISSUE THREAD

**Issue by BNYBLN030** [moloch--/RootTheBox#368]
i want to use nginx as proxy ... because i have different suddomains for the challenges.
For example for rootthebox --> ctf.xxx.de or for the owasp juice shop owasp-ctf.xxx.de. For the juice shop the proxy works ... but not for rtb ....!
I saw you also have a ngix template in the project that doesn't work for me either

**Comment by jeffg2k** [comment]
Here are some [wiki instructions](https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx) that describe the process, but I haven't gone through it myself.  A couple big things are probably the `rootthebox.cfg` option of `x_headers = True` and make sure `origin` is specified to the correct domain name.  If you find additional steps that should be included, please add to the wiki.
