### ISSUE TITLE
How do I back up user data

### ISSUE THREAD

**Issue by xuxinhen** [moloch--/RootTheBox#370]
I want to back up the user data, or back up the entire RTB instance, but it is easy to lose some files.when copying files/ folders. The existing solution is to copy the entire RTB/ folder, but this is not the best solution。The export function in the background is not enough to export the entire RTB instance

**Comment by jeffg2k** [comment]
In addition to the xml export, backup the `files` directory.  That should be all you need to fully restore.

**Comment by jeffg2k** [comment]
Clarification - that restores to a clean game instance.  It will not copy over user accounts or prior gameplay.  You'd want to do a database backup for user / team data.

**Comment by jeffg2k** [comment]
If you're running a sqlite db, you can just copy `.db` file for the user data.
