### ISSUE TITLE
cannot access higher levels

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#371]
I have set 100% completion of Level 0 for activating Level 1, however even after completing Level 0 , Level 1 is not activating.. Screenshots attached
![image](https://user-images.githubusercontent.com/49723167/79204927-ea394680-7e5a-11ea-8ab1-46ccb4b1682c.png)

![image](https://user-images.githubusercontent.com/49723167/79204880-de4d8480-7e5a-11ea-8a1f-cbcc1453d57f.png)

**Comment by jeffg2k** [comment]
Thank you for the bug report.  It has now been fixed.  We had a separate `_check_level` function which was called when all level flags were captured.  That function failed to commit the unlock to the database.

**Comment by jeffg2k** [comment]
@nishant2019 as an additional note, this update will not retroactively unlock levels that didn't get unlocked.  It just fixes the bug for future flag captures.  If you need fix an existing level that failed to unlock for a team, you'll need to add the entry manually to the database table `team_to_game_level`.
