### ISSUE TITLE
Add new theme

### ISSUE THREAD

**Issue by mcomtzg** [moloch--/RootTheBox#375]
Hello, what is the best way for add a new theme?

**Comment by jeffg2k** [comment]
You can add the css to `/static/css/themes`.  RootTheBox is currently using Bootstrap 2, so you could probably use additional themes from https://bootswatch.com/2/

**Comment by mcomtzg** [comment]
thanks for your answer @jeffg2k but when I added the new in /opt/RootTheBox/static/css/themes, the new theme doesn't reflect in the front end.

in addition,  I'm using the DB.. in the DB:

MariaDB [rootthebox]> select id,theme_id,_file_name from theme_file;
+----+----------+--------------------+
| id | theme_id | _file_name         |
+----+----------+--------------------+
|  1 |        1 | bootstrap.min.css  |
|  2 |        2 | amelia.min.css     |
|  3 |        3 | cyborg.min.css     |
|  4 |        4 | readable.min.css   |
|  5 |        5 | slate.min.css      |
|  6 |        6 | spruce.min.css     |
|  7 |        7 | united.min.css     |
|  8 |        8 | cerulean.min.css   |
|  9 |        9 | journal.min.css    |
| 10 |       10 | simplex.min.css    |
| 11 |       11 | spacelab.min.css   |
| 12 |       12 | superhero.min.css  |
| 13 |       13 | geocities.min.css  |
| 14 |       14 | 386.css            |
| 15 |       14 | 386.js             |
| 16 |       14 | 386.responsive.css |
+----+----------+--------------------+

I need to add the new the in the DB?

**Comment by jeffg2k** [comment]
Yes, looks like you're correct.  There are two tables in the database, theme and theme_file, that will need to be updated for the themes.  Never actually added an additional theme, so haven't really worked through the process.  To make it a little easier, you could probably just alter an existing one either by updating the db or deleting the css and naming yours in its place.

**Comment by mcomtzg** [comment]
thanks @jeffg2k

**Comment by moloch--** [comment]
Themes are just Boostrap CSS files that get rendered into the responses using the themes HTML module:

https://github.com/moloch--/RootTheBox/blob/master/templates/theme/theme.html

The database is used a whitelist of known theme files.

To add a theme:
- Add CSS file(s) to: https://github.com/moloch--/RootTheBox/tree/master/static/css/themes
- Make an entry in the database: https://github.com/moloch--/RootTheBox/blob/master/setup/bootstrap.py#L69
