### ISSUE TITLE
Is there a plan for webhook support?

### ISSUE THREAD

**Issue by MillsapCyber** [moloch--/RootTheBox#377]
I was wondering if there was any plans / effort being made towards automatic scoring, as in automatic attribution of actions on a box. If so please let me know, I'd be happy to see if I can write some kind of integration for it.

**Comment by jeffg2k** [comment]
No plans yet, but we can add it to the wish list.

**Comment by jeffg2k** [comment]
Webhook support added https://github.com/moloch--/RootTheBox/pull/437
