### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by alahammad** [moloch--/RootTheBox#379]
One of my friend found security issue when user register and upload avatar, he can upload malicious code inside svg, please add it to images filter.

Thanks

**Comment by jeffg2k** [comment]
SVG should already be filtered.  Can you describe the process?  I tried to upload an svg and got this:

<img width="442" alt="Screen Shot 2020-05-30 at 8 03 28 AM" src="https://user-images.githubusercontent.com/161904/83327780-6392ca00-a24c-11ea-9c1b-36e4c6ac0e36.png">

**Comment by alahammad** [comment]
try to use this code in svg:
`<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
 
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
<polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
<script type="text/javascript">
alert('This app is probably vulnerable to XSS attacks!');
</script>
</svg>`

and try to upload it registration, it will pass.

**Comment by jeffg2k** [comment]
It blocks SVG uploads, so not sure how it was uploaded.  Registration didn't allow me to upload an `.svg` file extension.  Did you use another extension type?

**Comment by alahammad** [comment]
no i use .svg extension and tried in registration form. try use this [svg](https://wetransfer.com/downloads/a9e8b68f1ec6e77758c7182c4a071e2020200531181515/0eb709ead96e14dbeb7a9ffad8e8cafe20200531181533/4f2c68?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email)
and in do in registration form. if not clear i can attach video to make it clear

**Comment by jeffg2k** [comment]
I think I understand - it doesn't let you create an account with that image, but it will display it in the preview.  Is that what you're saying?

**Comment by alahammad** [comment]
yes, and that will make issues. can we disable svg extension .

**Comment by jeffg2k** [comment]
I can restrict the the mime types in the form.  I think this is purely a html / js issue.  Pushed up https://github.com/moloch--/RootTheBox/commit/37437cd5b1e70ba7c1611260317e42f956c6ef5a
