### ISSUE TITLE
No such constraint error

### ISSUE THREAD

**Issue by mharrod** [moloch--/RootTheBox#385]
Not sure if this is something I did.  I did a rootthebox.py --update and all seemed to go fine.  However, when I start the box now, it does not start and I get the following error.  This has never happened before and I have update quite frequently.  Is there anything I can do to fix this.  The error is below:

[I 200619 02:21:34 __init__:253] Checking for Database Updates...
[I 200619 02:21:34 migration:154] Context impl SQLiteImpl.
[I 200619 02:21:34 migration:161] Will assume non-transactional DDL.
[I 200619 02:21:34 migration:513] Running upgrade 71aa3c94b7f5 -> bd7bd19e98bd, sourcecode cascade
[E 200619 02:21:34 rootthebox:54] Error: No such constraint: 'source_code_ibfk_1'

**Comment by jeffg2k** [comment]
It's possible that it got part way through the database update and something happened.  I'll describe where it is at.  RootTheBox uses Alembic to update the database schema.  Your error shows that it is trying to run the file `alembic/versions/bd7bd19e98bd_sourcecode_cascade.py`.

This file drops the foreign key `source_code_ibfk_1` in the `source_code` table and recreates it.  The intent being to change it from on delete `RESTRICT` to `CASCADE`.  However, the error your getting says the `source_code_ibfk_1` constraint doesn't exist for Alembic to drop.

What you'll have to do is edit the database directly.  I expect the easiest thing would be to create `source_code_ibfk_1` and hopefully the update will then be able to drop and recreate it.  Run this as a MySQL sql command.
```
ALTER TABLE `source_code` 
ADD CONSTRAINT `source_code_ibfk_1`
  FOREIGN KEY (`box_id`)
  REFERENCES `box` (`id`)
  ON DELETE CASCADE;
```

**Comment by jeffg2k** [comment]
@mharrod Did this resolve your issue?

**Comment by mharrod** [comment]
It probably would.  However, we were running a test instance and used Sqlite instead.  Seemingly, sqlite does not allow you to mess with constraints after the table has been created. One has to create a new table with FK constraint, copy data across, drop old table and then rename newly created table.  So we will either try that, comment out the check in the code or just rebuild everything but use MYSQL this time.  Thanks for you help.
