### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#387]
I am running roothhebox using docker. I have forgotten the password . How can I reset

**Comment by jeffg2k** [comment]
To run a command in Docker, you should be able to do this:

`docker exec -it <container_id_or_name> echo "I'm inside the container!"`

To reset the password in RootTheBox, you can run the recovery:

`rootthebox.py --recovery`

I haven't tested this, but I'm thinking you should be able to do run this to reset the password:

`docker exec -it <container_id_or_name> python3 /opt/rtb/rootthebox.py --recovery`

**Comment by nishant2019** [comment]
Thanks , the solution worked
