### ISSUE TITLE
Wrong Time for flag Capture

### ISSUE THREAD

**Issue by nishant2019** [moloch--/RootTheBox#388]
I am getting incorrect time for flag capture. How can I change time zone ? My computer has correct time

**Comment by jeffg2k** [comment]
I think all the timestamps are handled by the database.  It's a datetime field and when the record is inserted, that field is populated automatically (by the database or perhaps by sqlalchemy).  I think the only thing we're doing is displaying it with [strftime](https://strftime.org/) via `strftime("%I:%M%p %x")`.

**Comment by jeffg2k** [comment]
I'm going to close this for inactivity.  It looks like a database / host configuration issue.  If you continue to have the issue and can give more information to troubleshoot, feel free to reopen.  At this time, I don't see that it's an issue with RootTheBox.
