### ISSUE TITLE
Disable Game Materials while the game has not started

### ISSUE THREAD

**Issue by gmorchio** [moloch--/RootTheBox#389]
Dear all:

We have realized that Game Materials is available while people are registering, which is not desired on the following scenario:
The CTF will begun a week after the registration start. During that period of time, the process of challs uploading is still in progress. So we don't want that the registered user have access to those materials. I know we can move game_materials folders, but it is better that it is blocked through the app.

Thanks! 
Great job by the way

**Comment by jeffg2k** [comment]
Good idea - I'm trying to think through how best to make this an optional setting and if it should be the default.  I could also see a scenario where they may want to allow pre-game access, such as access to disk images, vms, or other game prep.

**Comment by jeffg2k** [comment]
Added the boolean option to the config `game_materials_on_stop`.  The default is `True`, which will allow users to see the game materials when the game is stopped.  If `False`, the game materials will be inaccessible to the users when the game is stopped.
