### ISSUE TITLE
No result in scoreboard

### ISSUE THREAD

**Issue by BNYBLN030** [moloch--/RootTheBox#390]
hi,
unfortunately i don't get any entries in the scoreboard, although currently 7 participants are registered and have received points

**Comment by BNYBLN030** [comment]
With the web developer tools under Firefox I get the following error message, it has something to do with it?

**Firefox kann keine Verbindung zu dem Server unter wss://ctf.xxxx.de/connect/notifications/updates aufbauen.

Firefox kann keine Verbindung zu dem Server unter wss://ctf.xxxx.de/scoreboard/wsocket/game_data aufbauen.**

**Comment by jeffg2k** [comment]
It appears to be failing to connect to your web socket.  Double check your `origin` in your configuration file `files/rootthebox.cfg` and the other options in the `Server` section.

**Comment by BNYBLN030** [comment]
@jeffg2k all configuration are correct. But i use a web reverse proxy with nginx! Maybe this is the problem ..... i used following configuration but it doesnt work:

       # websocket headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

**Comment by jeffg2k** [comment]
A reverse proxy can definitely cause this issue.  If you're using nginx, make sure to review the examples in the setup directory [nginx.conf](https://github.com/moloch--/RootTheBox/blob/master/setup/nginx.conf) and [nginx_vhost_rtb.conf](https://github.com/moloch--/RootTheBox/blob/master/setup/nginx_vhost_rtb.conf) along with our guide [Deployment with Nginx](https://github.com/moloch--/RootTheBox/wiki/Deployment-With-Nginx).  Hopefully that will get it resolved.

**Comment by nunoguerreiro** [comment]
yes, confirmed that works like jeffg2k is detailing

**Comment by jeffg2k** [comment]
I'm going to close this issue for inactivity as I see it as more of a troubleshooting question.  If the problem remains and you need assistance, feel free to reopen the ticket.
