### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by r3curs1v3-pr0xy** [moloch--/RootTheBox#391]
Hello Team,

This platform is really awesome specially its themes and features. But I am unable to find a way to make changes or customize the home page and incoming transmissions. Is this feature is available in platform or I need to make changes in code itself?

Thanks!

**Comment by jeffg2k** [comment]
@r3curs1v3-pr0xy take a look at the [Game](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#game) section in the configuration file.  You can change the game name, logo, tagline, org footer, and privacy policy.  And you can also change the default theme if you desire.  If there is something else you're looking to change, let me know and I'll see if it makes sense to turn it into an configuration option.
