### ISSUE TITLE
Glitch in the Matrix Actually a 500

### ISSUE THREAD

**Issue by MidasJade** [moloch--/RootTheBox#392]
Hi Jeff, I'm having a similar issue the the 404 bug that was closed. I did the docker install and everything worked great. Created a box and a flag in a chrome browser as admin. In another incognito browser I'm logged in as a player and can see the flag. If I add another flag and refresh in the player browser, I get the 404. I've tried resetting the game after adding flags. I've tried clearing cache and cookies.

Admin URL (shows the box and flag):
http://192.168.17.180:8888/user/missions/boxes?uuid=c11135ba-702b-4a64-8bd4-5c0ea9adef12

Player URL (shows 404):
http://192.168.17.180:8888/user/missions/boxes?uuid=c11135ba-702b-4a64-8bd4-5c0ea9adef12

When I viewed with Developer Tools it's actually showing a 500 error, so I captured the server output to a log file pasted below. Also pasted the box with the flag that it's not displaying. I might take a crack at debugging later this weekend but wanted to throw this out there in case it was something you recognized and could quickly edit. If you need me to run some other tests, just let me know. Really like this project!

 Attaching to rootthebox_memcached_1, rootthebox_webapp_1
webapp_1      200819 22:15:34 __init__:253] Checking for Database Updates...
webapp_1      200819 22:15:34 migration:155] Context impl SQLiteImpl.
webapp_1      200819 22:15:34 migration:158] Will assume non-transactional DDL.
webapp_1      200819 22:15:34 GameHistory:54] Loading game history from database ...
webapp_1      200819 22:15:34 GameHistory:67] Cached snapshot (1 of 4)
webapp_1      200819 22:15:34 GameHistory:67] Cached snapshot (2 of 4)
webapp_1      200819 22:15:34 GameHistory:67] Cached snapshot (3 of 4)
webapp_1      200819 22:15:34 GameHistory:67] Cached snapshot (4 of 4)
webapp_1      200819 22:15:34 GameHistory:71] History load complete.
webapp_1     [1m[36m[*] [0mSwitching CWD to '/opt/rtb'
webapp_1     [1m[36m[*] [0m[1m[31mStarting RTB on [36mhttp://localhost:8888[0m
webapp_1      200819 22:15:39 web:2246] 302 GET /user (192.168.17.1) 0.98ms
webapp_1      200819 22:15:39 web:2246] 200 GET /login (192.168.17.1) 9.00ms
webapp_1      200819 22:15:39 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 1.79ms
webapp_1      200819 22:15:46 PublicHandlers:113] Successful login: midasjade from 192.168.17.1
webapp_1      200819 22:15:46 web:2246] 302 POST /login (192.168.17.1) 192.02ms
webapp_1      200819 22:15:46 web:2246] 200 GET /user (192.168.17.1) 40.09ms
webapp_1      200819 22:15:46 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.70ms
webapp_1      200819 22:15:46 web:2246] 200 GET /static/js/libs/highcharts.js.map (192.168.17.1) 12.25ms
webapp_1      200819 22:15:46 web:2246] 200 GET /static/js/libs/highcharts-more.js.map (192.168.17.1) 9.41ms
webapp_1      200819 22:15:51 web:2246] 302 GET /user (192.168.17.1) 0.92ms
webapp_1      200819 22:15:51 web:2246] 200 GET /login (192.168.17.1) 1.13ms
webapp_1      200819 22:15:51 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.75ms
webapp_1      200819 22:15:59 PublicHandlers:113] Successful login: admin from 192.168.17.1
webapp_1      200819 22:16:00 web:2246] 302 POST /login (192.168.17.1) 179.73ms
webapp_1      200819 22:16:00 web:2246] 200 GET /user (192.168.17.1) 195.33ms
webapp_1      200819 22:16:00 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.73ms
webapp_1      200819 22:16:00 web:2246] 304 GET /scoreboard/ajax/timer (192.168.17.1) 0.67ms
webapp_1      200819 22:16:02 BaseHandlers:253] The game is about to begin, good hunting!
webapp_1      200819 22:16:02 web:2246] 302 POST /admin/game (192.168.17.1) 11.62ms
webapp_1      200819 22:16:02 web:2246] 200 GET /user (192.168.17.1) 172.51ms
webapp_1      200819 22:16:02 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.78ms
webapp_1      200819 22:16:02 web:2246] 304 GET /scoreboard/ajax/timer (192.168.17.1) 2.35ms
webapp_1      200819 22:16:05 web:2246] 200 GET /user (192.168.17.1) 26.90ms
webapp_1      200819 22:16:05 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.86ms
webapp_1      200819 22:16:05 web:2246] 200 GET /static/js/libs/highcharts.js.map (192.168.17.1) 11.87ms
webapp_1      200819 22:16:05 web:2246] 200 GET /static/js/libs/highcharts-more.js.map (192.168.17.1) 15.95ms
webapp_1     [E 200819 22:16:07 web:1788] Uncaught exception GET /user/missions/boxes?uuid=c11135ba-702b-4a64-8bd4-5c0ea9adef12 (192.168.17.1)
webapp_1         HTTPServerRequest(protocol='http', host='192.168.17.180:8888', method='GET', uri='/user/missions/boxes?uuid=c11135ba-702b-4a64-8bd4-5c0ea9adef12', version='HTTP/1.1', remote_ip='192.168.17.1')
webapp_1         Traceback (most recent call last):
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
webapp_1             result = method(*self.path_args, **self.path_kwargs)
webapp_1           File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
webapp_1             return method(self, *args, **kwargs)
webapp_1           File "/opt/rtb/handlers/MissionsHandler.py", line 119, in get
webapp_1             self.render(
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 856, in render
webapp_1             html = self.render_string(template_name, **kwargs)
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1005, in render_string
webapp_1             return t.generate(**namespace)
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 361, in generate
webapp_1             return execute()
webapp_1           File "missions/box_html.generated.py", line 778, in _tt_execute
webapp_1             _tt_tmp = str(flag.choicelist())  # missions/box.html:348 (via main.html:32)
webapp_1           File "/opt/rtb/models/Flag.py", line 396, in choicelist
webapp_1             return json.dumps(choices)
webapp_1           File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
webapp_1             return _default_encoder.encode(obj)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
webapp_1             chunks = self.iterencode(o, _one_shot=True)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
webapp_1             return _iterencode(o, 0)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
webapp_1             raise TypeError(f'Object of type {o.__class__.__name__} '
webapp_1         TypeError: Object of type bytes is not JSON serializable
webapp_1     [E 200819 22:16:07 BaseHandlers:194] Request from 192.168.17.1 resulted in an error code 500:
webapp_1         Traceback (most recent call last):
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
webapp_1             result = method(*self.path_args, **self.path_kwargs)
webapp_1           File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
webapp_1             return method(self, *args, **kwargs)
webapp_1           File "/opt/rtb/handlers/MissionsHandler.py", line 119, in get
webapp_1             self.render(
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 856, in render
webapp_1             html = self.render_string(template_name, **kwargs)
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1005, in render_string
webapp_1             return t.generate(**namespace)
webapp_1           File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 361, in generate
webapp_1             return execute()
webapp_1           File "missions/box_html.generated.py", line 778, in _tt_execute
webapp_1             _tt_tmp = str(flag.choicelist())  # missions/box.html:348 (via main.html:32)
webapp_1           File "/opt/rtb/models/Flag.py", line 396, in choicelist
webapp_1             return json.dumps(choices)
webapp_1           File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
webapp_1             return _default_encoder.encode(obj)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
webapp_1             chunks = self.iterencode(o, _one_shot=True)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
webapp_1             return _iterencode(o, 0)
webapp_1           File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
webapp_1             raise TypeError(f'Object of type {o.__class__.__name__} '
webapp_1         TypeError: Object of type bytes is not JSON serializable
webapp_1         
webapp_1     [E 200819 22:16:07 web:2246] 500 GET /user/missions/boxes?uuid=c11135ba-702b-4a64-8bd4-5c0ea9adef12 (192.168.17.1) 51.17ms
webapp_1      200819 22:16:07 web:2246] 101 GET /connect/notifications/updates (192.168.17.1) 0.66ms
Gracefully stopping... (press Ctrl+C again to force)

![flag](https://user-images.githubusercontent.com/7806936/90696646-41ed2180-e242-11ea-9267-7a0ac5e2d535.jpg)

**Comment by jeffg2k** [comment]
Thanks for the report - I plan to take a look tomorrow.  It looks like an issue with the transition from Python2 -> Python3.  The whole str vs bytes thing is a real pain, and oddly, I've found things that work fine in my Ubuntu environment that have a problem with the docker. If you don't have much in your game (test data), it would be nice if you were able to export, then I could import into my own docker to test on, otherwise, I'll just try to reproduce it based on your picture and description.

**Comment by jeffg2k** [comment]
I tried to recreate the problem and haven't been able to do so yet.  However, looking at the trace stack, I've tried to make a change that I hope will fix it for you.

**Comment by MidasJade** [comment]
I'll give it a shot this weekend. Did you still want the game dump? There's nothing sensitive in it. Happy to dump if you need it.

**Comment by jeffg2k** [comment]
@MidasJade just wanted to check to see if you able to test the change https://github.com/moloch--/RootTheBox/commit/251e0847eba8dbdfd34ac3fd7c1f9ad996f9300b?

**Comment by MidasJade** [comment]
Hi Jeff. Sorry. I ended up being without Internet that weekend and have been buried since. I will circle back on it this weekend and let you know. Thanks for checking back!

**Comment by MidasJade** [comment]
Just tested, works great. Thank you!
