### ISSUE TITLE
Game stop - lock all users

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#393]
@moloch-- I see that when a game is started, it unlocks all users and when the game is stopped, it locks all users.  I wonder if this creates a couple problems if one were to stop / restart a game for any reason.

1) If you lock a user's account for other reasons, it will be unlocked if you start the game.
2) Users not yet registered would still be able to register, log on - they just wouldn't be able to play yet.

I wonder if it would be better to just deauth them instead of locking, which would address both issues.  But I guess it depends on the intent of stopping the game.  Alternatively, we could also suspend registration when the game is stopped, which would address the second issue.

**Comment by nunoguerreiro** [comment]
The same here.

**Comment by jeffg2k** [comment]
Doing some testing, deauth doesn't quite work the way I thought.  It closes the websocket connection, but doesn't disconnect their http session or log them out.  Part of the challenge is that stop game is used at the end when the timer runs out or the admin wants to stop the end game.  Again, I'm not sure if a lock is the best thing, but it does prevent the player from doing anything (maybe too much).  However, I don't believe it's needed to prevent players from continuing to submit answers (I think the stop game does that on it's own) and we may want to leave them logged in to see the scoreboard if it's not public, see their other stats, messages, account info, etc.  I could probably do something to redirect authenticated users as needed, such as not allowing anything beyond `/user/missions/` or other gameplay pages.

**Comment by jeffg2k** [comment]
I removed the user lock on game stop and replaced it with a new security decorator applied to pages that should be inaccessible when the game is stopped, but allow it on other pages such as home, settings, scoreboard, registration, etc. Users will not be disconnected, they just won't be able to access or submit to any game related content, such as missions, flag submissions, black market, etc.  Scoreboard and Registration can now be controlled independently from Stopping the game.
