### ISSUE TITLE
PDF downloading giving error 

### ISSUE THREAD

**Issue by cyberjatin** [moloch--/RootTheBox#394]
Hi have created one page under public folder called walk through but when i am giving downloding path to PDF, its downloading corrupt file, do i need to make changes in handler or somewhere else to do that ?

**Comment by jeffg2k** [comment]
If you're talking about placing a file in `files/game_materials/walk through` than no, there is nothing else you need to do.  If your file is corrupt, I expect there is something else wrong.  I'd verify the file on disk is valid and compare the hash on disk to the file hash downloaded - maybe compare them at a hex level to see the issue.  It may just be your browser's viewer is messed up or something.
