### ISSUE TITLE
XML import from CLI fails

### ISSUE THREAD

**Issue by anthturner** [moloch--/RootTheBox#397]
When using `--xml` with the `rootthebox.py` CLI tool, I get an error suggesting I have not provided any actions for it to take. Subsequently, the XML is not imported into the scoreboard. I tried this using docker-compose against the latest release build (3.5.5) and got:

```
root@9777df63d89b:/# /opt/rtb/rootthebox.py --xml=/tmp/juiceshop.xml
[*] Switching CWD to '/opt/rtb'
        No options specified. Examples: 'rootthebox.py --setup=prod' or 'rootthebox.py --start'
                --recovery      start the recovery console
                --restart       restart the server
                --save          save the current configuration to file
                --setup         setup a database (prod|devel|docker)
                --start         start the server
                --tests         run the unit tests
                --update        pull the latest code via github
                --version       display version information and exit
                --xml           import xml file(s)
                --config        configuration file location (default: files/rootthebox.cfg)
```

edit: just to disambiguate -- the `juiceshop.xml` file was generated from the `juice-shop-ctf-cli` tool and can be imported into the scoreboard _using the web UI_ without an issue.

**Comment by jeffg2k** [comment]
Thanks for the report - I pushed a fix.  That was an really old bug, introduced [Dec 3, 2014](https://github.com/moloch--/RootTheBox/commit/b7de1a0af79fd52fa3f82bad7a0100ade99a14bc)
