### ISSUE TITLE
forget password module error

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#402]
Hi there!
I have configured  forget password with `rootthebox.cfg` as mentioned in document. I have tried same mail credentials with flask application and there is working fine.  Also, I have tried with `Google SMTP `mail configuration but not working. It is showing trace back error. here I have attached image.
Could you possibly guide me?
![image](https://user-images.githubusercontent.com/38101321/93746674-285d4200-fc13-11ea-969a-5354e3712ece.png)

**Comment by jeffg2k** [comment]
I tested Gmail before I released and it worked correctly.  Make sure you're getting a Google application key for SMTP and not using your personal password as that won't work.  Can't recall if I used port 587 or 465, but you could try both.

**Comment by PunitTailor55** [comment]
I have tried with Gmail application Key and personal email server. I have
tried with Flask mail and it is working fine.

**Comment by jeffg2k** [comment]
Great - curious, what was the fix / cause?

**Comment by PunitTailor55** [comment]
Fixed from Database because token value is 25 characters, Also, cross verified with Email server somehow Gmail was block in configuration. I have changed to 255 and added as note in setup file.
