### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by reoca87** [moloch--/RootTheBox#403]
Hi all,

First of all, I would like to congratulate you on your great work. I'm using RootTheBox and I think it's great. But I think the Spanish translation could be a lot better. If it's okay with you, I'll volunteer to help with the translations.

Thank you very much in advance

**Comment by jeffg2k** [comment]
Happy to merge a pull request.

**Comment by jeffg2k** [comment]
I'm going to close this issue, since it was more of a question.  Happy to receive any spanish translations you have.  Look forward to seeing them. :)
