### ISSUE TITLE
SMTP Error: SMTP AUTH extension not supported by server

### ISSUE THREAD

**Issue by rderveloy** [moloch--/RootTheBox#405]
I get the following error when attempting to send a password reset email:
`python[9406]: File "/opt/CTF/RootTheBox/handlers/PublicHandlers.py", line 395, in post`
`python[9406]: smtpObj.login(options.mail_username, options.mail_password)`
`python[9406]: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/smtplib.py", line 697, in login`
`python[9406]: "SMTP AUTH extension not supported by server.")`

For context, line 395 in RootTheBox/handlers/PublicHandlers.py executes the login command on the smtpObject:
`smtpObj.login(options.mail_username, options.mail_password)`

I tired commenting out the mail server username & password in the roothebox.cfg, instead of just leaving it empty, but that does not solve the issue.  I also could not find an option to disable SMTP auth in the config file.

Commenting out line 395 in /RootTheBox/handlers/PublicHandlers.py does resolve the issue, and the emails go through, but is obviously not a long-term solution.

Thank you for all your hard work!  This really is a great project!

**Comment by jeffg2k** [comment]
I think that maybe just adding a try/except might be best to handle this, rather than a configuration option since I expect it's not that common to not authenticate.  If you could, try to replace your line 395 with this and let me know if it works ok for you.
```py
                try:
                    smtpObj.login(options.mail_username, options.mail_password)
                except smtplib.SMTPNotSupportedError as e:
                    logging.warn("SMTP Auth issue (%s). Attempting to send anyway." % e)
```

**Comment by rderveloy** [comment]
The try/except block seemed to fix the problem!  Thank you!
