### ISSUE TITLE
Promoting user to administrator broken

### ISSUE THREAD

**Issue by anthturner** [moloch--/RootTheBox#406]
Promoting an existing user (who is on a team) to administrator does a few destructive things:
- The user who was promoted is deleted (not visible in admins list nor on the team)
- The next user who signs up is promoted to admin automatically

This breaks our workflow entirely, as we can't have more than the one (base) admin on a game.

Repro:
- Install RtB (from git) as a docker container (using docker-compose)
- Apply juice-shop-ctf-cli configuration with the `--xml` app argument
- Log in as admin/rootthebox
- Create a team
- Register as a new user on created team
- As "admin" user, promote new user to Admin
- New user vanishes
- Sign up as a second new user
- Second new user has admin rights

**Comment by jeffg2k** [comment]
Thanks for finding that bug (two bugs actually).  I'll push up a fix shortly that will fix the user deletion.  The permission issue will apply to new builds.  Existing builds will require a db update, which I'll have to test a Alembic patch.  Essentially, the fk on the permissions table needs to have `ondelete=CASCADE` set.
