### ISSUE TITLE
Fix for 407 causing error in MissionsHandler.py

### ISSUE THREAD

**Issue by rstocks** [moloch--/RootTheBox#408]
The change to MissionsHandler.py as part of the fix for #407 appears to contain an error:

```
root@rtb:/var/ctf/RootTheBox# ./rootthebox.py --start
[E 201006 00:50:29 rootthebox:54] Error: invalid syntax (MissionsHandler.py, line 141)
root@rtb:/var/ctf/RootTheBox# 
```

**Comment by jeffg2k** [comment]
Hmm, I can't reproduce this with Python3 or Python2.  I'm not sure what it's having an issue with.  
Can you see if it likes `not box_id` instead of `box_id is None`.

**Comment by jeffg2k** [comment]
Thanks - Not sure how it happened, but the commit contained the old code and the new code, where my code base didn't.  Anyway.. fixed it.  :)

**Comment by rstocks** [comment]
Love your work :-) Many thanks for the speedy fixes.
