### ISSUE TITLE
Is there any option to confirm Email ID?

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#409]
Hi there!
Is there any option to confirm registered email account of user? Please take as suggestion or Question.

**Comment by jeffg2k** [comment]
By confirm, do you mean that during registration, it sends an email to the user to "activate" the account?  RootTheBox doesn't currently support that, but could probably tie it into the registration token system.  Email was primarily just additional data with the recent exception being a password reset.

**Comment by PunitTailor55** [comment]
Yes I am talking about exactly same. Or Admin get privilege to Domain filtration.

**Comment by jeffg2k** [comment]
Feature added: https://github.com/moloch--/RootTheBox/commit/9c6cd06adeb5e82dd9bde09bd7655bf615353771
