### ISSUE TITLE
Juice box error while parsing 

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#410]
Hi there,
For juice box installation, when I am importing `xml` file. It is giving a database error. I am running mysql database.

![image](https://user-images.githubusercontent.com/38101321/95501247-9fd9f200-09c5-11eb-86c5-d703b697644e.png)

**Comment by jeffg2k** [comment]
So far, I haven't been able to reproduce it on docker or my test instance. From the error, it's having an issue importing the unicode of ⭐️ emoji, which we included for the difficulty level. It doesn't look like a python error though. It looks like a database error. @PunitTailor55 when you created your database, did you set the correct character set? `create database rootthebox character set utf8mb4;`

**Comment by eljeffeg** [comment]
Fixed various xml imports since this issue, so going to close it unless we can reproduce or have further discussion.
