### ISSUE TITLE
Feature request: ability to hide users from the scoreboard

### ISSUE THREAD

**Issue by rstocks** [moloch--/RootTheBox#411]
We're using RTB as a way of running some basic education, and so have a bunch of generic accounts that we unlock and hand out as needed. It would be great if there was a way to also hide accounts from the scoreboard, so that accounts not currently in use don't show up.

**Comment by jeffg2k** [comment]
I've pushed a change that will hide locked accounts from the scoreboard when in player mode.  In team mode, if all members of the team are locked, it will also hide that team from the scoreboard.
