### ISSUE TITLE
Forgot Password Bug

### ISSUE THREAD

**Issue by tijldeneut** [moloch--/RootTheBox#421]
When filling in the "Password Reset" box, a new 64-character password is generated.
But the default database password column is of type varchar(32) resulting in a "Glitch in the Matrix".

Details (/var/log/syslog):
`[SQL: INSERT INTO password_token (created, user_id, value, used) VALUES (%s, %s, %s, %s)]
[parameters: (datetime.datetime(2020, 11, 6, 17, 39, 20, 807557), 3, 'b0261e7d6af88cf5b0456f59686199f097a2615818e539f0f7075b611c1e7292', 0)]`

Workaround:
`mysql rootthebox -e "alter table password_token modify value varchar(100);"`

Kind regards

**Comment by jeffg2k** [comment]
Thanks - didn't see it during testing as it doesn't apply to sqlite / docker and on MySQL the update script (alembic) for the database had the correct value.  So anyone upgrading would have been fine.   Our SQLAlchemy definition was wrong, so it only applied to new installs using something other than sqlite / docker.  So thanks for the report!
