### ISSUE TITLE
Is there any option that visible task for particular group of people?

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#423]
I have one question Is there any option that visible task for particular group of people? 
Else Task is for who can access above some x amount of points or X amount of money?
OR Task filtered by IP address?

**Comment by jeffg2k** [comment]
Levels can be unlocked by points/money.  Black Market items can also be purchased.  So the capability is there to expand on this idea.

**Comment by PunitTailor55** [comment]
Is there any way to contact your team?

**Comment by jeffg2k** [comment]
You could msg us on twitter, @moloch-- has posted his contact info [here](https://keybase.io/moloch).  GitHub just released a new built in Discussion feature (chat).  @moloch-- would have to enable it for the repo.  Alternatively, if you want to point to your contact info, I could reach out.

**Comment by PunitTailor55** [comment]
I have already sent message on [Twitter](https://twitter.com/vulnmachines).

**Comment by jeffg2k** [comment]
Resolved with Game Levels https://github.com/moloch--/RootTheBox/commit/2f52b90285c6dce983af371fcad810f89018b902
