### ISSUE TITLE
Frequent Logout issue

### ISSUE THREAD

**Issue by mr-1nc00r3ct** [moloch--/RootTheBox#424]
Hi, users facing frequent session logout issues. Any solution? When a user is exploring the options, missions/challenges, the user is getting redirected to login page for re-auth. This is happening frequently at irregular intervals. What could be the issue?

**Comment by jeffg2k** [comment]
I'd look at maybe browser extensions that block cookies.  Alternatively, memcached?  Perhaps the user could open the dev tools and see something in the console that clues us to the cause.
