### ISSUE TITLE
Stuck on login screen

### ISSUE THREAD

**Issue by pmantul240** [moloch--/RootTheBox#425]
I seen several issues already, people complaining, that providing correct password user is looped back to login screen.
I followed all recommendations and checked memcached - service running correctly. I can even telnet to memcached.

When I am deploying prepared Docker image to Heroku, everything working fine, however on my local mac or dev linux machine I am stuck in login screen.

I will be very appreciated for any suggestions, how I could try to solve this issue.

**Comment by jeffg2k** [comment]
Check that you're not running Python 3.9.  Python 3.8 is the highest version supported.  Other than that, I'd say it has to be a configuration issue.  I've run it on the Linux and Mac without issue (my dev environment is a direct Linux install).  Add the `--debug` option to the start parameters and let me know if there are any errors that you see.

**Comment by pmantul240** [comment]
Thank you for your quick reply and valuable advise, my problem was related to port mapping in docker-compose.yml for anyone else having issues `python3 rootthebox.py  --start --debug` will help you to understand, where exactly you have a problem with your dev environment.
