### ISSUE TITLE
Active Directory Integration

### ISSUE THREAD

**Issue by stevenp322** [moloch--/RootTheBox#429]
Is there anyway to integrate users with Active Directory? Such as when a new AD user is created it populates a user account within the RootTheBox CTF platform?

**Comment by jeffg2k** [comment]
Sorry, not third party auth is supported yet.  Easiest might be to just enable self registration and maybe email verification.

**Comment by askew** [comment]
@stevenp322, I've just created #433 which enables authentication with Azure Active Directory.

**Comment by jeffg2k** [comment]
@stevenp322 we've merged the PR, so take a look when you get a chance.  I'm going to close the issue, but feel free to reopen if more is needed.
