### ISSUE TITLE
Could you possibly integrate VPN for users?

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#436]
Hi guys! you are doing an amazing job for the platform. I would like to ask for functionality of VPN connection. VPN connection file create while registration after user can download that file and access the platform tasks. Another way, create VPN access file for tasks/lab based so only allowed people can access. Reference like HackTheBox and TryHackMe

**Comment by ekstrah** [comment]
> Hi guys! you are doing an amazing job for the platform. I would like to ask for functionality of VPN connection. VPN connection file create while registration after user can download that file and access the platform tasks. Another way, create VPN access file for tasks/lab based so only allowed people can access. Reference like HackTheBox and TryHackMe

Maybe, you could try "cloud access"? It is somewhat vpn access but less complicated to integrate with. It is just my thought

**Comment by jeffg2k** [comment]
Yeah, I'll have to think more how it would apply.  RTB is a CTF scoreboard platform, not an interactive range.  The CTF creator needs to build that out and setting up a VPN or Cloud Access for the game's range environment would be part of that.  If someone wanted to provide an OpenVPN file, they could share and link it in RTB, but not sure how to best generate or integrate those technologies with scoreboard yet.

**Comment by PunitTailor55** [comment]
> > Hi guys! you are doing an amazing job for the platform. I would like to ask for functionality of VPN connection. VPN connection file create while registration after user can download that file and access the platform tasks. Another way, create VPN access file for tasks/lab based so only allowed people can access. Reference like HackTheBox and TryHackMe
> 
> Maybe, you could try "cloud access"? It is somewhat vpn access but less complicated to integrate with. It is just my thought

Thanks for your suggestion. I have already integrated with same.
