### ISSUE TITLE
Documentation interval wrong (minutes -> milliseconds)

### ISSUE THREAD

**Issue by tijldeneut** [moloch--/RootTheBox#441]
In the documentation there is a an issue on [the page](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details) detailing the configuration values.
`bot_reward_interval`
and
`history_snapshot_interval`
are explained to be in minutes.
But according to
[https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.PeriodicCallback](https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.PeriodicCallback)
this should be in milliseconds.

Regards

**Comment by jeffg2k** [comment]
Thanks!  Updated wiki
