### ISSUE TITLE
mysql relationship warning when starting roothebox.py

### ISSUE THREAD

**Issue by menfin35** [moloch--/RootTheBox#442]
Hello
When I execute rootthebox.py --start, I get several warning message like the one below. It dos not prevent roothebox to run but it is making me worried. Does someone got the issue and found a solution ?

/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/relationships.py:3463: SAWarning: relationship 'Box.team' will copy column box.id to column team_to_box.box_id, which conflicts with relationship(s): 'Team.box' (copies box.id to team_to_box.box_id), 'Box.teams' (copies box.id to team_to_box.box_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning. (Background on this error at: http://sqlalche.me/e/14/qzyx)
  code="qzyx",

Thanks

**Comment by menfin35** [comment]
Additional info : I am using mariadb

**Comment by jeffg2k** [comment]
You happen to know what version of sqlalchemy you're  running?

**Comment by menfin35** [comment]
Root the box v3.8.1
SQL Alchemy v1.4.11
Tornado v6.1

The warnings do not prevent rtb to run. Everything is working but I have the warnings

Thanks for the help

**Comment by jeffg2k** [comment]
Just as an update, I have been able to reproduce this with the latest SQL Alchemy.  Just haven't quite figured out the best way to fix it.  We're using backref's on both sides, which is already a bidirection relationship.  So it's essentially saying you're doing this twice.  So either use `backref` on only one or use `back_populates` on both.  But I'm not quite sure how to do the lazy stuff with back_populates and not sure how best to remove one of the backrefs as I'm not that familiar with SQL Alchemy and I don't want to break it.  Maybe @moloch-- can take a look.

**Comment by jeffg2k** [comment]
Resolved with https://github.com/moloch--/RootTheBox/commit/2f52b90285c6dce983af371fcad810f89018b902
