### ISSUE TITLE
SWAT - 404 Glitch in the matrix

### ISSUE THREAD

**Issue by tetravaal4** [moloch--/RootTheBox#443]
Love RTB, and am running into an issue with SWATing.

Basically SWATing works one time, then for all users I start getting "404 - Glitch in the matrix"

RTB - 3.8.1
SQL Alchemy - 1.4.13
Tornado - 6.1

Replication steps
Setup server and game
Create user 1 and give 5000 points
Create user 2 and give 5000 points
User 1 SWATS user 2 - and it works
Delete both users.
Create 2 more users and attempt to swat.. 
Error 404.

Below are my logs that are semi redacted.
May 03 19:51:46 RTB2 rootthebox.py[5577]:     HTTPServerRequest(protocol='https', host=removed’, method='GET', uri='/swat', version='HTTP/1.1', remote_ip='REMOVED')
May 03 19:51:46 RTB2 rootthebox.py[5577]:     Traceback (most recent call last):
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1702, in _execute
May 03 19:51:46 RTB2 rootthebox.py[5577]:         result = method(*self.path_args, **self.path_kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 188, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 156, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/handlers/UpgradeHandlers.py", line 346, in get
May 03 19:51:46 RTB2 rootthebox.py[5577]:         self.render_page()
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/handlers/UpgradeHandlers.py", line 396, in render_page
May 03 19:51:46 RTB2 rootthebox.py[5577]:         errors=None,
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 863, in render
May 03 19:51:46 RTB2 rootthebox.py[5577]:         html = self.render_string(template_name, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1012, in render_string
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return t.generate(**namespace)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 362, in generate
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return execute()
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "upgrades/swat_html.generated.py", line 109, in _tt_execute
May 03 19:51:46 RTB2 rootthebox.py[5577]:         _tt_tmp = target.team.name  # upgrades/swat.html:74 (via main.html:32)
May 03 19:51:46 RTB2 rootthebox.py[5577]:     AttributeError: 'NoneType' object has no attribute 'name'
May 03 19:51:46 RTB2 rootthebox.py[5577]: [E 210503 19:51:46 BaseHandlers:197] Request from REMOVED resulted in an error code 500:
May 03 19:51:46 RTB2 rootthebox.py[5577]:     Traceback (most recent call last):
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1702, in _execute
May 03 19:51:46 RTB2 rootthebox.py[5577]:         result = method(*self.path_args, **self.path_kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 188, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/libs/SecurityDecorators.py", line 156, in wrapper
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return method(self, *args, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/handlers/UpgradeHandlers.py", line 346, in get
May 03 19:51:46 RTB2 rootthebox.py[5577]:         self.render_page()
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/home/rtb/RootTheBox/handlers/UpgradeHandlers.py", line 396, in render_page
May 03 19:51:46 RTB2 rootthebox.py[5577]:         errors=None,
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 863, in render
May 03 19:51:46 RTB2 rootthebox.py[5577]:         html = self.render_string(template_name, **kwargs)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1012, in render_string
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return t.generate(**namespace)
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 362, in generate
May 03 19:51:46 RTB2 rootthebox.py[5577]:         return execute()
May 03 19:51:46 RTB2 rootthebox.py[5577]:       File "upgrades/swat_html.generated.py", line 109, in _tt_execute
May 03 19:51:46 RTB2 rootthebox.py[5577]:         _tt_tmp = target.team.name  # upgrades/swat.html:74 (via main.html:32)
May 03 19:51:46 RTB2 rootthebox.py[5577]:     AttributeError: 'NoneType' object has no attribute 'name'
May 03 19:51:46 RTB2 rootthebox.py[5577]:

Thanks!

**Comment by jeffg2k** [comment]
Thanks for the report - pushed a fix.
