### ISSUE TITLE
Automated creation of multiple teams

### ISSUE THREAD

**Issue by veryredheaded** [moloch--/RootTheBox#444]
Hi, I was wondering if there is a way (doesn't need to be via GUI) to create an arbitrary number of teams - say 20 - without having to create them 1 by 1? 

Thank you in advance!

**Comment by jeffg2k** [comment]
Yes, @anthturner recently contributed something that does that https://github.com/moloch--/RootTheBox/pull/432
CLI args:
* --generate_teams=N ... Generates N numbered teams. e.g. "Team 1", "Team 2" ...
* --generate_team="My Team", "Their Team", "Another Team" ... Generates teams from a comma-delimited list of names
* --add_admin="handle handle@contoso.com passwordpassword123" ... Generates admins from a comma-delimited list of strings, formatted as seen in the example here.

**Comment by veryredheaded** [comment]
Awesome, thanks for the quick response! Is there also a way to limit the number of players per team?

**Comment by jeffg2k** [comment]
Not yet, but that's a nice feature request.
