### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by RichardPhilRoy** [moloch--/RootTheBox#445]
Hi, I'm having errors when installing rootthebox. I'm installing it on Ubuntu 18.04
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pB9U30/PyMySQL/setup.py", line 6, in <module>
        with open("./README.rst", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pB9U30/PyMySQL/
Ignoring tornado: markers 'python_version < "3.0"' don't match your environment
```
and this 
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j_n5srfn/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j_n5srfn/cryptography/
```

**Comment by jeffg2k** [comment]
Can you explain your environment a bit more?  Python version, Tornado version.  Did you run `sudo ./setup/depends.sh`?
The Wiki should be accurate as far as I'm aware.  https://github.com/moloch--/RootTheBox/wiki/Installation but I'd recommend Python 3.8.  The depends should install the needed components for rust.

**Comment by RichardPhilRoy** [comment]
I'm trying it on Ubuntu Server 18.04 LTS, I started the installation by running ```sudo ./setup/depends.sh```. I didnt installed python manually the bash script installed it.

**Comment by jeffg2k** [comment]
The bash script doesn't install Python, so you're probably just running with the default of Ubuntu.  It's running Python 2.x, which is increasingly more difficult to continue support on.  RTB should still work fine, but all our dependency libraries have moved on.  I've updated the depends / requirements.txt to hopefully account for the dependencies that no longer support Python 2.x by specifying the latest version where they did support it.  So you can give that a try or update to Python 3.x

**Comment by RichardPhilRoy** [comment]
Ok thanks.
