### ISSUE TITLE
MySQL error after running --update flag

### ISSUE THREAD

**Issue by stevenromero02** [moloch--/RootTheBox#446]
I have received the following error after updating an installation that we used last October (used rootthebox.py --update):

[I 210623 18:16:38 __init__:266] Checking for Database Updates...
[E 210623 18:16:38 rootthebox:54] Error: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'password@127.0.0.1' (22)")
      (Background on this error at: http://sqlalche.me/e/14/e3q8)

I have also tried to re-run depends.sh to see if I was missing some dependency.  If the error is difficult to fix, is it possible to extract the contents of the database to use in a fresh RTB installation?

**Comment by jeffg2k** [comment]
The formatting of your hostname looks odd.  I wouldn't think it would have the username in there for this error, as that's specified in its own config entry.  And password seems like an odd user account.  So I'm confused about what's happening there.  I can't reproduce this error when I try it and I'm not aware of any changes that would break the MySQL connection.

As for exporting, we do have built in exporting of an XML, but it requires the database connection.  However, you should be able to copy out that database or reuse it.  It appears to be a connection problem, so if you resolve the connection issue, but reinstalling RTB or fixing the issue, it should work.

**Comment by PunitTailor55** [comment]
It is working fine. Please check  your mysql hostname.

**Comment by jeffg2k** [comment]
@stevenromero02 Did you ever get this resolved?  Looking back at my comment and the odd username.  I have seen this type of thing before when the mysql password has an `@` symbol in it.  SQLAlchemy reads it as a delimiter #448 I plan to look at it soon and implement a check / fix.  Not sure if it will address your issue though.

**Comment by stevenromero02** [comment]
I did manage to resolve the issue a few weeks ago by removing the @ symbol from the password.  I wasn't aware that the symbol was a delimiter, but I figured something must be wrong with the password since that is where the error was occurring.  Thanks for checking back on this.
