### ISSUE TITLE
Mysql error while installing RTB

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#448]
Hey guys I am using `ubuntu 20.4 ` version and Mysql `Server version: 8.0.26-0ubuntu0`
While installing RTB in new machine it is showing an error. 

I have tried with database connection string, it is working fine.

I have tried with older version the same error is coming. please help me out

![image](https://user-images.githubusercontent.com/38101321/127165175-b01cfad4-e9f6-49db-a288-c95ca647a126.png)

**Comment by jeffg2k** [comment]
I'm surprised to see the `5500@` specified as part of the "server host".  Is 5500 the username?  Your config should look something like this:
```
# [ Database ]
sql_dialect = "mysql"
sql_database = "rootthebox"
sql_host = "127.0.0.1"
sql_port = 3306
sql_user = "rtb"
sql_sslca = ""
sql_password = "rtb"
log_sql = False
```

**Comment by PunitTailor55** [comment]
Digits are related to my password. I am also surprised why it is taking password rather than username.

**Comment by jeffg2k** [comment]
I think we identified the issue as being an `@` symbol used in the mysql password, which the Python MySQL or SQL Alchemy is parsing as a delimiter.  Will follow up with some code that warns a user if this is detected.
