### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Amine1980F** [moloch--/RootTheBox#451]
I want to install RTB in Ubuntu 20.04 TLS, python is 3.8.10. When I run sudo ./setup/depends.sh, I find this issue:

ERROR: Could not find a version that satisfies the requirement python_version<'3.0' (from versions: 0.0.2)
ERROR: No matching distribution found for python_version<'3.0'
Please could you help? Thank you.

**Comment by jeffg2k** [comment]
Looks like it might be getting stuck on installing the python `requirements.txt`.  The first line checks to see the python version and if it's less than 3.0, it installs Tornado 5.x.  If it's greater than/equal to 3, it installs the latest Tornado.  I wonder if you might already have Tornado 5.x installed.  Normally, it would see you have python3 and skip right over this line.

Try to run it manually
`pip3 install -r ./setup/requirements.txt --upgrade`

If that still fails, try to remove that first line that does the version compare for Tornado or any other lines that compare 3.x vs 2.x.

**Comment by jeffg2k** [comment]
https://github.com/moloch--/RootTheBox/wiki/Installation#application-configuration

**Comment by Amine1980F** [comment]
Thank you very much.
Please I found this in the server section;
# [ Server ]
origin = "ws://localhost:8888"
listen_port = 8888
listen_interface = "0.0.0.0"
session_age = 3600
x_headers = False
ssl = False
certfile = ""
keyfile = ""
admin_ips = ['127.0.0.1', '::1']
autoreload_source = True
webhook_url = None


Please, how to do the configuration? Thank you.

**Comment by jeffg2k** [comment]
https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details
