### ISSUE TITLE
JQuery question

### ISSUE THREAD

**Issue by nametovski** [moloch--/RootTheBox#455]
Hello, 

Is there plan to upgrade the shipped jquery version? Last scan showed that the current one is vulnerable.

Cheers

**Comment by jeffg2k** [comment]
Unfortunately, jQuery 3.x is not compatible with the Bootstrap used in RTB.  Once Bootstrap is upgraded, we can likely update jQuery.  But I'm not sure when that will happen, so we're running the latest jQuery 2.x.  There is an open request to upgrade Bootstrap if you want to have a go #74
