### ISSUE TITLE
Teams issue

### ISSUE THREAD

**Issue by Hansolo32** [moloch--/RootTheBox#461]
Is there a way to stop teams from sharing answers? We have 4 teams of 8 people but we want each person to have to input the answer individually because some boxes are not team-based. Is this possible with a configuration that I'm not seeing?

**Comment by jeffg2k** [comment]
Player mode would require them to each supply their own flag and Team mode requires one flag for the entire team.  We don't have a hybrid mode yet where some flags are team mode and others are player mode.  I am hoping to include a group scoreboard at some point #161.

**Comment by jeffg2k** [comment]
Note that I don't think you can switch from team mode to player mode on the fly.  Essentially player mode is using team mode with a restriction of 1 player per team.
