### ISSUE TITLE
Export users/teams & scores

### ISSUE THREAD

**Issue by smoetsie** [moloch--/RootTheBox#462]
Hi,

Is it possible to also export the users/teams and their scores to an XML file? Because when there are gonna be updates on the repository or the docker container needs to be stopped, the users and scores will be lost.

**Comment by jeffg2k** [comment]
There is not an export / import, but there is a json feed of the players and scores which is part of the CTFTime integration.  You could also directly backup the files directory.  However, this should be persistent in the docker container.  A volume is created on the files directory and those files should be ignored in a normal image update.  Starting and stopping the container should also not remove those files.
