### ISSUE TITLE
Player name: accept all characters

### ISSUE THREAD

**Issue by Linkid** [moloch--/RootTheBox#463]
Hi! In the registration form, only some characters are accepted for the player name field: [`pattern="^[a-zA-Z0-9 ]{3,64}$"`](https://github.com/moloch--/RootTheBox/blob/03352db2494732537cea59eb505089d83143b371/templates/public/registration.html#L122). However, in the model, the `name` column is of type [`Unicode`](https://github.com/moloch--/RootTheBox/blob/03352db2494732537cea59eb505089d83143b371/models/User.py#L78). Then, the player should be able to use all unicode characters.

**Comment by jeffg2k** [comment]
It should be doable and was likely added to minimize attack vectors.  I believe it's checked client and server side.  But this does limit use for multi-language support and emojis.

**Comment by jeffg2k** [comment]
Doing a little research, surprisingly javascript natively doesn't support unicode regex and thus the pattern input.  Python similarly seems difficult.  There is a library for javascript and I'm looking into that.

**Comment by eljeffeg** [comment]
Updated the pattern for unicode words.  So it should now have multi-language support for the player name field and team motto.  I wasn't quite able to get emoji regex filtering to work in python, so will have to revisit that at some point if there is a need.
