### ISSUE TITLE
Storage volume erased after the containers getting down

### ISSUE THREAD

**Issue by rahimbtc** [moloch--/RootTheBox#464]
hello ;
why the storage volume (ex. members and teams) getting deleted after the containers getting down ! 
how to avoid that ?

**Comment by jeffg2k** [comment]
@garanews you know what could be causing this?  I'm still learning the particulars of docker.

**Comment by garanews** [comment]
The db file is created under /opt/rtb of webapp container.
The mapped volume instead is mapping /opt/rtb/files so just a subfolder.
If rebuild image, then db is deleted, but if you just stop and start container, the file is not deleted and data should not being deleted. 
I have just tried and can confirm this.

**Comment by jeffg2k** [comment]
That makes sense.. when using a sqlite database, we should be creating it under the files directory.

**Comment by jeffg2k** [comment]
@rahimbtc I pushed up a fix https://github.com/moloch--/RootTheBox/commit/8d791068fdee1507d7f5cfa2340d161e80014ccc that should address future docker builds.  For existing builds, move the `rootthebox.db` file into the `files` directory.  Then update the `rootthebox.cfg` and set the `sql_database` option to `files/rootthebox.db`.
