### ISSUE TITLE
Scoreboard empty

### ISSUE THREAD

**Issue by smoetsie** [moloch--/RootTheBox#471]
Hi,

When I open the scoreboard page, the charts are empty and the history keeps loading. I cloned the latest version of Root the Box but I still got the problem... I have tested it with users completing flags but it stays empty.

![image](https://user-images.githubusercontent.com/57101843/146205301-3b9ec5d6-afc5-42be-b482-dc0a0d5198fc.png)

**Comment by jeffg2k** [comment]
I don't have this issue in my dev environment.  Couple things you could do to help figure this out...  Open up the dev tools in the browser and see if there are any errors in the console.  Also, look at the running terminal for RootTheBox and see if we have any error messages.  Would be helpful to put it in debug mode that could give more info.

**Comment by smoetsie** [comment]
I found out it was because of nginx, the websockets couldn't be found. Now I followed the wiki for the nginx deployment and got the nginx.conf and nginx_vhost_rtb.conf just as the example but now i get these errors:

![image](https://user-images.githubusercontent.com/57101843/146342926-3557510d-dcaf-49e4-9028-05b7db0f6c6f.png)


and this is my config for /static/ just like the example:
![image](https://user-images.githubusercontent.com/57101843/146343049-46a61fbc-01b2-4071-8b1f-c3eae70dba3c.png)

**Comment by smoetsie** [comment]
okay so I added a proxy_pass to the /static/ locations and now it works, but got a different error when loading the scoreboard:

![image](https://user-images.githubusercontent.com/57101843/146347950-f0339aa0-6793-409a-85fe-e795716eda94.png)

**Comment by jeffg2k** [comment]
One thing to verify when using a proxy is the [origin](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#origin) value in config.  It should reflect the public url as `ws://...../static`.  Proxy issues are almost always a configuration issue from my experience.

Take a look at this StackOverflow [question](https://stackoverflow.com/questions/22183859/javascript-err-content-length-mismatch)  It seems to match your error and describe your proxy situation.

**Comment by christiaanvaken** [comment]
That's what we did, with the origin value, but it looks like the rootthebox.cfg file is overridden everytime.

**Comment by jeffg2k** [comment]
I fixed the issue with overwriting the rootthebox.cfg

**Comment by smoetsie** [comment]
Thanks! 

Also, adding `proxy_buffering off;` for all the locations in the nginx config, fixed the issue and now the scoreboard is working!
