### ISSUE TITLE
Start a new Game

### ISSUE THREAD

**Issue by thehybrid-at** [moloch--/RootTheBox#472]
Hello, 

This might sound stupid question,  but how do I start an entire new game? for some reason I find it in the UI.

In the configuration page from Admin account, I can only see "Game Name" which I modify the current Game name.

But How can I delete the old game and start a new one with new boxes and flags?

Thanks.

**Comment by jeffg2k** [comment]
Game Management Menu -> Flags / Boxes / Corp
https://github.com/moloch--/RootTheBox/wiki/Game-Setup-Tutorial
