### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by ivancleef** [moloch--/RootTheBox#48]
So I'm going to be using Root The Box to host a CTF event at my college in the spring semester.
Just have a few questions, if you can answer them!
1. When assigning an IP to a "box" the box quite literally is a different computer on the network, such as a Windows XP or 7 computer, correct? If not, how would this be done?
2. When assigning a flag to that box, does the file actually get sent to the box somehow, or do I have to put it on the computer manually?
3. Do you have any suggestions for isolating the game from the rest of the college's network? The IT department was concerned with people hacking the wrong computers and screwing up the entire network.
Thanks!

**Comment by tim-skillcafe** [comment]
An alternative way for isolation from college networks:  Put the CTF architecture behind Guacamole, so that everyone has to use a browser to access the network.  You can do some interesting things with Guacamole v1.2, especially if you're willing to mess with its database.
