### ISSUE TITLE
User is getting logged out too frequently

### ISSUE THREAD

**Issue by mr-1nc00r3ct** [moloch--/RootTheBox#485]
Hi,

I have deployed the RTB on ec2 and routed it thru Cloudflare. Everything was working for a week and suddenly, all the users and admins facing issues of getting logged out too frequently. Can you please check and assist as we have our registrations open in 24 hours?

**Comment by eljeffeg** [comment]
Take a look at the [session_age](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#session_age) in the config.  Default is 48hrs (2880 min).  Other than that.. could be a memcached / proxy issue, but I don't see anything obvious in the code that might cause that.

**Comment by eljeffeg** [comment]
Also make sure the origin is set up correctly.

**Comment by mr-1nc00r3ct** [comment]
Thank you for your quick response. I am using the default values for session_age and for origin I have given only the domain name now (no port). Let me check for some time and if the issue get resolved or any workaround identified, I will update you

**Comment by mr-1nc00r3ct** [comment]
Hi, The issue has been identified from the debugging and fixed, the cause of the issue is cloudflare as the caching is enabled certain pages are being loaded from various IPs of cloudflare subnet and due to which the person is getting logged out. Thank you for your support.
