### ISSUE TITLE
Need a confirmation of the UI issue

### ISSUE THREAD

**Issue by mr-1nc00r3ct** [moloch--/RootTheBox#486]
Hi,

There are almost 40 teams registered and once I open the teams page, I can only see a fixed number of team names on the left side and no scrolling. It's fixed as per the display size and getting varied upon zooming in/out of the browser. Is this an issue that happened only with my implementation?

**Comment by eljeffeg** [comment]
On the scoreboard, you'll probably only see a team once they score points.

On the teams page, I'm not aware of a scrolling issue.  Maybe open the browser dev panel and see if there is a JavaScript error.  I'll take a look when I have a moment.

**Comment by eljeffeg** [comment]
Fixed in the upcoming 3.12.0 release
