### ISSUE TITLE
Error loading web with admin account

### ISSUE THREAD

**Issue by blu3car** [moloch--/RootTheBox#490]
I have Root the box installed on a debian machine and everything has worked correctly. But for a few days when I log in with an administrator account, the web panel is slow until it gives a 404 error. On the other hand, if I log in as a normal user, everything works correctly. I've updated the static folder which has changes from 4 days ago, but it's still slow.

**Comment by blu3car** [comment]
I copy log output (/admin/gitstatus delays 130 seconds):

May 17 10:58:30 p1 rootthebox.py[588]: [I 220517 10:58:30 web:2239] 304 GET /scoreboard/ajax/timer (84.77.99.91) 0.76ms
**May 17 11:00:40 p1 rootthebox.py[588]: [I 220517 11:00:40 web:2239] 304 GET /admin/gitstatus (84.77.99.91) 130150.21ms**
May 17 11:00:40 p1 rootthebox.py[588]: [I 220517 11:00:40 web:2239] 101 GET /connect/notifications/updates (84.77.99.91) 1.89ms
May 17 11:00:41 p1 rootthebox.py[588]: [I 220517 11:00:41 web:2239] 200 GET /admin/view/game_objects (84.77.99.91) 163.44ms
May 17 11:00:41 p1 rootthebox.py[588]: [I 220517 11:00:41 web:2239] 101 GET /connect/notifications/updates (84.77.99.91) 0.90ms

**Comment by blu3car** [comment]
Resolved
I have commented one line in this file static/js/pages/admin/home.js
  //updateGitStatus();

**Comment by eljeffeg** [comment]
Thanks, I'll look at making that asynchronous.

**Comment by eljeffeg** [comment]
Commit https://github.com/moloch--/RootTheBox/commit/69bf12fc351ead8ebf142059f8a37cedc9ffea33 should help.
