### ISSUE TITLE
Base Url on Nginx Proxy service. 

### ISSUE THREAD

**Issue by DoloresPromesas** [moloch--/RootTheBox#491]
I was wondering if there is a way without messing around with the code to set a base url defined in the webapp...

My scenario is a server with different web applications served with Docker. I have an nginx proxy that serves the applications when accessing `https://myserver/rtb/` I receive a shower of 302 errors since it is looking for paths like `https://myserver/static/` etc... and cannot find them...

Someone who can help me with this?

Thanks in advance.

**Comment by eljeffeg** [comment]
That would probably be difficult as I expect there are a lot of absolute paths based on the root of the webserver.  Another approach would be to assign it a separate hostname rtb.myserver.com, which the nginx can proxy to the correct backend.

**Comment by DoloresPromesas** [comment]
We will try it, cheers!
