### ISSUE TITLE
configuration export attempt results in export xml error

### ISSUE THREAD

**Issue by torrycrass** [moloch--/RootTheBox#495]
RTB version is latest version.

![image](https://user-images.githubusercontent.com/38197983/177666169-8fc68159-a557-4abb-9abe-07d637861900.png)

When choosing "Export XML" leaving the game play settings export checked or unchecking it and clicking "Download File" the following error results.

![image](https://user-images.githubusercontent.com/38197983/177666079-870998a4-5715-4d2f-8fcb-457c32157f18.png)

Developer tools indicates a 500 error.

![image](https://user-images.githubusercontent.com/38197983/177666455-2a33b5d6-2e4b-47d6-ad03-bac1fc47d634.png)

To the best of our knowledge all other items are working.

**Comment by eljeffeg** [comment]
Pushed a fix - issue was introduced with the new disable a box feature. bool -> str(bool)
