### ISSUE TITLE
Unable to locate in DB game status

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#496]
Please could someone share with me how I can either use rootthebox.py or the sqlite3 db query to find the value of the game status and registration status? I have crawled through the .cfg file and the .db file looking for the setting, but can't seem to locate where it's stored.

I have a webpage frontend to access a few RTB's and want to show the current game and registration state on that page. Be nice to have an API ;-)

Thanks

**Comment by eljeffeg** [comment]
I added a request for getting the game and registration status via `/status`

**Comment by PJNorrisS1** [comment]
Thanks - so I wasn't going mad then - it's not stored in the DB?

**Comment by eljeffeg** [comment]
No, you're correct.  There is an autostart option that will set the game running, but yeah, they're just in-memory variables that don't survive a restart.

**Comment by PJNorrisS1** [comment]
FYI - I did a git pull for one of my docker instances, and it has started up, but can't get access to it at moment. I've double checked everything, including restoring my docker-compose.yml file that gets overwritten on the pull (even after doing a git stash). I did a docker compose build too before bringing it back up - any hints? Do I need to do a db update on something?

**Comment by eljeffeg** [comment]
The update of the database should be automatic via alembic.  You could view the docker logs to see what's happening.  
```
$ sudo docker ps
$ sudo docker logs container_id
```

**Comment by PJNorrisS1** [comment]
| [E 220712 18:43:42 rootthebox:54] Error: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL
`  |     [SQL: ALTER TABLE flag ADD COLUMN _locked BOOLEAN NOT NULL]

**Comment by eljeffeg** [comment]
I pushed an update to the Alembic script to set a default when adding the `_locked` column.

**Comment by PJNorrisS1** [comment]
Just done a pull, docker build and then ran docker compose up (output to the screen and not daemon) - same error.

`rtb-me-webapp-1 exited with code 1
rtb-me-webapp-1     | [I 220712 19:10:46 rootthebox:262] Environment Configuration (SQL_DIALECT): sqlite
rtb-me-webapp-1     | [I 220712 19:10:46 rootthebox:1074] Running Docker Setup
rtb-me-webapp-1     | [I 220712 19:10:46 ConfigHelpers:15] Saving current config to: files/rootthebox.cfg
rtb-me-webapp-1     | [*] Switching CWD to '/opt/rtb'
rtb-me-webapp-1     | [*] 19:10:46 : Creating the database ...
rtb-me-webapp-1     | [I 220712 19:10:46 rootthebox:262] Environment Configuration (SQL_DIALECT): sqlite
rtb-me-webapp-1     | [I 220712 19:10:47 __init__:267] Checking for Database Updates...
rtb-me-webapp-1     | [I 220712 19:10:47 migration:204] Context impl SQLiteImpl.
rtb-me-webapp-1     | [I 220712 19:10:47 migration:207] Will assume non-transactional DDL.
rtb-me-webapp-1     | [I 220712 19:10:47 migration:618] Running upgrade cd4d09aa9c68 -> 83f862086ff0, add flag lock
rtb-me-webapp-1     | [E 220712 19:10:47 rootthebox:54] Error: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL
rtb-me-webapp-1     |     [SQL: ALTER TABLE flag ADD COLUMN _locked BOOLEAN NOT NULL]
rtb-me-webapp-1     |     (Background on this error at: https://sqlalche.me/e/14/e3q8)
rtb-me-webapp-1 exited with code 1`

**Comment by eljeffeg** [comment]
Hmm, still says it's trying to add a default of Null.  The last update should have fixed that.  The file in question is this one:
`RootTheBox/alembic/versions/83f862086ff0_add_flag_lock.py`

It uses Alembic via SQLAlchemy to run what you're seeing.
If you want to try a few things... make sure that default value is there.  Another option would be to remove both the nullable and default, see if that forces the default if we're not specifying nullable.

**Comment by eljeffeg** [comment]
Nice - thanks for working through the issue with me.  I've pushed up a change with those removed.
