### ISSUE TITLE
Checking rootthebox.py

### ISSUE THREAD

**Issue by oreodejobi** [moloch--/RootTheBox#497]
I'm trying to setup RootTheBox using the tutorial on github. when i got to rootthebox.py --update, it says command not found. kindly help out.

**Comment by eljeffeg** [comment]
I tested it on my dev machine and it worked.  Hmmm. Maybe try `python3 ./rootthebox.py --update` to make sure it's calling all the right things

**Comment by oreodejobi** [comment]
it worked, Thanks

**Comment by oreodejobi** [comment]
> I tested it on my dev machine and it worked. Hmmm. Maybe try `python3 ./rootthebox.py --update` to make sure it's calling all the right things

./rootthebox.py --start keeps saying cannot connect to database with any available driver. verify correct username and password in rootthebox.cfg.
Any help?

**Comment by eljeffeg** [comment]
The easiest setup is to use [Docker](https://github.com/moloch--/RootTheBox/wiki/Docker-Deployment).  On a direct install, easiest would be to use SQLite.  But sounds like you're going the MySQL or Postgres route, which is a bit more tricky since there is more configuration and different versions of Linux and new drivers can cause yet unknown issues.

First thing would be to make sure your database, let's say MySQL, is connecting properly from the host.  Login with the newly created account `mysql -u rootthebox -p`.  Once verified (and make sure there is no `@` symbol in your password), make sure your rootthebox.cfg has the proper [database settings](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#database).

If all looks good, then it's likely a python driver issue. So I'd rerun `pip3 install -r ./setup/requirements.txt`, which is normally done in by the `depends.sh`, but with all the stuff being installed, maybe something produced an error such as the package couldn't be found.

**Comment by oreodejobi** [comment]
okay thanks, i tried all this still the same. can i just uninstall the mysql and intsall it again, then start afresh?

**Comment by eljeffeg** [comment]
Yeah, you can do that.

**Comment by oreodejobi** [comment]
> 

create user '<user>'@'localhost' identified by '<password>';

Hello, will i remove the <> for both? or i will create my user and password using the <>

**Comment by eljeffeg** [comment]
Remove them

**Comment by oreodejobi** [comment]
> Remove them

okay thanks, i have tried eveything, when i run ./rootthebox.py --start, i'm still getting can't connect to database with any available driver. verify correct username and password in rootthebox.cfg and db dep. 
Any other help?

**Comment by eljeffeg** [comment]
Could try a different database, like SQLite.

**Comment by oreodejobi** [comment]
> Could try a different database, like SQLite.

Hello, Thanks for your help, i was able to resolve it. but now it's showing Error Module 'collections' has not attribute 'mutablemapping'. i checked google and i saw some codes, but under which file will i put those codes? kindly assist. Thanks

**Comment by eljeffeg** [comment]
Docker makes a lot of this pretty seamless.  It sounds like you're using Python 3.10.  RootTheBox only supports up to Python 3.8.x as we haven't removed all the backward compatibility with Python 2.7.x yet which breaks RTB in Python 3.9 and greater.  But I'll add the code to deal with the MutableMapping which changed in 3.10, but that likely won't be the only error you'll get with that version.

**Comment by oreodejobi** [comment]
> ableMapping which changed in 3.10, but that likely won't be the only error you'll get with that version.

i installed python3.8 already, i uninstalled 3.10 but i don't know why it's still on ubuntu. if i check python3 --version it shows 3.10 but python3.8 --version shows for 3.8. i don't know what to do to completely remove 3.10

**Comment by eljeffeg** [comment]
Few ways you could do it, but you could just run `python3.8 ./rootthebox.py --start` or better, use a [virtual environment](https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/).

**Comment by oreodejobi** [comment]
Thanks, i just did, but it says traceback (most recent call last): file ./rootthebox.py, line 29, in module import nose . No module named 'nose'

i tried to pip install nose, it says it's already installed, i tried to use python3.8 pip install nose, it says python3.8 cant open file pip {no such file}. How do i install pip in python3.8?

**Comment by eljeffeg** [comment]
Try `python3.8 -m pip install`

**Comment by oreodejobi** [comment]
> Try `python3.8 -m pip install`

Hello, i used sudo apt install python-pip and it went through but it installed pip2. i uninstall python3.10 and made 3.8 default using update-alternatives. i proceeded and it says tornado and import nose not found. i used pip2 install tornado and nose, it installed but it's still showing me line 34 in module NoModuleNamed tornado not found when i try to use ./rootthebox.py --save. Kindly help out.

**Comment by oreodejobi** [comment]
i was able to solve it, now ./rootthebox.py --start now says Error: (MYSQLdb.OperationalError) (1060, duplicate column name '_original_value'")
[SQL: ALTER TABLE flag ADD colunm _original_value Integer]

**Comment by eljeffeg** [comment]
Sounds like it's trying to recreate the database.  Not sure what to do there.  Since you're having so many problems with setup, I think your best course would be to use Docker.  It's pretty simple to install and rootthebox will just work as everything is already setup in the container.  Runs on any OS.

**Comment by oreodejobi** [comment]
> Sounds like it's trying to recreate the database. Not sure what to do there. Since you're having so many problems with setup, I think your best course would be to use Docker. It's pretty simple to install and rootthebox will just work as everything is already setup in the container. Runs on any OS.

oh okay thanks. but do you have any link on how to install docker? cos i used pip to install it earlier.

**Comment by oreodejobi** [comment]
I have figured it out. Thanks.
So you mean after installing the docker on ubuntu, i will just restart the rootthebox step by step setup??

**Comment by eljeffeg** [comment]
No need to setup anything really.  You navigate to the rootthebox directory and run `docker compose up`

**Comment by eljeffeg** [comment]
Here are the instructions https://github.com/moloch--/RootTheBox/wiki/Docker-Deployment

**Comment by oreodejobi** [comment]
oh okay thanks. I'm setting it up RN.
But i want to create a new working environment.

**Comment by oreodejobi** [comment]
Done with the setup and everything worked out well with the docker. Thanks for your help. 
How do i setup the game cos i have questions i wanna input for beginner, intermediary and advanced. Any suggestion please?
Thanks once again.

**Comment by eljeffeg** [comment]
For RTB setup, see the [Game Setup Tutorial](https://github.com/moloch--/RootTheBox/wiki/Game-Setup-Tutorial)

In general, I recommend these as good reads:
* [The Many Maxims of Maximally Effective CTFs](https://web.archive.org/web/20201212081922/http://captf.com/maxims.html)
* [PPP - Suggestions for running a CTF](https://github.com/pwning/docs/blob/master/suggestions-for-running-a-ctf.markdown)
