### ISSUE TITLE
Dependent Flag not showing correctly

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#500]
When editing flags, if there is a dependency on a previous flag, there is a padlock next to the flag name. If you highlight the flag, it correctly shows the right dependency.

However, if you edit the flag, and scroll down to the Dependent flags, it's blank.
![image](https://user-images.githubusercontent.com/106666319/181057458-512bdf77-3a8f-4468-b19a-280f1618f00f.png)

**Comment by eljeffeg** [comment]
I'm not able to reproduce this.  What happens if you select a different dependency, save, and then reselect it.  This is all client side code in `game_objects.js` if you want to look at it.

**Comment by PJNorrisS1** [comment]
Hi, if I select a dependency, it saves. But when opening it again, still selects the 'blank' field. However, if I hover over the padlock on the flag, it correctly identifies the dependency and in the game it works... just not in the edit field.

**Comment by eljeffeg** [comment]
Was looking at this issue again and I still haven't been able to reproduce it.  Do you see any errors in the browser console?  
This is the piece of code that should select the option.

https://github.com/moloch--/RootTheBox/blob/feda8e9c6f863010a29e2d6436d11ebb5df8c7ba/static/js/pages/admin/view/game_objects.js#L48-L52

**Comment by PJNorrisS1** [comment]
Hi
I think this can be closed. I too, have not been able to reproduce this recently. Thanks for looking in to it though.
