### ISSUE TITLE
Auto import xml file after deploying docker container

### ISSUE THREAD

**Issue by jeffbenson4** [moloch--/RootTheBox#502]
I have a need to deploy 3 separate instances of RTB in different environments. Each will have different sets of flags, and not be accessible from the other environments. I started a default docker environment, created the boxes/flags, then exported the xml file. Is there a way to have RTB auto import an xml file that I've created from a previous game?  I would then create an xml file for each environment, then have it auto deploy when Deploy the Docker image. I'm not the greatest developer, so I'm looking for the simplest way possible. Love RTB!

**Comment by eljeffeg** [comment]
I haven't tested it in a while, but you should be able to run `rootthebox.py --xml rootthebox.xml`

**Comment by jeffbenson4** [comment]
Thanks for the quick response! I tried the --xml option, but I'm still getting nothing. I don't get any errors, but nothing changes.

**Comment by eljeffeg** [comment]
I was actually incorrect there.. It has an `=` in it.  So `rootthebox.py --xml="/path/to/rootthebox.xml"`.  I'd suggest doing a git pull on the latest code as the last two pushes help issues with XML import / export.
