### ISSUE TITLE
While loading scoreboard is taking long time

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#504]
Hi team,
I have seen that scoreboard is taking so long to load the page. As per the pagination, It suppose to load 50 users details in the page. I am displaying top 50 users on Summary page. 

Load the scoreboard, it is taking 17 seconds.

![image](https://user-images.githubusercontent.com/38101321/185334371-b0ebbdb2-0d3c-4036-9761-358f407693da.png)

Python debug.
![image](https://user-images.githubusercontent.com/38101321/185334583-20a072b6-681f-4b2c-bbc4-c1737100aff8.png)

Is there anyway to display only top 50 users and mention user rank in their profile/dashbooard.

Thanks

**Comment by eljeffeg** [comment]
That is pretty crazy.. displaying only the top 50 wouldn't help this situation.. that's essentially what the pagination is doing already.  The base `/scoreboard` query is pretty simple.

https://github.com/moloch--/RootTheBox/blob/273472308f15b00474b1f513d63a9582f395e535/handlers/ScoreboardHandlers.py#L80-L104

The only area that would take any amount of time would be the `Scoreboard.update_gamestate(self)` as this "refreshes" the data in memory (we could probably do this asynchronously to improve performance).  But here is the code if you wanted to put in some timing statements to see what is happening.

https://github.com/moloch--/RootTheBox/blob/273472308f15b00474b1f513d63a9582f395e535/libs/Scoreboard.py#L49-L121

**Comment by eljeffeg** [comment]
I created a new branch that updates the gatestate in a separate thread, which I think should resolve that issue.  But I expect the main problem is the history, which needs to be rewritten.  https://github.com/moloch--/RootTheBox/tree/scoreboard_test

**Comment by PunitTailor55** [comment]
I have tried the thread but not working. Summary page is taking 17 seconds to disaplay the top 50 users. I have removed pagination from `summary` and `team` page and displaying top 50 users only but still taking time. Also, disabled the `charts` from `scoreboard` page. 

![image](https://user-images.githubusercontent.com/38101321/185545376-eb23abfe-55b5-4ad7-b9a2-e6b16c0c9835.png)
