### ISSUE TITLE
New lab display first.

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#507]
Is it possible to display new lab on top/first such as decending order.

**Comment by eljeffeg** [comment]
Not yetl, unless you edit the database.
It's a feature request, which you've commented on: https://github.com/moloch--/RootTheBox/issues/492

**Comment by PunitTailor55** [comment]
If you give some idea then I will definetly try to impliment.

**Comment by eljeffeg** [comment]
Included for 3.12.0
