### ISSUE TITLE
Stream is closed

### ISSUE THREAD

**Issue by nametovski** [moloch--/RootTheBox#513]
Hello, 

Can you check the logs bellow? For some reason when there is load on the application 100+ concurrent users, everything becomes slow and the RTB web is not responding. The following logs are populated during this time.

Thanks
N.

Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]: [E 221012 14:16:42 base_events:1608] Task exception was never retrieved
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.7/dist-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     Traceback (most recent call last):
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:       File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 1092, in wrapper
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:         await fut
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     During handling of the above exception, another exception occurred:
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     Traceback (most recent call last):
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:       File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 1094, in wrapper
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:         raise WebSocketClosedError()
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     tornado.websocket.WebSocketClosedError
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]: [E 221012 14:16:42 base_events:1608] Task exception was never retrieved
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.7/dist-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     Traceback (most recent call last):
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:       File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 1092, in wrapper
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:         await fut
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     During handling of the above exception, another exception occurred:
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     Traceback (most recent call last):
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:       File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 1094, in wrapper
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:         raise WebSocketClosedError()
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     tornado.websocket.WebSocketClosedError
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]: [E 221012 14:16:42 base_events:1608] Task exception was never retrieved
Oct 12 14:16:42 ip-100-122-4-190 rootthebox.py[9726]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.7/dist-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>

**Comment by nametovski** [comment]
I've tested with 300 concurrent users today and looks much better with the latest fix. Still have some delays and slowness, but it does not cause timeouts or crashes. We are running big EC2 instances, so the resources are not a problem.

**Comment by eljeffeg** [comment]
In 3.12.0 there is also a new configuration option "scoreboard_lazy_update" that you may want to set to True.  This will further improve performance, particularly with so many concurrent users.  By default, whenever some does a scoreboard refresh it updates the gamestate.  While this has been formed to a background thread, it should be unnecessary to run in most situations as it already runs whenever someone captures a flag, user is created or when an admin makes an update. By setting this to True, it skips running the update on every refresh.

**Comment by eljeffeg** [comment]
An additional thought, might want to try and get visibility into memcached.  We're using the [python-binary-memcached](https://github.com/jaysonsantos/python-binary-memcached) client to access it in RTB, but you could look at misses, hits, total session limits, etc.  I'll close this issue for now, but feel free to reopen if you see some errors we can address or you have any ideas for improvement.
