### ISSUE TITLE
More Webhooks please…

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#517]
Would it be possible to add webhooks for incorrect flags, completed levels, hints taken, and when a flag is captured perhaps time difference between that and previous (not essential). In addition, could there be more information in the hook, such as host name, or game name?

The idea is to have a master leader board and stats on which flags are hard and need hints and how many captures. 

Thanks for the excellent work, we use your platform a lot and appreciate all your efforts.

**Comment by eljeffeg** [comment]
I'll take a look, but I'm going to tag @anthturner as he was the author of the webhooks.  By incorrect flags, you mean like some of the info we include on the statistics page?  Currently that's not something we expose outside the admin account.  I wouldn't mind having something that reflected challenge difficulty, but now sure how much we'd want to provide on that.  Completed levels, hints taken shouldn't be a problem - we show those on the scoreboard already.

**Comment by eljeffeg** [comment]
Looks like completed levels already had a webhook.  Incorrect flags (capture failed) had a webhook, but it only fired if there was a penalty, so I changed that.   Let me know if they're not working.  I added hints taken hook as well as including game name and the origin for each hook.  The time between flags will be difficult right now, but hope to remove the entire "snapshot" system and just timestamp all the actions at some point.

I don't have the webhook system setup on my test machine.. so please test. :)

**Comment by PJNorrisS1** [comment]
Thank you! I will do some testing later. Meanwhile, I use a free account on hookdeck.com to test the responses coming in. Just generate a URL and stick it in the .cfg file.
