### ISSUE TITLE
!! 3.12.0 build/db migration error !!

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#519]
I fetched and merged 3.12.0 to my 3.11.1 master to test...

I ran docker compose build
I ran docker compose up
and it's exiting with the following messages:

rtb-uk-webapp-1     | [I 221016 10:02:32 rootthebox:262] Environment Configuration (SQL_DIALECT): sqlite
rtb-uk-webapp-1     | [I 221016 10:02:32 rootthebox:1083] Running Docker Setup
rtb-uk-webapp-1     | [I 221016 10:02:32 ConfigHelpers:15] Saving current config to: files/rootthebox.cfg
rtb-uk-webapp-1     | [*] Switching CWD to '/opt/rtb'
rtb-uk-webapp-1     | [*] 10:02:32 : Creating the database ...
rtb-uk-webapp-1     | [I 221016 10:02:32 rootthebox:262] Environment Configuration (SQL_DIALECT): sqlite
rtb-uk-webapp-1     | [I 221016 10:02:32 __init__:267] Checking for Database Updates...
rtb-uk-webapp-1     | [I 221016 10:02:32 migration:204] Context impl SQLiteImpl.
rtb-uk-webapp-1     | [I 221016 10:02:32 migration:207] Will assume non-transactional DDL.
rtb-uk-webapp-1     | [I 221016 10:02:32 migration:618] Running upgrade 31918b83c372 -> de5d615ae090, add user to penalty stat
rtb-uk-webapp-1     | [E 221016 10:02:32 rootthebox:54] Error: (sqlite3.OperationalError) duplicate column name: user_id
rtb-uk-webapp-1     |     [SQL: ALTER TABLE penalty ADD COLUMN user_id INTEGER]
rtb-uk-webapp-1     |     (Background on this error at: https://sqlalche.me/e/14/e3q8)
rtb-uk-webapp-1 exited with code 1

**Comment by eljeffeg** [comment]
Thanks - Alembic can be a pain on sqlite.  Made some changes to the db update script to handle it better.  We need to implement the CD so the docker is tested on each commit. #395

**Comment by PJNorrisS1** [comment]
Phew - relief! I'm up with 3.12.0 now and it works - and GREAT work on the status too, just what is needed.
