### ISSUE TITLE
Automatic Ban - not persistent

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#525]
Hi, we are getting a lot of brute force attempts on the sites. I have enabled Automatic Ban, but when I restart RTB, it does not remain. I see it's not stored in the cfg, but most likely a memory thing like Game status and registration.

Please could you have this as a configuration option so it can remain persistent?
![image](https://user-images.githubusercontent.com/106666319/197265324-03b7c24b-8ee7-4f15-b5c0-4f45119b1552.png)

**Comment by nametovski** [comment]
You can edit handles/__init__.py and update the default settings there. This will set the the Enable automatically for you on each start. Same for the Threshold and you can add additional blacklisted IPs.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/15018959/197302856-fece7175-b72d-4aec-a82b-8421a5012fe6.png">

**Comment by eljeffeg** [comment]
The save will now persist and the option is available in the config.

**Comment by PJNorrisS1** [comment]
Marvellous! Thank you again!
