### ISSUE TITLE
Have an option to clear out teams and users when resetting game

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#526]
Is is possible to have a checkbox on this screen: 
![image](https://user-images.githubusercontent.com/106666319/197299779-2d0d5545-ae40-41eb-ac10-b63956d6c9f9.png)
that will delete all player names and team names? Please?

**Comment by eljeffeg** [comment]
Option added

**Comment by PJNorrisS1** [comment]
Legend! Thank you - much needed!

**Comment by PJNorrisS1** [comment]
Just tested - getting this up:
![image](https://user-images.githubusercontent.com/106666319/197895413-af527ba0-bc5f-4e5b-95ae-0d265a82a0fe.png)
I have tested it with game stopped, registration open and one user registered, with two administrator accounts registered. On that note, I assume the admin accounts will remain or will they be nuked too?

**Comment by PJNorrisS1** [comment]
Also tried reset game - 
![image](https://user-images.githubusercontent.com/106666319/197895622-f4535e3c-5f1a-4588-802e-74f4f0efc017.png)

**Comment by eljeffeg** [comment]
Admin account will remain.  Do you see any error in the logs?

**Comment by eljeffeg** [comment]
Pushed a fix I hope - I had tried to persist the admin's session since I clear the memcached after the reset to kick off all users.  However, I guess that caused an issue.  So the admin will have to log back in after the reset.

**Comment by PJNorrisS1** [comment]
Yup that fixed it! Nice one. Just one observation though... as this is a one way action with no undo button, I would perhaps suggest we have a confirmation box come up - Are you sure you want to RESET / Delete Game? and have the user enter a physical word in. As I said, there is no undo button :-). If not a physical word, perhaps just a yes no button? :-)

**Comment by eljeffeg** [comment]
I tend to find over-proofing annoying, so I just added a confirmation yes no.  If you go through the process to click the reset page, click the reset button, then click confirm - that's on you. lol

**Comment by PJNorrisS1** [comment]
Ha brilliant! Thank you. Tend to agree, but we also have ‘dumb’ users too – “problem between keyboard and chair” type people

From: ElJeffe ***@***.***>
Date: Wednesday, 26 October 2022 at 13:53
To: moloch--/RootTheBox ***@***.***>
Cc: PJ Norris ***@***.***>, Author ***@***.***>
Subject: [EXT.MSG] Re: [moloch--/RootTheBox] Have an option to clear out teams and users when resetting game (Issue #526)

I tend to find over-proofing annoying, so I just added a confirmation yes no. If you go through the process to click the reset page, click the reset button, then click confirm - that's on you. lol
