### ISSUE TITLE
Tracking an internal game version

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#527]
Hi, as we run a number of RTB’s, we update from time to time the flags and tokens. In order to keep track which boxes we have updated, we append a version number (currently a date, but can be any string) to the game name, so when we pull the /status game JSON we can see at a glance the game version in the game name. 

However, this also appears in Webhooks so I use a regex parser to strip it to keep the game names unique, and it also appears in the game title page, so this is not really an ideal or tidy solution. 

The ask… could we have an entry in the cfg file to store or own internal version (not just RTB’s version), and also have that exposed on the /status JSON as well? It would eliminate the parsing and the ugliness of our titles. Thank you as always.

**Comment by eljeffeg** [comment]
Added to the status and the webhooks as `game_version`.  Renamed `version` to `rtb_version` on status.

**Comment by PJNorrisS1** [comment]
THANK YOU! What a game changer that is for us! Recoding it tonight to make it work for workshops tomorrow. Thank you!

**Comment by eljeffeg** [comment]
We might want to add this to the gui config, that way you don't have to restart rootthebox to pick up a new version.

**Comment by PJNorrisS1** [comment]
That would be incredible. On that note, could there be a button on the config to say “reload config” to load changes from cfg file without restarting?
