### ISSUE TITLE
Player Count does not increment /status

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#528]
I've noticed this a few times now, and can now recreate.

- New Game
- Game stopped, registration open
- Register a new player
- /status player_count is 0
- No change after a while
- Log in as admin
- See player has registered
- /status player_count still remains at 0
- Load the score board
- /status player_count is now at 1

The same occurs when I remove that player... it will only decrement when the scoreboard page is loaded.

Is there something happening when the scoreboard loads for the player_count string to update?

Thanks

**Comment by eljeffeg** [comment]
Yeah, the count was pulled from the scoreboard cache instead of directly from the database. I can update that as it's not a heavy query.

**Comment by PJNorrisS1** [comment]
Ahh magic! Thank you
