### ISSUE TITLE
When deleting a player, it's not cleared from DB

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#529]
Scenario:

- Create a new player by registering
- Player exists on scoreboard
- Test the player exists by going to add points manually under user management - player is listed
- Delete the player from user management
- Player is removed from scoreboard
- Go to the add points under user management and the player is still listed.
- 
![image](https://user-images.githubusercontent.com/106666319/199468383-35f4eeda-9010-4bb2-a651-c1804e979ba8.png)

This is the same for teams as well. Before you added that wonderful new feature of resetting all users, I had a large list of old player and team names in that pull down list. The only true way to delete a player now is to reset the game with users deleted.

Happy hunting :-)

**Comment by eljeffeg** [comment]
There were two delete player buttons when in player mode.  If you use the small one, it didn't actually delete the "team" (team of 1).  So I now hide that smaller delete button when in player mode so there is only one delete and it deletes both.

**Comment by PJNorrisS1** [comment]
Ah that makes perfect sense! Great job, thank you.
