### ISSUE TITLE
Default registration setting change

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#530]
I know game status (started/stopped) and registration is (open/closed) are stored in memory. They default to stopped and registration open. 

Could it be that:

- Registration is not volitile and stored as a setting, so will survive restarts of container?
- Game state - restore the previous known state, eg: it was running or not. 

The first one is more important (registration) than the second suggestion (game state).

Thanks in advance,
PJ

**Comment by simon-hoegl** [comment]
Take a look at PR #535. Not exactly what you are looking for but at least this makes the "suspend registration" status configurable

**Comment by PJNorrisS1** [comment]
Perfect thank you - partially resolved. The 2nd option is a nice to have.
