### ISSUE TITLE
Way to copy boxes and Flaggs to another Company (Konzerne)

### ISSUE THREAD

**Issue by H4xl0r** [moloch--/RootTheBox#540]
Maybe i just dont get it but if i crate new Konzerns / Companies 
why is there no option to copy existing boxes and flags into a new Comp. (also with the flags for boxes)
It directly gives me the option to create a new one , but what if i want to use existing ones ?

**Comment by eljeffeg** [comment]
We should be able to easily add that ability.

**Comment by eljeffeg** [comment]
Once you create a Corporation, you can go to the box and click the Edit and change the Corporation for that box.

<img width="543" alt="Screenshot 2023-02-18 at 8 07 19 AM" src="https://user-images.githubusercontent.com/161904/219867476-b187d6bf-afe5-4cc8-a459-bf17d27437c8.png">

**Comment by H4xl0r** [comment]
Thats not a copy it moves the machine i want to copy them

**Comment by eljeffeg** [comment]
Ah, I guess the best way currently would be to export the xml, modify it copy the box under a new corp and then import it back in.  It shouldn't delete the other one and just add what's new.

**Comment by H4xl0r** [comment]
would even work with same box names ? like box name a in corp 1 and box name a in corp 2 ?

**Comment by eljeffeg** [comment]
I think you're correct that you would have to give it a new name and probably alter the garbage key.
