### ISSUE TITLE
Error locking a level

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#541]
This is recreatable.

Unable to lock a level. If setting to locked, remains unlocked. The workaround is to select Game Progress, change the 0 value to any number other than zero, then reselect Lock, the level will save locked.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/106666319/219798214-ae16c567-78ff-4e01-8c06-1d7a920e98e0.png">
Bring up the field with a 0 value in it
<img width="428" alt="image" src="https://user-images.githubusercontent.com/106666319/219798289-2632d138-419d-40c8-a355-2c7220dc864b.png">
Change that to a positive value
<img width="436" alt="image" src="https://user-images.githubusercontent.com/106666319/219798361-7cb5bb78-f7ea-4773-9c23-51f27abc48a8.png">
Then select Lock and save
<img width="541" alt="image" src="https://user-images.githubusercontent.com/106666319/219798447-5550f5aa-b566-4054-bedc-31f10c96d410.png">

In general, you can't enter a 0 value for purchase unlock or % of previous level. If this is fixed this bug is resolved.

**Comment by eljeffeg** [comment]
Pushed a fix - thanks for the report.

**Comment by PJNorrisS1** [comment]
Fixed thank you
