### ISSUE TITLE
[down] Web Site and Demo Site (heroku)

### ISSUE THREAD

**Issue by ramazansancar** [moloch--/RootTheBox#543]
Hello, when I try to access the site, I get a warning that hosting is unavailable.

Can you check?
- https://root-the-box.com/
- https://rootthebox.herokuapp.com/

**Comment by eljeffeg** [comment]
Yeah, looks like @moloch-- let root-the-box.com expire.  It wasn't updated in any case.  We can probably remove that on the GitHub link.
The heroku app is on me.  I think they did away with their free dynos and I never changed it.  Maybe I'll move it to GCP.  Thanks for letting us know.

**Comment by moloch--** [comment]
Yea just remove the link, it had super outdated info.

**Comment by moloch--** [comment]
@eljeffeg i still have the domain, the server died.

**Comment by ramazansancar** [comment]
@eljeffeg @moloch-- 
How about deploying with Vercel.com? (Free up to 100GB bandwidth per month)

Check this,
- https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/python
- https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js

**Comment by moloch--** [comment]
I do like Next.js hehe

**Comment by moloch--** [comment]
Its not so much the cost as we hadn't updated the website since about 2015

**Comment by ramazansancar** [comment]
@moloch--  Well then, I'm looking forward to its release.

**Comment by eljeffeg** [comment]
Updated the demo link to https://rootthebox-2xyfdkbnkq-uc.a.run.app
