### ISSUE TITLE
External Links href add target="_blank"

### ISSUE THREAD

**Issue by H4xl0r** [moloch--/RootTheBox#546]
add target="_blank" For External Links inside of RTB 
Links inside Description Texts (added via the html editor ) that go to another page should be targeted with target="_blank"
so the external link loads a new tab 

We should also think about renaming the Wargame to something similar with less bounding to war (UK/Russia) this could be taken wrong by some ppl
'Hackspace'or'Hackgame' something like that

**Comment by eljeffeg** [comment]
Added the target="_blank"
