### ISSUE TITLE
Unable to login into Admin via web

### ISSUE THREAD

**Issue by mr-1nc00r3ct** [moloch--/RootTheBox#550]
Hi Team,

I am unable to log in via the web console into the Admin account. Getting an error as Admin is restricted by IPs and making changes in the .cfg file. However, I have kept the value empty for Admin IPs. Could anyone guide me thru? PFA screenshot of the configuration and error message in login page is "Successful credentials, but administration is restriceted via IP. See 'admin_ips' in configuration."

![2023-04-04](https://user-images.githubusercontent.com/54534321/229722610-ab389081-23ff-4e12-873f-e6e4b004654f.png)

**Comment by eljeffeg** [comment]
Try setting `admin_ips = []` and not `['']`.  The first is a 0 length list, the second has a length of 1 but has no value.  I expect you're telling it there is 1 admin IP with no value.

**Comment by mr-1nc00r3ct** [comment]
Hi, the first one did the job. Thanks very much
