### ISSUE TITLE
[Question] Docker Deployment - Turn Debug back off

### ISSUE THREAD

**Issue by jharbin** [moloch--/RootTheBox#552]
May not be an issue, more than a question that I can't seen to find an answer to on the WIKI or in the GitHub repo.

I put the --debug directive in as an ENTRYPOINT when I built the system and now want to turn debug back off.  I have removed the additional directive from Dockerfile and done a "docker-compose build".  As I see the build steps go by, the ENTRYPOINT params look ok and the build completes successfully, but... when I execute a "docker-compose up" to bring the system back on-line it still shows: "Debug mode is enabled; DO NOT USE THIS IN PRODUCTION".  How do I turn debug back off?

**Comment by eljeffeg** [comment]
Debug=true might have gotten written to your config file, which should be in the mounted volume.

**Comment by jharbin** [comment]
Got it... correct answer!

/files/rootthebox.cfg contained debug = True.

This would be nice to toggle off and on in the configuration dialogue.  :)

Thanks!
