### ISSUE TITLE
reCaptcha does not appear

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#556]
I am trying to setup recaptcha on registration and login page. While giving `recaptcha_site_key`, `recaptcha_secret_key` and `use_recaptcha = True`. It doesnot appear on screen. I have checked `PublicHandler.py` there is no configuration regarding `reCaptcha`. Please guide me on reCaptcha setup. Thanks.

![image](https://user-images.githubusercontent.com/38101321/235066837-94798366-78be-4225-8c78-0a0b3236dffe.png)

![image](https://user-images.githubusercontent.com/38101321/235066904-0895f777-5eaa-40d6-9ecf-9ba5834cf489.png)

**Comment by eljeffeg** [comment]
I think this is just for the banking password, not registration. https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#recaptcha

**Comment by PunitTailor55** [comment]
It would be great if we set for registration and login. It helps to stop brute force attacks.

**Comment by eljeffeg** [comment]
Feature Added

**Comment by eljeffeg** [comment]
This is what it looks like for me.  Wonder why it's not showing up for you.
<img width="984" alt="Screenshot 2023-06-06 at 11 46 07 PM" src="https://github.com/moloch--/RootTheBox/assets/161904/4542666b-34c1-4102-be09-b30e6ffe9d0c">
