### ISSUE TITLE
Suggestion: Hide levels if locked

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#559]
We are using the RTB platform to host a few variants of the CTF. We are using Level locks to enable or disable levels for players. 

It would be great if we could have an option in the list to 'hide' the level in the pull down list: 
![image](https://user-images.githubusercontent.com/106666319/236514563-92a65c8e-2ed8-4f69-b0ba-d831ec812cd9.png)
So it doesn't appear.

Alternatively, perhaps an option under configuration to toggle - Show/Hide locked Game levels?

**Comment by eljeffeg** [comment]
The Managed option will hide the level.  Are you thinking something different?

**Comment by eljeffeg** [comment]
To clarify, with Managed, you can select which users have access to the level.  Users that don't have access to the level will not see it.  There is no requirement for a user to have access, so it could be hidden from all users.

**Comment by PJNorrisS1** [comment]
Yes! That works! Thank you.
