### ISSUE TITLE
Scoreboard placing is incorrect and based on the last person who scored.

### ISSUE THREAD

**Issue by tetravaal4** [moloch--/RootTheBox#560]
While playing a game if there are two players with the same score, the last person who scored shows as first place, even if another user has the same score and scored the final flag before them.

EX. 
Player 1 - Scores final flag - Total Score 100
Player 2 - Scores final flag 10 minutes later - Total Score 100

Result
Player 2 in 1st place
Player 1 in 2nd place

I would assume that in the event of a tie, the person who scored first would remain in the top position. 

![image](https://github.com/moloch--/RootTheBox/assets/68917796/31c27385-9bab-4299-8be1-1466f4eb8659)

Mega fan of your work!

**Comment by eljeffeg** [comment]
Yeah, you're right.  There were two ways to rank, score & flags.

- Score uses this formula `score ▲, hints ▼, flags ▲`
- Flags uses this formula `flags ▲, score ▲, hints ▼`

But if you don't use hints and flag values are equal, there is no time component so it would just sort by first registered team.  I adding a time component makes sense.  This is what I'm thinking:

- Score uses the formula `score ▲, hints ▼, time ▼, flags ▲`
- Flags uses the formula `flags ▲, score ▲, hints ▼, time ▼`

I'm thinking putting time before flag count when ranking based off of score as it would seem to me that when basing things on score, the number of flags captured should be somewhat irrelevant if another team gets a score first.

**Comment by tetravaal4** [comment]
I agree with that methodology and it should solve any "same score" scenarios and I really appreciate you taking the time! I wish I were better on the coding side and could help, but I will offer some beer money because of how awesome RTB is and how responsive you are. Let me know if you have a tip jar, or cup of coffee link.. 

As a fun anecdote, I was running a game today and we had a same score scenario combined with the exact same time of capture on the last flag. To fix even this scenario, we are going to implement point decrements for incorrect questions.

![image](https://github.com/moloch--/RootTheBox/assets/68917796/fc1f2e53-c4f6-4724-bec0-0dcc8812649a)
 
Thanks again!

**Comment by eljeffeg** [comment]
I pushed up the change if you can give it a test.

**Comment by eljeffeg** [comment]
If you don't mind unsolicited advice, with `point decrements for incorrect questions` you'll want to review your stats periodically for incorrect guesses and adjust your tokens to include simple mistakes (via regex or something).  Of course, this will depend on your game.  If you wrap your flag in something like FLAG{...} then it's usually a non-issue, but it sucks to lose a point (and maybe the game) because of case sensitivity or formatting when you feel you got the answer correct.
