### ISSUE TITLE
Resetting a game from CLI or DB?

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#561]
Trying to automate the resetting of a game.

We have game admins who leave the RTB instance as is after a session. When others need to use it, they are concerned the box is in use. We are trying to automate a way of resetting the game instead of doing it via admin menu, reset and clear out data and players.

Have full access to db, scripts etc from a CLI on a RHEL host, and each RTB is running in it's own docker container. Welcome thoughts.

**Comment by eljeffeg** [comment]
I think we could add a reset option to the cli.

**Comment by eljeffeg** [comment]
Pushed up the change if you can test it.  You'll probably need to do a `--restart` after to get the scoreboard to update as I didn't see a good way to update the app's in-memory gamestate from the cli.

- `--reset` keeps teams / players and resets the game to start`
- `--reset-delete` deletes teams / players and resets the game to start

**Comment by PJNorrisS1** [comment]
Works perfectly! Thank you!
