### ISSUE TITLE
Enable team members to see captured tokens

### ISSUE THREAD

**Issue by dodecagonfd** [moloch--/RootTheBox#571]
I host online competitions using the RootTheBox. 
I create flags with a mix of tokens and questions-and-answer.
Especially in the latter case, it is convenient if a member within a team can see the token or the answer that other members from the same team already has captured.
Currently, I believe this is not the case.

**Comment by eljeffeg** [comment]
See the [show captured flag](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#show_captured_flag) option.  Setting it to True should do what you describe.  You'll have to set this on the configuration file and restart rtb.
