### ISSUE TITLE
Showing player UTF-8 name in the scoreboard

### ISSUE THREAD

**Issue by ilovewingchun** [moloch--/RootTheBox#577]
By default the scoreboard will show all the player's handle name instead of the defined player name. Admin can manually set the displayed name for the scoreboard. Can we add a feature so that the scoreboard can automatically show all the player's name instead of handle name?

**Comment by eljeffeg** [comment]
This might be a challenge as it's not actually the user handle that is being displayed, it's the team name.  When in individual player mode, what really happens is that you're creating a team of one, so the user becomes the team.  So it's not as simple as `if x then handle else real_name`.

**Comment by eljeffeg** [comment]
What we could potentially do is, when it's in player mode, have a setting that sets the team name based on the full name instead of the handle.  It would be a bit odd, but would probably work how you want.

**Comment by ilovewingchun** [comment]
> 

Yes that would work, thanks!

**Comment by eljeffeg** [comment]
Ok, added a configuration option (have to edit the rootthebox.cfg) for the option [player_use_handle](https://github.com/moloch--/RootTheBox/commit/de44dd6ef86dd5b97524d0e438d0441922099930). You'll want to set this value to False, which will tell it to use the playername.

**Comment by ilovewingchun** [comment]
> Ok, added a configuration option (have to edit the rootthebox.cfg) for the option [player_use_handle](https://github.com/moloch--/RootTheBox/commit/de44dd6ef86dd5b97524d0e438d0441922099930). You'll want to set this value to False, which will tell it to use the playername.

Tested and looking good, thank you!
