### ISSUE TITLE
Increase Flag Description field from 1024 to 4096

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#584]
I'm finding the Flag Description field is truncating my flags. Is it possible to increase from VARCHAR(1024) to VARCHAR(4096)?

Thanks

**Comment by eljeffeg** [comment]
Yeah, no problem 
https://github.com/moloch--/RootTheBox/commit/286d709002b86d3660a6a7a908172f65daa10387

**Comment by PJNorrisS1** [comment]
Fantastic! Thank you
