### ISSUE TITLE
Request a webhook on user validation

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#586]
In addition to the awesome webhooks you have added for me in the past, any chance you could put one on when a user validates their email address? We looked, I think it may only be a few lines of code perhaps? :-)

Thank you again.

**Comment by eljeffeg** [comment]
Pushed up a webhook - please test and let me know if it works good.  I also removed a couple things that seemed like duplication and unnecessary in the user and team info.. let me know if that was important. lol

**Comment by PJNorrisS1** [comment]
Yup tested and looks great to me! Thank you so much. I think the additional WebHook information is okay to be removed.
