### ISSUE TITLE
./rootthebox.py --save error on CentOS 7

### ISSUE THREAD

**Issue by anarkygit** [moloch--/RootTheBox#59]
./rootthebox.py --save
Traceback (most recent call last):
  File "./rootthebox.py", line 432, in <module>
    options.parse_command_line()
  File "/usr/lib/python2.7/site-packages/tornado/options.py", line 191, in __getattr__
    raise AttributeError("Unrecognized option %r" % name)
AttributeError: Unrecognized option 'parse_command_line'

**Comment by moloch--** [comment]
You may have an old version of Tornado, make sure you have the latest code and try `rootthebox.py --version`

You should see something close to:
```
Root the Box v0.6.1
 SQL Alchemy v0.9.8
     Torando v4.0.2
```

**Comment by anarkygit** [comment]
It appears the Tornado version on 2.2(provided I installed the correct package, python-tornado) on the centos base repo. I just installed pip and did it that way. Thanks!
