### ISSUE TITLE
Manually validating a user

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#593]
Hey,

When a user validates their email, there is a webhook sent. If an admin manually validates (unlocks) the user; no webhook is sent. 

We capture the webhook in another tool that creates a user on another system, therefore could a webhook (same one) be sent when an admin manually validates a user (unlocks?).

Thanks

**Comment by eljeffeg** [comment]
I added the webhook for the admin manual validation if you could test it. https://github.com/moloch--/RootTheBox/commit/203fe55c4d07a198fdb246671f7374be5df09ba7

**Comment by PJNorrisS1** [comment]
Perfecto! thank you!
