### ISSUE TITLE
Invalid Characters in Full Name

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#598]
With so many games we play globally, I can't believe this hasn't come up before!

We have an instance running in France and we had a few users register on the RTB console with é in their name (eg: Céline).

When clicking register, we get "glitch in the matrix", or in France it was "Glitch dans la matrice"
<img width="766" alt="image" src="https://github.com/moloch--/RootTheBox/assets/106666319/fca8897d-2abd-43d1-bd2b-6289bfca00a4">
RTB validates Handle Field and Email field, can we have a validation on the Full Name field please?

**Comment by eljeffeg** [comment]
Hmmm, that shouldn't happen.  Do you happen to have the stack trace on that?

**Comment by PJNorrisS1** [comment]
Not at hand at moment but super easy to replicate try registering and put a foreign character in the Full Name field. Oddly enough the user is created though. On 9 Nov 2023, at 21:41, ElJeffe ***@***.***> wrote:﻿
Hmmm, that shouldn't happen.  Do you happen to have the stack trace on that?

**Comment by eljeffeg** [comment]
Yeah, trying to replicate it, but the account seems to create.  What page are you seeing the error on?

**Comment by bmartin5692** [comment]
@eljeffeg - I've opened PR #599 which addresses the issue
