### ISSUE TITLE
DB Schema change

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#601]
Seasonal Greetings!

A couple of minor requests if you could be so kind to squeeze in for us please?

- .box._description is varchar(4096), however the box description is limited to 1024 - please can that be changed? 
![image](https://github.com/moloch--/RootTheBox/assets/106666319/f135ca92-b107-4c29-ae54-d2420ab25736)
- add a new field to .flag called _plain_answer as a varchar(256) - this is purely an internal admin db and nothing in the interface. We want to query the DB to show the flags and answers, but not the regex tokens, so we want to store the acceptable answer in this field so we can query it

Thank you 
PJ

**Comment by PJNorrisS1** [comment]
Hello! Any thoughts on the above schema change please?

**Comment by eljeffeg** [comment]
Sounds good, just haven't had time to look at it.  The box description should be an easy fix.  The new field will take a little longer as it has a db migration script.

**Comment by eljeffeg** [comment]
Ok, should be all set.

**Comment by PJNorrisS1** [comment]
Many thanks for doing this. qq. should the master build update existing db schemas or is it only when new db's are created? Is the _plain entry visible in the 'create flag' screen, or i manually update the db ?

**Comment by CyDefender** [comment]
It should update existing db.  It is not visible in the UI yet, just the db.

**Comment by PJNorrisS1** [comment]
Thanks - didn't update my db, hence asking. I see the box description fixed now. I'll do it again and see how it goes. Thank you.

**Comment by PJNorrisS1** [comment]
ah ignore me, picked the wrong db to browse! haha - see _plain_answer now - thank you!
