### ISSUE TITLE
something wrong with templates/theme/theme.html

### ISSUE THREAD

**Issue by vivek12895** [moloch--/RootTheBox#62]
this was the error,
http://sprunge.us/QBJW

**Comment by vivek12895** [comment]
update: self.theme is 
None

**Comment by vivek12895** [comment]
./rootthebox.py --admin_ips=10.1.74.164  --start
then i am getting 
Successful login: admin from 10.1.74.164
 then i got to /admin but i am getting some sort of fake page

**Comment by moloch--** [comment]
I'm looking into it.

**Comment by vivek12895** [comment]
how do i get admin panel??

**Comment by moloch--** [comment]
You should still be able to access the admin console from `localhost`, I'm looking into the issue with the Admin IP list not working properly.

**Comment by Markin** [comment]
Theme name in preference must be first capital letter. Default is 'cyborg', must be 'Cyborg'.
