### ISSUE TITLE
team management features

### ISSUE THREAD

**Issue by bb111189** [moloch--/RootTheBox#64]
Some feature ideas:
1. The ability to delete existing team
2. The ability to reset all flag and $$ to 0.

**Comment by moloch--** [comment]
Unfortunately due to the way object relations work in the database it's not possible to delete teams, however a "Reset Game" option is a good idea!

**Comment by AnarKyx01** [comment]
Question on #1.  When I manually delete a team via mysql, I don't see to see any issues.  Can you elaborate on where this becomes an issue?

**Comment by moloch--** [comment]
You can delete the Team objects, if they're not in the Scoreboard history. After they're in the Scoreboard history removing them becomes problematic because of all of the foreign keys that get broken.

**Comment by AnarKyx01** [comment]
Gotcha, don't think I've ran into that issue, as history appears broke atm....

[E 150522 15:30:31 ioloop:588] Exception in callback <bound method GameHistory.take_snapshot of <libs.GameHistory.GameHistory object at 0x7f839255b890>>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 989, in _run
        return self.callback()
      File "/home/anarky/PycharmProjects/RootTheBox/libs/GameHistory.py", line 75, in take_snapshot
        self.event_manager.push_history(snapshot.to_dict())
    TypeError: push_history() takes exactly 1 argument (2 given)

**Comment by jasnow** [comment]
Yes, I would like "reset" or "restart" GUI option too. I have tested my CTF and want to start over - I deleted the team members but the summary page still shows the pie chart with total score. I am running RTB in VM inside Ubuntu 16.04 and using sqlite database.

**Comment by jeffg2k** [comment]
An option to reset the game was added. https://github.com/moloch--/RootTheBox/commit/3edaa97444f0dca4c502acb8d3695d6d0aa7f11c  Also, if a team has no players, it is no longer displayed on the scoreboard or player list.  It's hidden with an exception being if the team scored points in the past, in which case, the name will still be visible on the history page.

I have some SQL updates that should allow us to delete teams, but that requires more testing.

**Comment by jeffg2k** [comment]
Added the feature to delete a team and already added ability to reset game.
