### ISSUE TITLE
Can not use the Start Button

### ISSUE THREAD

**Issue by megatraveler** [moloch--/RootTheBox#65]
Hi,

I am facing the issue that after we started the Python Script, we can nearly do anything on the Website, besides to start a Game. The Button shows no response. Checking in Debug mode, I can not even see the request, when I hit start the game.

Hope you can response soon, we wanted to run the Scorebot this afternoon. :/

bye
MT

**Comment by bb111189** [comment]
Have you set the admin ip address to ur machine? I previously had similar problem and was solved after setting the admin ip address to my machine in the configuration file.

**Comment by megatraveler** [comment]
Jeah, solved it. It was not the admin IP, besides, that was missed too. There was the wrong Socket defined within the [Server] origin section.
So, it took some time to figure out, but I have it now running on Port 80. But, I still can not get it done on 443 with SSL. Maybe the next time. Right now I am happy, that it is up and running ;)

**Comment by megatraveler** [comment]
@bb111189 can you tell me how to reset the values for a team. We run a test on start game now the values are fixed in the scoreboard. How can I reset the values?

**Comment by megatraveler** [comment]
Solved ;) but Thanks anyway :+1:
