### ISSUE TITLE
Feature Request - Hints

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#66]
Is there a way that an administrator could provide multiple hints for each flag instead of tying the hints to each box?  This would be a great feature for situations where you want each contestant (students in this case) to be able to obtain every flag and the only difference at the end of the game being the score for each contestant/team.

Thanks for your consideration.
Chris

**Comment by moloch--** [comment]
Sure thing, I'll add it to the TODO list

**Comment by jeffg2k** [comment]
Feature added in https://github.com/moloch--/RootTheBox/commit/ce239c609ecf1cff65c7333ca7fd1e03b1067c18
