### ISSUE TITLE
How do I reset the Game

### ISSUE THREAD

**Issue by megatraveler** [moloch--/RootTheBox#67]
Hi,

maybe I am missing something :(

I have a running box with scorebot. So when I start a game, everything works fine. Noe I want to reset everything and start a new game with the same scenario.

I am pretty sure, I need to reset something within the MySQL Database, but somehow I can not figure it out. 

Could somebody provide some Help on this.

Maybe it would be not bad to have a button within the Admin Website, to reset the scores and to restart the game.

aTdHvAaNnKcSe

Bye
MT

**Comment by moloch--** [comment]
The easiest way is to just drop the database and re-run the setup, it should go something like this:

```
mysql -u <user> -p

mysql> drop database rootthebox; create database rootthebox
mysql> exit
./rootthebox.py --setup=prod
```

**Comment by megatraveler** [comment]
Thanks, that worked gerat ;)
