### ISSUE TITLE
Score board summary

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#69]
Score board summary pie charts ceased functioning 1-2 hours into the game.  The line graph continued working.

**Comment by moloch--** [comment]
Interesting, I've not seen this issue before. Can you provide more details around what happened (e.g. number of players, flags, etc) and any details you think may have contributed to it?

**Comment by cgsilvers** [comment]
we had around 30 contestants within 16 teams.  there were a total of 47 flags distributed over 4 companies with 3 boxes each.  The board was working fine until about an hour or two into the game.  it just stopped showing anything in the pie charts.

**Comment by kumux** [comment]
I'm currently seeing this issue using Nginx as a proxy, but when I connect directly on port 8888 the charts are visible.

**Comment by jeffg2k** [comment]
I've updated the libraries for the graph software in the latest RTB version, which I know fixed other graph issues (#155).  Between that and the nginx fix #73, I'm hoping this issue is resolved.  I'm going to mark it closed.  If there is still a problem, we can reopen.
