### ISSUE TITLE
Admin feature

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#75]
Ability for admins to see all teams paste bin & shared files

**Comment by noraj1337** [comment]
And ability to disable teams paste bin & shared files

**Comment by jeffg2k** [comment]
Added - Ability for admins to see all teams paste bin & shared files, ability to disable teams paste bin & shared files.

**Comment by garanews** [comment]
Need possibility to add files/pastes from Admin to a single team

**Comment by jeffg2k** [comment]
@garanews fixed the Py3 bug and added the ability for admin to add files/pastes to a single team or all teams.
