### ISSUE TITLE
Messaging feature in game

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#80]
in game messaging between players and admins

**Comment by moloch--** [comment]
I think Slack/Discord integration is the way to go instead of re-inventing the wheel. It would be nice to have RtB send updates to team channels at stuff too.

**Comment by jeffg2k** [comment]
I'm going to look into integration with RocketChat this week for an upcoming CTF I'm hosting.  RocketChat is offered in Ubuntu and could easily be deployed along with RTB without any Internet dependencies.  I'm thinking that if enabled, when the user registers on RTB, it could create an account on the configured RocketChat server via the API.  It could probably also automatically set up team channels and send alerts via this method if we offer that as options.

As a side note, I'll be running the Python3 codebase with about 30 users, so should be a good vetting.

**Comment by moloch--** [comment]
You know I also wrote a RocketChat XSS worm :) - https://github.com/moloch--/little-doctor

**Comment by jeffg2k** [comment]
@moloch-- one issue with the rocket chat integration is that rocket chat limits the username to use only `letters, numbers, dots, hyphens and underscores`.  If a RTB user creates a handle with something outside that, such as a space, it fails to create an account on RocketChat for the player.  I see a couple options if we want to make it work properly.

1. Change RTB handle field to match the username requirements of Rocket Chat.
2. Option 1, but only when Rocket Chat is used by RTB

Any thoughts, suggestions or preferences on what to do?

I need to look at the restrictions on private group names as well, as we use the team name to create private groups on Rocket Chat.  On this one, if the team has a space in it, I automatically replace it with an underscore.  This is not a problem as this is just a private group that displays for them.  The username is different as they have to log in with it and I didn't want to alter it from what they specified in RTB.

**Comment by jeffg2k** [comment]
I have seen some creative use of handles, such as emoji, in CTFs.  I haven't tried that in RTB, but I expect it would support that.  So, I sort of lean toward option 2 so we're not limiting everyone for those that want to use Rocket Chat.

**Comment by jeffg2k** [comment]
Turns out, we already had the regex limited to letters and numbers.  I don't see an issue with removing spaces and allowing dashes, underscore, and dots.
