### ISSUE TITLE
xml import fails

### ISSUE THREAD

**Issue by admin-support** [moloch--/RootTheBox#88]
When attempting to import already exported xml file the import fails.
In the gui you are given a 404, but if you do it commandline you get an error.

user@ubuntu:~/RootTheBox$ sudo ./rootthebox.py --xml data.xml
Traceback (most recent call last):
  File "./rootthebox.py", line 438, in <module>
    options.parse_command_line()
  File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 267, in parse_command_line
    raise Error('Option %r requires a value' % name)
tornado.options.Error: Option 'xml' requires a value

You get not feedback or no data in the database tables if you attempt to do the following command;
user@ubuntu:~/RootTheBox$ sudo ./rootthebox.py --xml=/home/user/RootTheBox/file.xml
or
user@ubuntu:~/RootTheBox$ sudo ./rootthebox.py --xml=file.xml
or
user@ubuntu:~/RootTheBox$ sudo ./rootthebox.py --xml="file.xml"

The rtb.log contains the following;
[E 150519 07:16:17 BaseHandlers:189] Request from 127.0.0.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(_self.path_args, *_self.path_kwargs)
      File "/home/user/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, _args, *_kwargs)
      File "/home/user/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, _args, *_kwargs)
      File "/home/user/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, _args, *_kwargs)
      File "/home/user/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 424, in post
        if import_xml(fxml):
    NameError: global name 'import_xml' is not defined

**Comment by roobixx** [comment]
I added  "from setup.xmlsetup import import_xml" to the AdminGameHandlers.py file and no longer get a 404 error, however I do get a "failed to parse correctly" error...so some progress

**Comment by moloch--** [comment]
Yes I think a few things got renamed, so the parsing code needs a bit of love.

**Comment by n01g3L** [comment]
Adding "from setup.xmlsetup import import_xml" to AdminGameHandlers.py resolved the import issue for me. No more 404's and everything imports correctly. Mind you, I'm importing an exported xml created from the RTB scoring engine... not sure what "roobixx's" issue us.

**Comment by admin-support** [comment]
I was trying to import an exported xml created from the RTB scoring engine as well. So just directly exported the config and tried to import it again. No custom XML to mention, so if you try n01g3L's solution I think you will fix this bug as well.

**Comment by jeffg2k** [comment]
The import was added and my last tests of importing and exporting from RTB were successful - closing.
