### ISSUE TITLE
Error when new registration successfully completes.

### ISSUE THREAD

**Issue by AnarKyx01** [moloch--/RootTheBox#91]
When registering, upon successful registration, there is an error thrown on the back end. Not sure what effect this has, as I am not seeing anything odd from this.

[I 150520 19:37:20 base:666] ROLLBACK
[E 150520 19:37:20 ioloop:588] Exception in callback <functools.partial object at 0x7fa6983264c8>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 568, in _run_callback
        ret = callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(_args, *_kwargs)
      File "/home/anarky/PycharmProjects/RootTheBox/libs/EventManager.py", line 112, in push_team
        for user_id in self.auth_connections[team_id]:
    KeyError: 3L
[D 150520 19:37:20 BaseHandlers:255] Checking request origin 'ParseResult(scheme='http', netloc='192.168.1.205:8888', path='', params='', query='', fragment='')' ends with 'ParseResult(scheme='ws', netloc='localhost:8888', path='', params='', query='', fragment='')'
[D 150520 19:37:20 NotificationHandlers:46] [Web Socket] Opened public notification socket.

**Comment by moloch--** [comment]
Yea its in the event manager, it's responsible for sending real-time updates to other clients connected to the scoring engine (the notifications in the upper right). Looks like there's a bug in they way it pulls out the teams using `__getitem` (hence the key error).

**Comment by jeffg2k** [comment]
I'm no longer seeing this error on new registrations.  Closing issue.
