### ISSUE TITLE
How to setup team avatars

### ISSUE THREAD

**Issue by ghost** [moloch--/RootTheBox#98]
Hi,

I can not find a way within the database or the web interface to change or to set the avatars for the teams.

Where do I need to look?

Bye
MT

**Comment by megatraveler** [comment]
Hi,

found it at least.
Within the table users is a row called _avatar. I just punched there the names of the jpegs for each team and it worked.

Great work that Scorebot so far :) I like it.

Bye
MT

**Comment by moloch--** [comment]
Thanks, users should be able to set their own individual avatars once they log in under Settings in the upper right corner. However, we should also make this a Team/Admin feature methinks.

**Comment by jeffg2k** [comment]
Feature added in https://github.com/moloch--/RootTheBox/commit/ce239c609ecf1cff65c7333ca7fd1e03b1067c18
