### ISSUE TITLE
Keep redirecting to login page (re-authenticated problem)

### ISSUE THREAD

**Issue by qazbnm456** [moloch--/RootTheBox#99]
I don't know what happened while I keep getting this situation. Logging successfully but redirecting to login page again.

After digging into source code, I found out the problem is, when I was redirected to user page from PublicHandlers.py after 'Successful login: admin from 127.0.0.1' printed, 'self.session' is a None object in the 'authenticated function' in SecurityDecorators.py, leading me to login page again eventually.

I'm using OS X Yosemite 10.10.5, by the way.

Thanks :)

**Comment by moloch--** [comment]
Make sure memcached is running, I have this issue every once in a while. The memcached client silently fails if it cannot connect (sessions are currently stored in memcached). The Bootrstrap 3 re-write we'll be moving away from memcached for this and other reasons.

**Comment by qazbnm456** [comment]
The problem is solved by starting memcached. Thanks you, moloch--.

**Comment by nunoguerreiro** [comment]
have the same problem and even with the memcached in debug mode the RTB cannot pass the initial screen

also in rootthebox.cfg the memcache & port are well configured....
see image attached 
![rtb](https://user-images.githubusercontent.com/1771943/75598270-ea040800-5ab3-11ea-9379-f7a4c93897f3.png)

can someone help ?
Thanks.

**Comment by jeffg2k** [comment]
I pushed up a small change to the master branch that will raise an error when it can't connect to memcache to provide better visibility, but that's very likely the cause.  This is the issue when memcache is not working.

There is another branch labeled `memcached` that uses a newer memcache API if you want to give that a try.  You'll have to install [bmemcached](https://github.com/jaysonsantos/python-binary-memcached) for that branch.

**Comment by nunoguerreiro** [comment]
> I pushed up a small change to the master branch that will raise an error when it can't connect to memcache to provide better visibility, but that's very likely the cause. This is the issue when memcache is not working.
> 
> There is [another branch](https://github.com/moloch--/RootTheBox/tree/memcached) labeled `memcached` that uses a newer memcache API if you want to give that a try. You'll have to install [bmemcached](https://github.com/jaysonsantos/python-binary-memcached) for that branch.

Hi @jeffg2k  - worked - super cool.

configs are now:
[ Cache ]
memcached_host = "127.0.0.1"
memcached_port = 11211

and 
systemctl start memcached - memcached started.

Thanks a lot for the prompt support.
